### ISSUE TITLE
The partitions and batch method doesn't work

### ISSUE THREAD

**Issue by ljxgit** [neo4j-contrib/neo4j-spark-connector#100]
I use the dataframe API to generate a spark dataframe, but it  seems that the partitions() and batch() doesn't work, for example, I set the partitions(4), but the number of spark tasks still is one, what's the meaning of the partitions and batch?

neo.cypher("MATCH (n:Person) RETURN id(n) as id SKIP {_skip} LIMIT {_limit}").partitions(4).batch(25).loadDataFrame

**Comment by jexp** [comment]
How much data do you have in your graph to test this?

Yes it would run 4 partitions with a size of 25 each, making this 4 different tasks for 4 queries

**Comment by ljxgit** [comment]
A big graph about 125G
I got 4 partitions using **neo.cypher("MATCH (n:Person) RETURN id(n) as id limit 100").partitions(4).batch(25).loadDataFrame**, but each partition is same although with a siae of 25 each

**Comment by jexp** [comment]
right because you didn't add the {skip} and {limit} params in there

try

`neo.cypher("MATCH (n:Person) WITH n SKIP {skip} LIMIT {limit} RETURN id(n) as id").partitions(4).batch(25).loadDataFrame`

**Comment by moxious** [comment]
Hi - I’m writing with good news.  Over the last few months, we’ve been investing a lot of effort in bringing the neo4j spark connector up to newer versions of spark, supporting the Datasource API, and enabling multi-language support for things like Python and R.

Today we’re putting out a pre-release of this new version of the spark connector.

You can download a build here:
https://github.com/neo4j-contrib/neo4j-spark-connector/releases/tag/4.0.0-pre1

And see the documentation here:
http://5.9.211.195:8000/neo4j-spark-docs/1.0.0/

We’re in the process of updating our guidance & documentation on spark.  We’re sorry, but we are unable fix issues & carry forward support of the earlier version of the connector, based on a different API - which went up to and included version 2.4.5-M2.  

Moving forward, we will be focusing our efforts on the new approach above.

As a result, we’re closing the remaining issues attached to the old version, but we would very much appreciate feedback & issues raised against the new 4.0 series of the connector, which you’ll find on the 4.0 branch of the repo.  The connector is going to stay open source, and our current issue list & github planning is in the open and will stay that way.  

We hope you find it a big improvement over the previous version,  and would welcome collaboration around this!
