### ISSUE TITLE
Cluster nodes throwing java.lang.NullPointerException for large data

### ISSUE THREAD

**Issue by sandeepwww** [neo4j-contrib/neo4j-spark-connector#103]
I am trying to run a query to insert record(around 1.15bn rows) s from a dataFrame.

This is my logic, using this approach from an earlier issue here.
````
def splitDf(df: DataFrame, n:Int): Array[Dataset[Row]] = {
  val weights = Array.fill(n)(1.0)
  df.randomSplit(weights = weights)
}

def writeCypherWithDataFrame(sc: SparkContext,
                             dataFrame: DataFrame,
                             query : String,
                             partitions: Int = 100): Unit =
{
  val config = Neo4jConfig(sc.getConf)
  val columns = dataFrame.columns.toSeq
  dataFrame.repartition(partitions).foreachPartition(rows => {
    val params: AnyRef = rows.map(r =>
      Map
      (
        "properties" -> columns.map( c => (c, r.getAs[AnyRef](c))).toMap.asJava
      ).asJava).asJava
    Neo4jDataFrame.execute(config, query, Map("rows" -> params).asJava, write = true)
  })
}

val createNodeClusters = f""" 
CALL apoc.periodic.iterate(
 "UNWIND {rows} as row
  RETURN row.properties as r", "${queryString}"
  , {batchSize:10000,iterateList:true, retries:2, params: {rows: {rows}}})
"""

// Running Cypher query using neo4j Driver

val parallel = 80
val dfCount = 115551421
val MAX_RECORDS_PER_NEO4J_CALL = 60000
val MAX_RECORDS_PER_DATASET = parallel * MAX_RECORDS_PER_NEO4J_CALL
val NUM_OF_DATASETS = 1 + ( dfCount / MAX_RECORDS_PER_DATASET).toInt

var splitDfs = splitDf(factDf, NUM_OF_DATASETS )

splitDfs.foreach {
      dataSet => writeCypherWithDataFrame(sc, dataSet, createNodeClusters, parallel)
}

````
Spark Logs:
**org.apache.spark.SparkException: Job aborted due to stage failure: Task 22 in stage 626.0 failed 4 times, most recent failure: Lost task 22.3 in stage 626.0 (TID 30628, 10.139.64.7, executor 43): org.neo4j.driver.v1.exceptions.ServiceUnavailableException: Could not perform discovery. No routing servers available.**

Logs from the cluster node : 
**WARN  Error during iterate.commit 
WARN  1 times: java.lang.NullPointerException**

Using this approach, jobs are passing initially, but the logs show nodes going down with this error, but the LEADER keeps changing, so it works for some time and eventually terminates after many stages are cancelled due to the above error.

Stuck with this behaviour for long. Not sure how to take it from here.
All my connection pool settings are default.

**Comment by jexp** [comment]
I think for that volume it's much easier to just create a gzipped CSV from Spark and import it with the bulk importer into Neo4j.

You also left out your query string. In general you can increase the batch-size for UNWIND to 60k
you don't need apoc to insert 60k nodes/records.

If you create relationships do you have indexes/constraints for start and end-node id's ?
So that they are looked up in O(1) and not with a full databases scan?

**Comment by jexp** [comment]
If you have 1.15bn entries and send 60k sized batches you'd need roughly 20k operations to Neo4j.

Not sure what your Neo4j config looks like and what kind of disk/IO you're using as that needs to sustain the writing.

**Comment by sandeepwww** [comment]
Yes. I have already created the indexes for all the labels I am inserting - every merge is O(1)
This would need 20k operations but that is split to around 120 spark jobs. I am not sure if that is the right approach.
I resorted to this kind of splitting because of failures while doing the same for larger batches.
I am aware of the CSV import which is my last resort as this is a part of a daily pipeline that needs to run on SPARK.

Here's the query, ignore the syntax, modified slightly to share publicly.
```
  MERGE (person: Person{id: coalesce(r.id, -1)})
  ON CREATE SET  ... 4 properties ...
    
  FOREACH(ignoreMe IN CASE WHEN r.Guid IS NOT NULL AND r.Guid <> ''  THEN [1] ELSE [] END |
    MERGE (sub: Sub {guid:r.Guid}) ON CREATE SET ... 4 props ...)

  FOREACH(ignoreMe IN CASE WHEN r.ServiceLevel1 IS NOT NULL AND r.ServiceLevel1 <> '' THEN [1] ELSE [] END |
    MERGE (sLevel: Level {serviceLevel1: r.ServiceLevel1, serviceLevel2:r.ServiceLevel2})   
    MERGE (sub) - [slRel:HAS_SERVICE_LEVEL] -> (sLevel)
    SET  slRel.revenue = r.Revenue)
    
  MERGE (product:Product {productType:r.Product})
  MERGE (sku:SKU {name : r.Sku})
  MERGE (sub) - [:HAS_SKU] -> (sku)
  
  MERGE (sub) - [:IS_PRODUCT_TYPE] -> (product)
      
  MERGE (customer: Customer {tpid: coalesce(r.Id, -1)})
  ON CREATE SET customer.name = r.CustomerName
  MERGE (ind: Industry {name:  coalesce(r.IndustryName, 'Unknown')}) ON CREATE SET ind.key = r.CustomerIndustryKey
  MERGE (country: Country {country: coalesce(r.CustomerCountry,'Unknown')}) ON CREATE SET country.countryCode = coalesce(r.CustomerCountryCode, 'NA')
  MERGE (customer) -[:FROM_INDUSTRY] -> (ind)
  MERGE (customer) -[:FROM_COUNTRY] -> (country)
```

Can you please suggest how should I partition/batch my query to successfully complete all records and possibly without crashing any of the nodes.
Also, could you explain why I am seeing the errors I mentioned above?

**Comment by sandeepwww** [comment]
I have other relationship merges, which i am doing as another query. Currently stuck with failures in building the nodes itself.

**Comment by sandeepwww** [comment]
I found a workaround, I split the above query into multiple small queries, create each node and then create each relationship, which then works fine.
Also to avoid "threads not available" error, I increased the max thread pool to 800 on my nodes and made transaction memory OFF_HEAP.

Right now I don't see errors but something weird is happening : 

````
val subRelDf = factDf.unpersist.select("SubscriptionGuid","Sku").distinct().filter("SubscriptionGuid IS NOT NULL AND SubscriptionGuid <> '' ")
subRelDf.createOrReplaceTempView("SubRel")

val subsciptionQuery = """ 
  MATCH (subscription: Subscription {guid:r.SubscriptionGuid})
  MATCH (sku:SKU {name:r.Sku})
  MERGE (subscription) - [:HAS_SKU] -> (sku)
"""
writeCypherWithDataFrame(sc, subRelDf, baseRowQuery + subsciptionQuery)
````

A simple query like this one, I have a total of 11m relations that should have ideally been created. But on each run, it is creating only around 300k relations after a point. I am not clear, all the stages are passing. I tried to increase the number of partitions to reduce the number per each partition but still, there is no effect. 
Am I missing something here? How could we explain such behavior given that the query is getting executed successfully for atleast some nodes.

**Comment by sandeepwww** [comment]
@jexp can you please guide me in solving this problem. thanks.

**Comment by conker84** [comment]
> val subsciptionQuery = """ 
>   MATCH (subscription: Subscription {guid:r.SubscriptionGuid})
>   MATCH (sku:SKU {name:r.Sku})
>   MERGE (subscription) - [:HAS_SKU] -> (sku)
> """

@sandeepwww can you try with the following query?

```
val subsciptionQuery = """ 
  MATCH (subscription: Subscription {guid:r.SubscriptionGuid})
  MATCH (sku:SKU {name:r.Sku})
  CREATE (subscription) - [:HAS_SKU] -> (sku)
"""
```

I look forward to your feedback.

**Comment by conker84** [comment]
@sandeepwww ping

**Comment by conker84** [comment]
I'm closing this because we got no feedback feel free to reopen in case the issue is not solved
