### ISSUE TITLE
Leverage Spark DataSource APIs

### ISSUE THREAD

**Issue by conker84** [neo4j-contrib/neo4j-spark-connector#109]
Move the current business logic into the Spark DataSource API

https://www.slideshare.net/databricks/extending-spark-sql-24-with-new-data-sources-live-coding-session

We should consider with this refactoring if we could start directly with DataSource API V2 (supported from Spark 2.3):

https://databricks.com/session/apache-spark-data-source-v2

https://jaceklaskowski.gitbooks.io/mastering-spark-sql/spark-sql-DataSourceV2.html

The old datasource api should be removed in spark 3 so the last version is future-proof

**Comment by moxious** [comment]
Closed by development of the 4.0 version of the connector
