### ISSUE TITLE
Persist RDD/DataSet from Spark to Neo4j

### ISSUE THREAD

**Issue by lansaloltd** [neo4j-contrib/neo4j-spark-connector#110]
Problem:

**I have an RDD/DataFrame/Dataset (representing a Graph) and I want to persist it in Neo4J (efficiently).** 

I read somewhere that this connector should suit my needs my I'm not sure that is actually the case. Or perhaps I'm missing something.

Anyway, this connector is based on the neo4j-java-driver. Following the examples, it all happens in the `Neo4jDataFrame` class if I'm not mistaken.

First cause of concern, in both `createNodes` and `mergeEdgeList` there is a `dataFrame.count() ` followed by a `dataFrame.foreachPartition`. Both are actions, and there is no cache of the dataFrame. As it is that should trigger the the computation of the same dataframe from the beginning **twice**. 

Second cause of concern: 
in the `dataFrame.foreachPartition` you basically create a Neo4J driver, get a session from it and then close both, for each record in the dataframe (if I read it correctly, that is what the `execute` method does). Hence the second cause of concern, accordingly to the Neo4J documentation a `driver` is a quite expensive resource to obtain as opposed to a `session` with is cheap and expendable. Also, I might be wrong, but I don't think a transaction can span over a session, so I can't see the benefit of running all that within a transactional context when you open and close the session for each record in the Dataframe.

Could you please throw some light on the above points? Am I missing something pretty obvious?

**Comment by moxious** [comment]
Hi - I’m writing with good news.  Over the last few months, we’ve been investing a lot of effort in bringing the neo4j spark connector up to newer versions of spark, supporting the Datasource API, and enabling multi-language support for things like Python and R.

Today we’re putting out a pre-release of this new version of the spark connector.

You can download a build here:
https://github.com/neo4j-contrib/neo4j-spark-connector/releases/tag/4.0.0-pre1

And see the documentation here:
http://5.9.211.195:8000/neo4j-spark-docs/1.0.0/

We’re in the process of updating our guidance & documentation on spark.  We’re sorry, but we are unable fix issues & carry forward support of the earlier version of the connector, based on a different API - which went up to and included version 2.4.5-M2.  

Moving forward, we will be focusing our efforts on the new approach above.

As a result, we’re closing the remaining issues attached to the old version, but we would very much appreciate feedback & issues raised against the new 4.0 series of the connector, which you’ll find on the 4.0 branch of the repo.  The connector is going to stay open source, and our current issue list & github planning is in the open and will stay that way.  

We hope you find it a big improvement over the previous version,  and would welcome collaboration around this!
