### ISSUE TITLE
How use encrypted client connections

### ISSUE THREAD

**Issue by wjlight** [neo4j-contrib/neo4j-spark-connector#111]
My neo4j conf have：

`dbms.connector.bolt.tls_level=REQUIRED`

but，when use

`Neo4j(sc)`

have error

> org.neo4j.driver.v1.exceptions.ServiceUnava
ilableException: Connection to the database terminated. This can happen due to n
etwork instabilities, or due to restarts of the database

How can I use encrypted client connections with neo4j-spark-connector?

**Comment by conker84** [comment]
closed via 0ace7db
