### ISSUE TITLE
load Scala object from loadRawRdd

### ISSUE THREAD

**Issue by sahand1995** [neo4j-contrib/neo4j-spark-connector#117]
I manually convert every java.object to scala.object for further processing.Is there a way to directly load scala.object from loadRawRdd OR LoadRdd[T] 

For example:
`
      val query = neo.cypher(
        "MATCH (n:Person)-[r]-(m:Person) " +
                "where n.name='nahid' " +
                "unwind r.weight as weight " +
                "return weight, n.name "
      ).loadRowRdd
`
          
r.weigth is an array in neo4j and n.name is a string : 
`r.weight = [1,2,3]`
`n.name = "nahid"`

So for converting to scala.Integer every time I should do the following : 

`val result = query.map(x =>x(0).asInstanceOf[scala.Long].toInt)`

Is there a better way? :(

**Comment by JakobWyatt-VGW** [comment]
A collaborator here can probably have a better look at this, but I doubt there is a better way within the library.

**Comment by conker84** [comment]
this should work:

```scala
val rdd = Neo4j(sc).cypher("MATCH (n:Person) RETURN collect(id(n)) AS ids").loadRowRdd
val data = rdd.flatMap(x => x(0).asInstanceOf[Array[Object]]).collect() // look here
data.foreach(println)
```

**Comment by jexp** [comment]
@sahand1995 ping?
