### ISSUE TITLE
Major version release and Pyspark interface

### ISSUE THREAD

**Issue by JakobWyatt-VGW** [neo4j-contrib/neo4j-spark-connector#118]
Hi,
I've been doing a lot of work on a fork of this library for use at my workplace.
It adds in support for a python interface, however this interface changes the scala library API significantly.
Would it be considered to merge this into a major release? Or are the changes to the interface too drastic?

**Comment by jexp** [comment]
Hi Jakob, this is pretty cool.

Can you outline the changes to the Scala API in more detail (especially from a users point of view)?

And does it *have* to change the API for Scala users? Or could we have a more pythonic API on the side that internally calls the same infrastructure but is just nicer for python?

Do you have any R experience? So that we could/would know if that would also good for Rspark users?

**Comment by JakobWyatt-VGW** [comment]
I've been using the post here to guide my changes: https://diogoalexandrefranco.github.io/scala-code-in-pyspark/
Essentially, the summary is that:
- Scala `object`s can easily be created from Pyspark.
- Scala `class` constructors cannot be called from Pyspark.
- Methods on an object can be called easily, however accessing the spark types on either end.
- SparkSession, SQLContext, and DataFrame objects can be passed with no conversion on the Scala side.
- SparkContext and RDD objects need some conversion on the Scala side (When passed in, not when returning).

This library can essentially be split into 4 parts: Builder API, GraphX API, DataFrame API, GraphFrame API, and RDD API.
I've been using the architecture from [graphframes](https://github.com/graphframes/graphframes) where possible. The way they seem to be doing things is to have an overarching `PythonAPI` object with factory methods that construct objects from different classes.

The builder API can already be used without any modification. As the Neo4j object takes a SparkContext, the `PythonAPI` factory method can simply convert this before constructing the Neo4j object and passing it back to Pyspark.

The Neo4jGraph and Neo4jDataFrame API requires some modification. As almost every method in these objects is input a SparkContext, the only way to keep the API the same is to rewrite Python versions of these classes that convert the python spark context into a SparkContext.

This is possible, but not really on the "I'm getting paid for this" timeframe. Therefore, I have instead converted these objects into classes that input a SparkContext, so that they can be created from the PythonAPI factory methods. This means the new usage is now something like:
`(new Neo4jDataFrame(sc)).doSomething(args)`

This could be simplified by having passthrough methods within the object of the same name. However, I haven't really looked into this, as I do have a deadline to get this project done by.

I have not investigated the RDD or GraphFrame API much.

As for the R interface, it seems possible already (although not very clean): https://jozef.io/r204-spark-r-invoke-scala/
Although I'm not too sure about how spark objects are passed between Scala and R.

The repository of the changes is here: https://github.com/JakobWyatt/neo4j-spark-connector
Please note that I've also been changing some usages of the SQLContext (deprecated) into SparkSession, and removing some redundant Java tests - obviously the changes would be cherry picked, I'm not expecting the entire repo to be merged in.

**Comment by jexp** [comment]
Thanks a lot for the detailed explanation !!

If we can find a way to disturb the existing API as little as possible, by e.g. having a PythonAPI object I would very much prefer that.

Can you send a PR with your changes and we can discuss on that?

**Comment by JakobWyatt-VGW** [comment]
Sure, I'm a bit under the pump at work at the moment and on holiday during Jan, but I'll see if I can get something done early Feb.

**Comment by jexp** [comment]
No worries, happy holidays and enjoy your vacation!

**Comment by jexp** [comment]
@conker84 also wanted to explore the new Spark DataSource APIs as an alternative.
Would love to hear your feedback on that as soon as a PR / examples are ready.

**Comment by conker84** [comment]
@JakobWyatt-VGW are you available for a call?

**Comment by JakobWyatt-VGW** [comment]
@conker84 I've stopped working on this PR at the moment as we've stopped using Neo4j for this project. However, I'm still happy to help give any pointers on what I ended up doing.
Most of it is in the post above, however.

**Comment by zbacjxx** [comment]
@conker84 - are you progressing this - I cant see Jakobs repo but would be interested in helping out with this.

I agree that you shouldnt be breaking your core API (at least initially) and that we can address pythonic style issues in the python layer.

**Comment by conker84** [comment]
@zbacjxx we're finalizing the support for Neo4j 4.0 and then we'll work on this, my idea is to leverage the new datasource apis in order to use them via the programming languages supported by spark.
It you want to chat on this please let me know!

**Comment by yukioichida** [comment]
Hi,

Are you progressing in this issue? I intend to use this connector in our pyspark module but I did not find any pull request related to this issue.

**Comment by moxious** [comment]
We are actively developing a new version on the 4 branch which will address this issue and uses newer spark data source APIs.  The API for the connector will change.  For the meantime, we will leave this issue open so folks can see what is happening, but eventually this issue will be closed by the formal release of a 4.0.0 version of the connector, expected by end of year 2020.

**Comment by moxious** [comment]
Hi - I’m writing with good news.  Over the last few months, we’ve been investing a lot of effort in bringing the neo4j spark connector up to newer versions of spark, supporting the Datasource API, and enabling multi-language support for things like Python and R.

Today we’re putting out a pre-release of this new version of the spark connector.

You can download a build here:
https://github.com/neo4j-contrib/neo4j-spark-connector/releases/tag/4.0.0-pre1

And see the documentation here:
http://5.9.211.195:8000/neo4j-spark-docs/1.0.0/

We’re in the process of updating our guidance & documentation on spark.  We’re sorry, but we are unable fix issues & carry forward support of the earlier version of the connector, based on a different API - which went up to and included version 2.4.5-M2.  

Moving forward, we will be focusing our efforts on the new approach above.

As a result, we’re closing the remaining issues attached to the old version, but we would very much appreciate feedback & issues raised against the new 4.0 series of the connector, which you’ll find on the 4.0 branch of the repo.  The connector is going to stay open source, and our current issue list & github planning is in the open and will stay that way.  

We hope you find it a big improvement over the previous version,  and would welcome collaboration around this!
