### ISSUE TITLE
It seems that Neo4jRowRDD only has one partition?

### ISSUE THREAD

**Issue by shifeng258** [neo4j-contrib/neo4j-spark-connector#12]
I have a Neo4j database with 400 million vertices and 600 million edges.I use  Neo4jRowRDD in spark and then the excutor out of memory.I read the source code of Neo4jRowRDD ,and it eems that Neo4jRowRDD only has one partition.Am i right?

**Comment by jexp** [comment]
Good question

What exactly do you pull in? Which query do you use? And which version of neo4j?

Reading from neo is currently done with one thread returning a streaming Iterator and subsequent operations can use more partitions. 

Can you share the exact exception?

Von meinem iPhone gesendet

**Comment by shifeng258** [comment]
I use  neo4j version 3. I want to use spark to do pageRank and Triangle Counting.I have to load the graph to spark first.It is too slow If reading from neo is currently done with one thread.Neo4jRowRDD  with only one partiton can not deal with big data.

**Comment by jexp** [comment]
But no matter how many partitions the original RDD has (it pulls it from Neo4j in a single query) but you can batch it, you still can repartition the data.

Example for batching is here: 

https://gist.github.com/jexp/0dfad34d49a16000e804#file-spark-neo4j-pagerank-scala-L35

So you can do _something_ like this:

```scala
val total = 600000000
val batch = total/1000000

val q = "MATCH (p1:Page)-[:Link]->(p2) RETURN id(p1) as from, id(p2) as to skip {skip} limit 1000000"
// read batches of 100k rows of relationships with skip <window> limit 100k
// each otherwise Spark runs into OOM keeping 100M rows at once
val links = sc.range(0,batch).repartition(batch).mapPartitionsWithIndex( (i,p) => {
    p.flatMap( skip => Neo4jRowRDD(sc, q, Seq("skip"->skip*1000000)))
})

```

**Comment by shifeng258** [comment]
@jexp The "developer-manual" said that "By using SKIP, the result set will get trimmed from the top. Please note that no guarantees are made on the order of the result unless the query specifies the ORDER BY clause."Is there a duplicate data between partitions of Neo4jRowRDD while not specifies the ORDER BY clause?

**Comment by jexp** [comment]
@shifeng258 
I finished the loading API over the weekend and would love your feedback. 
Writing would be next.

See: https://github.com/neo4j-contrib/neo4j-spark-connector#builder-api

**Comment by jexp** [comment]
Should work now with the new API
