### ISSUE TITLE
spark.neo4j.bolt Configuration

### ISSUE THREAD

**Issue by zbacjxx** [neo4j-contrib/neo4j-spark-connector#124]
Being able to configure the bolt connection properties through the SparkContext.SparkConf is problematic in a multi user notebook environment such as Zeppelin, where this would need to be configured (for a single user, with a plaintext password) in the interpreter config.  

Instead we have updated the Neo4jConfig class to use priortitise the use of environment variables (if present) over the following properties on the SparkConf:

spark.neo4j.bolt.url
spark.neo4j.bolt.user
spark.neo4j.bolt.password

This was obviously the least invasive mechanism I could quickly find, but worth considering other options instead of/as well as this

**Comment by jexp** [comment]
Thanks a lot for your thinking, can you turn that into a PR. Would you mind sign our CLA before.
https://neo4j.com/developer/cla

Would that also work in a spark environment? just curious. And how do other connectors eg. to RDBMS handle it.

**Comment by zbacjxx** [comment]
Hi

My Name is Richard Hay (Richard.hay@bigspark.dev. zbacjxx)

I agree to the terms in the attached Neo4j contributor licence Agreement as attached

John - yes should work for a Spark environment I will PR and test over the weekend as I am working on an urgent cover-19 modelling project at the moment and I need to deploy the forked version to Zeppelin ASAP

Thanks
Rich






Richard Hay
Director bigspark.dev 
+44 (0)7902268602
richard.hay@bigspark.dev

**Comment by moxious** [comment]
Hi - I’m writing with good news.  Over the last few months, we’ve been investing a lot of effort in bringing the neo4j spark connector up to newer versions of spark, supporting the Datasource API, and enabling multi-language support for things like Python and R.

Today we’re putting out a pre-release of this new version of the spark connector.

You can download a build here:
https://github.com/neo4j-contrib/neo4j-spark-connector/releases/tag/4.0.0-pre1

And see the documentation here:
http://5.9.211.195:8000/neo4j-spark-docs/1.0.0/

We’re in the process of updating our guidance & documentation on spark.  We’re sorry, but we are unable fix issues & carry forward support of the earlier version of the connector, based on a different API - which went up to and included version 2.4.5-M2.  

Moving forward, we will be focusing our efforts on the new approach above.

As a result, we’re closing the remaining issues attached to the old version, but we would very much appreciate feedback & issues raised against the new 4.0 series of the connector, which you’ll find on the 4.0 branch of the repo.  The connector is going to stay open source, and our current issue list & github planning is in the open and will stay that way.  

We hope you find it a big improvement over the previous version,  and would welcome collaboration around this!
