### ISSUE TITLE
Can I have multiple neo4j inside sparkContext

### ISSUE THREAD

**Issue by sahand1995** [neo4j-contrib/neo4j-spark-connector#125]
Let Say I have two neo4j , How can I set them in a sparkContext?
 as I understand we can do this by creating different sparkContext which means multiple spakrContext inside single Jvm. 

> Although configuration option spark.driver.allowMultipleContexts exists, it is misleading because usage of multiple Spark contexts is discouraged. This option is used only for Spark internal tests and is not supposed to be used in user programs. You can get unexpected results while running more than one Spark context in a single JVM.

So should I have multiple sparks for each neo4j? Is there another way or am I thinking wrong

https://stackoverflow.com/questions/61031696/run-multiple-neo4j-driver-within-a-spark-context

**Comment by conker84** [comment]
Unfortunately at this very moment you can achieve your goal only by changing `spark.driver.allowMultipleContexts` to `true`.
We plan to change this behaviour in the future.

**Comment by moxious** [comment]
Hi - I’m writing with good news.  Over the last few months, we’ve been investing a lot of effort in bringing the neo4j spark connector up to newer versions of spark, supporting the Datasource API, and enabling multi-language support for things like Python and R.

Today we’re putting out a pre-release of this new version of the spark connector.

You can download a build here:
https://github.com/neo4j-contrib/neo4j-spark-connector/releases/tag/4.0.0-pre1

And see the documentation here:
http://5.9.211.195:8000/neo4j-spark-docs/1.0.0/

We’re in the process of updating our guidance & documentation on spark.  We’re sorry, but we are unable fix issues & carry forward support of the earlier version of the connector, based on a different API - which went up to and included version 2.4.5-M2.  

Moving forward, we will be focusing our efforts on the new approach above.

As a result, we’re closing the remaining issues attached to the old version, but we would very much appreciate feedback & issues raised against the new 4.0 series of the connector, which you’ll find on the 4.0 branch of the repo.  The connector is going to stay open source, and our current issue list & github planning is in the open and will stay that way.  

We hope you find it a big improvement over the previous version,  and would welcome collaboration around this!
