### ISSUE TITLE
Transaction retries?

### ISSUE THREAD

**Issue by moxious** [neo4j-contrib/neo4j-spark-connector#127]
Some users have reported failing batches of transactions when writing partitions in parallel, due to lock timeout exceptions.   We've advised not to write in parallel and to single-track transactions.  But still the question remains:  if you write a batch of 100k records in transactional batches, how do we detect & retry failed batches, to guarantee that the *entire* write succeeds or fails?

**Comment by jexp** [comment]
Currently we rely on the driver to retry. We could also fail and have spark do the retry instead.

**Comment by moxious** [comment]
I have a trello card open with the drivers team about certain aspects of configurability here.   Driver retries are fine, but eventually these will fail as well.   There's one issue of how to configure the retry strategy the driver uses (this might just be exposing more driver config properties) -- and the second issue is what to do, if you have 5k transactions, and 7 of them fail.
