### ISSUE TITLE
Supporting temporal data types using Neo4jDataFrame.mergeEdgeList

### ISSUE THREAD

**Issue by ronassa** [neo4j-contrib/neo4j-spark-connector#132]
Spark 2.4.6
neo4j-spark-connector 2.4.5-M1

Getting the below error when trying when using timestamp column in the data frame.
 
this is happening since Spark SQL timestamp is converted to java.sql.timestamp which is not supported by the driver, is there any workaround to be able to insert ZonedDateTime using Neo4jDataFrame.mergeEdgeList ?

org.neo4j.driver.exceptions.ClientException: Unable to convert java.sql.Timestamp to Neo4j Value.
	at org.neo4j.driver.Values.value(Values.java:134)
	at org.neo4j.driver.Values.value(Values.java:297)
	at org.neo4j.driver.Values.value(Values.java:119)
	at org.neo4j.driver.Values.value(Values.java:297)
	at org.neo4j.driver.Values.value(Values.java:119)
	at org.neo4j.driver.Values.value(Values.java:236)
	at org.neo4j.driver.Values.value(Values.java:118)
	at org.neo4j.driver.internal.util.Extract.mapOfValues(Extract.java:203)
	at org.neo4j.driver.internal.AbstractQueryRunner.parameters(AbstractQueryRunner.java:69)
	at org.neo4j.driver.internal.AbstractQueryRunner.run(AbstractQueryRunner.java:43)
	at org.neo4j.spark.dataframe.Neo4jDataFrame$$anonfun$execute$1$$anonfun$apply$6$$anon$1.execute(Neo4jDataFrame.scala:65)
	at

**Comment by conker84** [comment]
If your source `df` contains a `java.sql.Timestamp` you should convert it to a `ZonedDateTime` or `LocalDateTime` or `Long`

**Comment by ronassa** [comment]
How can I use ZoneDateTime in a Spark data frame? (without using User Defined Types)

does it make sense to add 
`if ( value instanceof java.sql.Timestamp ) { return value( (value.toLocalDateTime()) value ); }`
to https://github.com/neo4j/neo4j-java-driver/blob/4.1/driver/src/main/java/org/neo4j/driver/Values.java ?

**Comment by jexp** [comment]
We should also handle it in the spark-connector. I was pretty sure I had that in the code originally. @conker84 can you check?

**Comment by conker84** [comment]
I looked into the branch v2.4.1-M1:
https://github.com/neo4j-contrib/neo4j-spark-connector/blob/2.4.1-M1/src/main/scala/org/neo4j/spark/dataframe/Neo4jDataFrame.scala

And there is no conversion for input data, but I agree with you that should be something that we should provide directly into the connector.

**Comment by conker84** [comment]
> How can I use ZoneDateTime in a Spark data frame? (without using User Defined Types)

The best solution at this very moment is to transform it into a long but we can improve the connector by let it doing the conversion for you.

> does it make sense to add
> `if ( value instanceof java.sql.Timestamp ) { return value( (value.toLocalDateTime()) value ); }`
> to https://github.com/neo4j/neo4j-java-driver/blob/4.1/driver/src/main/java/org/neo4j/driver/Values.java ?

No I think that it makes sense put the management directly into the Spark Connector

**Comment by ronassa** [comment]
Thanks, @conker84,  but that means it will be stored as long in Neo4j, not temporal data type, right?
There is any workaround that the data will be stored as temporal datatype?

**Comment by conker84** [comment]
[neo4j-spark-connector-full-2.4.5-M1.jar.zip](https://github.com/neo4j-contrib/neo4j-spark-connector/files/4864780/neo4j-spark-connector-full-2.4.5-M1.jar.zip)

@ronassa Can you try with the jar above?

It's created from the PR #136

**Comment by ronassa** [comment]
Thanks, @conker84, I'll test it and let you know.

**Comment by ronassa** [comment]
sorry for the late response, it does working for me. thanks

**Comment by waelAbass** [comment]
I am using maven and I want  dependency for neo4j-spark-connector-full-2.4.5-M1.jar.zip
