### ISSUE TITLE
Support for Scala 2.12.x

### ISSUE THREAD

**Issue by SebastianKG** [neo4j-contrib/neo4j-spark-connector#138]
I was blocked while trying to get the spark connector up and running in an existing project when I realised that neo4j-spark-connector is only compatible with Scala 2.11.x. I have also read that Spark and Neo4j's own drivers were stuck on 2.11 for some time, but I believe both are now available for 2.12. Are there any plans to upgrade to 2.12 at this time?

**Comment by jexp** [comment]
We should use whatever spark is supporting.

**Comment by SebastianKG** [comment]
As of September 2018, Scala 2.12 has been supported https://issues.apache.org/jira/browse/SPARK-14220 (the blog post for the release of the correspondig version, Spark 2.4.0, was posted on November 8th, 2018).

**Comment by SebastianKG** [comment]
@conker84 thanks so much for upgrading the dependency so quickly. Is there any chance this could be put into a new release, or is that waiting on achieving a certain milestone?

**Comment by jexp** [comment]
@SebastianKG sorry I was on vacation just returned, I can try to put out a release for this this week.

**Comment by jexp** [comment]
Until then you can also just build it yourself.

**Comment by jexp** [comment]
Sorry it took so long, here you go: https://github.com/neo4j-contrib/neo4j-spark-connector/releases/tag/2.4.5-M2
also on spark-packages https://spark-packages.org/package/neo4j-contrib/neo4j-spark-connector
