### ISSUE TITLE
Create Option Class in order to connect to Neo4j

### ISSUE THREAD

**Issue by conker84** [neo4j-contrib/neo4j-spark-connector#139]
We want to create a shared class between read/write-support that allows to connect to Neo4j in every scenario like we did in the Neo4j Streams Kafka Connect Plugin:
https://github.com/neo4j-contrib/neo4j-streams/blob/3.5/kafka-connect-neo4j/src/main/kotlin/streams/kafka/connect/sink/Neo4jSinkConnectorConfig.kt

**Comment by moxious** [comment]
👍👍👍

**Comment by conker84** [comment]
closed via e6b166f
