### ISSUE TITLE
Neo4j database error while creating nodes

### ISSUE THREAD

**Issue by aitormars** [neo4j-contrib/neo4j-spark-connector#150]
I'm using the following versions:

- Spark:2.4.0
- Neo4j:3.5.12
- neo4j-spark-connector:2.4.5-M1

When I tried to create the nodes the following error raise:

'''
org.neo4j.driver.exceptions.ClientException: Database name parameter for selecting database is not supported in Bolt Protocol Version 3. Database name: 'admin'
'''
I tried to configure the database, but i got the same error:

val sparkConf = new SparkConf()
      .setAppName("Data Processing")
      .set("spark.neo4j.bolt.url", "bolt://127.0.0.1:7687")
      .set("spark.neo4j.bolt.user", "neo4j")
      .set("spark.neo4j.bolt.password", "neo4j")
      .set("spark.neo4j.bolt.database", "graph.db")

Thanks,

**Comment by conker84** [comment]
With Neo4j 3.5 you don't need to set the database:
```scala
val sparkConf = new SparkConf()
  .setAppName("Data Processing")
  .set("spark.neo4j.bolt.url", "bolt://127.0.0.1:7687")
  .set("spark.neo4j.bolt.user", "neo4j")
  .set("spark.neo4j.bolt.password", "neo4j")
```

**Comment by aitormars** [comment]
Hello @conker84 ,
I tried without database setting and I got the same error.

Regards,

**Comment by conker84** [comment]
@aitormars can you please try without the `bolt` word:

```scala
val sparkConf = new SparkConf()
  .setAppName("Data Processing")
  .set("spark.neo4j.url", "bolt://127.0.0.1:7687")
  .set("spark.neo4j.user", "neo4j")
  .set("spark.neo4j.password", "neo4j")
```

**Comment by Nevernamed** [comment]
> With Neo4j 3.5 you don't need to set the database:
> 
> ```scala
> val sparkConf = new SparkConf()
>   .setAppName("Data Processing")
>   .set("spark.neo4j.bolt.url", "bolt://127.0.0.1:7687")
>   .set("spark.neo4j.bolt.user", "neo4j")
>   .set("spark.neo4j.bolt.password", "neo4j")
> ```

with Neo4j 4.1 how can i select the database?

**Comment by conker84** [comment]
@Nevernamed you are using deprecated APIs please check the docs for then new connector:

https://neo4j.com/docs/spark/current/
