### ISSUE TITLE
user agent flagging

### ISSUE THREAD

**Issue by moxious** [neo4j-contrib/neo4j-spark-connector#152]
In driver usage when communicating to Neo4j, please set the user agent to be the name of the program.  This is useful later on for things like Aura, which can then detect how many users of a software are there.

We can get you a technical example later of how to do this with java if you're not already familiar.  Otherwise, a simple way to do it is instead of executing MATCH (n) RETURN n LIMIT 10 I will sometimes do `WITH "MySoftware-v1.0" as userAgent MATCH (n) RETURN n LIMIT 10` and then it's obvious in the logs every time.

**Comment by conker84** [comment]
It could be very simple:

**Comment by conker84** [comment]
https://neo4j.com/docs/api/java-driver/current/org/neo4j/driver/Config.ConfigBuilder.html#withUserAgent-java.lang.String-

**Comment by moxious** [comment]
I think this issue may have already been addressed by an earlier commit, may be closeable.  WDYT?

**Comment by moxious** [comment]
Closed by previous commit & agreement
