### ISSUE TITLE
Neo4jGraph.execute issue : Unable to convert scala.Tuple2 to Neo4j value

### ISSUE THREAD

**Issue by sjishan** [neo4j-contrib/neo4j-spark-connector#16]
Hi any help regarding how to send the parameters correctly will be appreciated. I tried to emulate from the source code. Attach herewith is the screenshot.

![capture](https://cloud.githubusercontent.com/assets/5510397/17632287/5a09e060-607c-11e6-892a-6c067445b1d6.PNG)

**Comment by jexp** [comment]
Hi,

I'd do it like this:

```
    val data = List(Map("id"->1,"name"->"Test").asJava).asJava
    Neo4jGraph.execute(sc, "UNWIND {data} as row CREATE (n:Test {id:row.id}) SET n.name = row.name", Seq(("data",data)))
```

**Comment by jexp** [comment]
But good feedback, I think I change that piece of the API

**Comment by sjishan** [comment]
Thank you very much for your response. On a different note, would you be able to make some time to address the previous issue #15 . I changed a dataframe to rdd and then map on each partition. I am getting Java NullPointerException.

**Comment by jexp** [comment]
Can we close this one?

**Comment by sjishan** [comment]
Thank you. Sure.
