### ISSUE TITLE
Add support for PushDownFilters

### ISSUE THREAD

**Issue by utnaf** [neo4j-contrib/neo4j-spark-connector#161]
Add support for PushDownFilters as stated in #142 and #141 

We decided to do a different PR for these features to avoid having too many in the first one. 

Here's the doc for [SupportPushDownFilters](https://jaceklaskowski.gitbooks.io/mastering-spark-sql/content/spark-sql-SupportsPushDownFilters.html).

**Comment by utnaf** [comment]
Removed PushDownColumn support from this issue since is going to be added in another PR.

**Comment by moxious** [comment]
Closed by https://github.com/neo4j-contrib/neo4j-spark-connector/pull/162
