### ISSUE TITLE
Exception in thread "main" java.lang.NoSuchFieldError: NULL

### ISSUE THREAD

**Issue by waelAbass** [neo4j-contrib/neo4j-spark-connector#165]
I am using spark neo4j connector 2.4.5-M1,  programming language: java version 8 and getting the above error  when using  neo4j-java-driver version 1.7.5 : 

```
Exception in thread "main" java.lang.NoSuchFieldError: NULL
	at org.neo4j.driver.Values.<clinit>(Values.java:85)
	at org.neo4j.driver.AuthTokens.basic(AuthTokens.java:72)
	at org.neo4j.driver.AuthTokens.basic(AuthTokens.java:54)
	at org.neo4j.spark.Neo4jConfig.driver(Neo4jConfig.scala:19)
	at org.neo4j.spark.Neo4jConfig.driver(Neo4jConfig.scala:23)
	at org.neo4j.spark.dataframe.Neo4jDataFrame$.apply(Neo4jDataFrame.scala:121)
	at org.neo4j.spark.dataframe.Neo4jDataFrame.apply(Neo4jDataFrame.scala)
	at org.neo4j.spark.Neo4JavaSparkContext.queryDF(Neo4JavaSparkContext.java:55)
	at com.etl.sparkneo.testIntegration.main(testIntegration.java:36)
for java  code as follows :- 
  SparkConf sparkConf = new SparkConf().setAppName("spark etl").set("spark.neo4j.bolt.url", "bolt://localhost:7687").set("spark.neo4j.bolt.user", "neo4j").set("spark.neo4j.bolt.password", "123456");
        //SparkContext sc = new SparkContext(sparkConf);
        SparkSession session = SparkSession.builder().config(sparkConf)
                .master("local[2]")
                .getOrCreate();
   JavaRDD<Row> data = v.queryDF("MATCH (m:player) RETURN m.YOB, m.name,m.POB ", null).toJavaRDD();
when using neo4j-java-driver version 4.0.1 : 
Exception in thread "main" org.neo4j.driver.exceptions.FatalDiscoveryException: Database does not exist. Database name: "123456"

	at org.neo4j.driver.internal.util.Futures.blockingGet(Futures.java:143)
	at org.neo4j.driver.internal.InternalResult.blockingGet(InternalResult.java:128)
	at org.neo4j.driver.internal.InternalResult.hasNext(InternalResult.java:64)
	at org.neo4j.spark.dataframe.Neo4jDataFrame$$anon$2.execute(Neo4jDataFrame.scala:127)
	at org.neo4j.spark.dataframe.Neo4jDataFrame$$anon$2.execute(Neo4jDataFrame.scala:124)
	at org.neo4j.driver.internal.InternalSession.lambda$transaction$4(InternalSession.java:150)
	at org.neo4j.driver.internal.InternalSession$$Lambda$11/1479809423.get(Unknown Source)
	at org.neo4j.driver.internal.retry.ExponentialBackoffRetryLogic.retry(ExponentialBackoffRetryLogic.java:101)
	at org.neo4j.driver.internal.InternalSession.transaction(InternalSession.java:146)
	at org.neo4j.driver.internal.InternalSession.readTransaction(InternalSession.java:112)
	at org.neo4j.driver.internal.InternalSession.readTransaction(InternalSession.java:106)
	at org.neo4j.spark.dataframe.Neo4jDataFrame$.apply(Neo4jDataFrame.scala:133)
	at org.neo4j.spark.dataframe.Neo4jDataFrame.apply(Neo4jDataFrame.scala)
	at org.neo4j.spark.Neo4JavaSparkContext.queryDF(Neo4JavaSparkContext.java:55)
	at com.etl.sparkneo.testIntegration.main(testIntegration.java:36)
```

here is maven pom.xml file 

```
 <dependencies>
        <!-- list of dependencies -->
        <dependency>
            <groupId>org.neo4j.driver</groupId>
            <artifactId>neo4j-java-driver</artifactId>
            <version>4.0.1</version>
        </dependency>
        <dependency>
            <groupId>org.apache.spark</groupId>
            <artifactId>spark-core_2.11</artifactId>
            <version>2.4.5</version>
        </dependency>
        <dependency>
            <groupId>org.apache.spark</groupId>
            <artifactId>spark-sql_2.11</artifactId>
            <version>2.4.5</version>
        </dependency>
        <!-- https://mvnrepository.com/artifact/neo4j-contrib/neo4j-spark-connector -->
        <dependency>
            <groupId>neo4j-contrib</groupId>
            <artifactId>neo4j-spark-connector</artifactId>
            <version>2.4.5-M1</version>
        </dependency>
   
    </dependencies>
    <repositories>
        <repository>
            <id>spark-repo</id>
            <url>http://dl.bintray.com/spark-packages/maven/</url>
        </repository>
    </repositories>

```

**Comment by jexp** [comment]
did you see that the config options changed?
and the bolt driver is packaged so you shouldn't need to use one yourself.

**Comment by waelAbass** [comment]
How to solve this problem?

**Comment by jexp** [comment]
I also think you should switch to Java 11.

**Just** depend on the spark connector, no neo4j driver or such.

**Comment by conker84** [comment]
> I am using spark neo4j connector 2.4.5-M1, programming language: java version 8 and getting the above error when using neo4j-java-driver version 1.7.5 :
> 
> ```
> Exception in thread "main" java.lang.NoSuchFieldError: NULL
> 	at org.neo4j.driver.Values.<clinit>(Values.java:85)
> 	at org.neo4j.driver.AuthTokens.basic(AuthTokens.java:72)
> 	at org.neo4j.driver.AuthTokens.basic(AuthTokens.java:54)
> 	at org.neo4j.spark.Neo4jConfig.driver(Neo4jConfig.scala:19)
> 	at org.neo4j.spark.Neo4jConfig.driver(Neo4jConfig.scala:23)
> 	at org.neo4j.spark.dataframe.Neo4jDataFrame$.apply(Neo4jDataFrame.scala:121)
> 	at org.neo4j.spark.dataframe.Neo4jDataFrame.apply(Neo4jDataFrame.scala)
> 	at org.neo4j.spark.Neo4JavaSparkContext.queryDF(Neo4JavaSparkContext.java:55)
> 	at com.etl.sparkneo.testIntegration.main(testIntegration.java:36)
> for java  code as follows :- 
>   SparkConf sparkConf = new SparkConf().setAppName("spark etl").set("spark.neo4j.bolt.url", "bolt://localhost:7687").set("spark.neo4j.bolt.user", "neo4j").set("spark.neo4j.bolt.password", "123456");
>         //SparkContext sc = new SparkContext(sparkConf);
>         SparkSession session = SparkSession.builder().config(sparkConf)
>                 .master("local[2]")
>                 .getOrCreate();
>    JavaRDD<Row> data = v.queryDF("MATCH (m:player) RETURN m.YOB, m.name,m.POB ", null).toJavaRDD();
> when using neo4j-java-driver version 4.0.1 : 
> Exception in thread "main" org.neo4j.driver.exceptions.FatalDiscoveryException: Database does not exist. Database name: "123456"
> 
> 	at org.neo4j.driver.internal.util.Futures.blockingGet(Futures.java:143)
> 	at org.neo4j.driver.internal.InternalResult.blockingGet(InternalResult.java:128)
> 	at org.neo4j.driver.internal.InternalResult.hasNext(InternalResult.java:64)
> 	at org.neo4j.spark.dataframe.Neo4jDataFrame$$anon$2.execute(Neo4jDataFrame.scala:127)
> 	at org.neo4j.spark.dataframe.Neo4jDataFrame$$anon$2.execute(Neo4jDataFrame.scala:124)
> 	at org.neo4j.driver.internal.InternalSession.lambda$transaction$4(InternalSession.java:150)
> 	at org.neo4j.driver.internal.InternalSession$$Lambda$11/1479809423.get(Unknown Source)
> 	at org.neo4j.driver.internal.retry.ExponentialBackoffRetryLogic.retry(ExponentialBackoffRetryLogic.java:101)
> 	at org.neo4j.driver.internal.InternalSession.transaction(InternalSession.java:146)
> 	at org.neo4j.driver.internal.InternalSession.readTransaction(InternalSession.java:112)
> 	at org.neo4j.driver.internal.InternalSession.readTransaction(InternalSession.java:106)
> 	at org.neo4j.spark.dataframe.Neo4jDataFrame$.apply(Neo4jDataFrame.scala:133)
> 	at org.neo4j.spark.dataframe.Neo4jDataFrame.apply(Neo4jDataFrame.scala)
> 	at org.neo4j.spark.Neo4JavaSparkContext.queryDF(Neo4JavaSparkContext.java:55)
> 	at com.etl.sparkneo.testIntegration.main(testIntegration.java:36)
> ```
> 
> here is maven pom.xml file
> 
> ```
>  <dependencies>
>         
>         <dependency>
>             <groupId>org.neo4j.driver</groupId>
>             <artifactId>neo4j-java-driver</artifactId>
>             <version>4.0.1</version>
>         </dependency>
>         <dependency>
>             <groupId>org.apache.spark</groupId>
>             <artifactId>spark-core_2.11</artifactId>
>             <version>2.4.5</version>
>         </dependency>
>         <dependency>
>             <groupId>org.apache.spark</groupId>
>             <artifactId>spark-sql_2.11</artifactId>
>             <version>2.4.5</version>
>         </dependency>
>         
>         <dependency>
>             <groupId>neo4j-contrib</groupId>
>             <artifactId>neo4j-spark-connector</artifactId>
>             <version>2.4.5-M1</version>
>         </dependency>
>    
>     </dependencies>
>     <repositories>
>         <repository>
>             <id>spark-repo</id>
>             <url>http://dl.bintray.com/spark-packages/maven/</url>
>         </repository>
>     </repositories>
> ```

@waelAbass 
can you try with the following snippet?
```scala
SparkConf sparkConf = new SparkConf().setAppName("spark etl")
  .set("spark.neo4j.url", "bolt://localhost:7687")
  .set("spark.neo4j.user", "neo4j")
  .set("spark.neo4j.password", "123456");
        //SparkContext sc = new SparkContext(sparkConf);
        SparkSession session = SparkSession.builder().config(sparkConf)
                .master("local[2]")
                .getOrCreate();
```

removing the `bolt` in the config

**Comment by waelAbass** [comment]
@conker84
thanks  , it works now
