### ISSUE TITLE
Write to Neo4J with More Flexibility

### ISSUE THREAD

**Issue by adamrabie** [neo4j-contrib/neo4j-spark-connector#17]
I'm curious if the saveGraph method can allow for more flexible ways of writing to Neo4J. For example, instead of updating a node property with the latest page rank, I'd like to append the latest page rank to an array property of a node e.g. rank: [{timestamp}:{pagerank}]. Any idea how this can be done?

I have little experience with scala or spark and not sure how to manipulate the 'g' data variable or how what options are available for the saveGraph method. Any help or thoughts are very much appreciated.

**Comment by jexp** [comment]
Yes, I'd be more than happy to.

Any suggestions for a good API? I'm collecting feedback for a more builder pattern.

We can generalize the save methods to take an arbitrary Cypher statement which then can consume the given, named RDDs or DataFrames in batches.

**Comment by adamrabie** [comment]
@jexp Yeah, I think the API should mimic working with Cypher as much as possible. 

If we can pass data in to a Cypher statement then execute that statement, this is ideal. I'd also really appreciate some examples of using spark data in a Cypher context. I'm still trying to figure out how to play with the data.

**Comment by jexp** [comment]
@adamrabie I finished the loading API over the weekend and would love your feedback. 
Writing would be next.

See: https://github.com/neo4j-contrib/neo4j-spark-connector#builder-api

**Comment by conker84** [comment]
I'm closing this because it's more than 1yr old feel free to reopen in case the issue is not solved
