### ISSUE TITLE
Type validation / Neo4j/Spark Type Reference

### ISSUE THREAD

**Issue by moxious** [neo4j-contrib/neo4j-spark-connector#176]
This ticket is just to log the fact that we need to double check full type consistency between 4.1, 4.2 and spark.   Most types we know are already handed in some reasonable way, and in some cases, "String" is going to be the best that we can do.

But we need to add to the docs a "type mapping reference" that shows how each possible type in Neo4j turns into the equivalent in spark.

**Comment by conker84** [comment]
@moxious with #191 we have cross-testing over version `3.5`, `4.0` and `4.1`. Do we need to do something else?

**Comment by moxious** [comment]
Original scope of what I intended for this ticket is basically done so I'm closing it.  If we find any more gaps we can take them up as separate, narrowly scoped improvements.
