### ISSUE TITLE
Missing node key field results in unexplained error on relationship writes

### ISSUE THREAD

**Issue by moxious** [neo4j-contrib/neo4j-spark-connector#178]
Look at the code carefully:  notice that "name:author" is correct but reversed, it should be "author:name".

<img width="895" alt="Screen Shot 2020-09-09 at 9 52 54 AM" src="https://user-images.githubusercontent.com/5471710/92607588-4ecdc580-f282-11ea-8a29-c6dff3f09223.png">

This is a user error, but the error makes no sense.  Managed to replicate a bug post-merge that we were looking into the other day.   We need a check before writes begin that any fields mentioned/implicated in the keys for source/target must exist.  This dataframe didn't even have a "name" field so before opening any connection, this error should be detectable/reportable.

**Comment by moxious** [comment]
I'm finding that the feature does work correctly in more testing -- but that this particular bug makes it hard to test.  It's very easy to make a small mistake in node key mappings and have it fail with no explanation.

**Comment by conker84** [comment]
closed via dba1d61
