### ISSUE TITLE
Update graphframes package version in README.md

### ISSUE THREAD

**Issue by Lax100** [neo4j-contrib/neo4j-spark-connector#18]
The graphframes package version listed under the Neo4jGraphFrame section of the readme should be changed from

$SPARK_HOME/bin/spark-shell --conf spark.neo4j.bolt.password= \ --packages neo4j-contrib:neo4j-spark-connector:2.0.0-M1,graphframes:graphframes:0.2.0-spark2.0_2.11

to

$SPARK_HOME/bin/spark-shell --conf spark.neo4j.bolt.password= \ --packages neo4j-contrib:neo4j-spark-connector:2.0.0-M1,graphframes:graphframes:0.2.0-**spark2.0-s_2.11**

**Comment by jexp** [comment]
Fixed, thanks
