### ISSUE TITLE
Inner CALL { block } breaks certain cypher patterns when reading via custom query

### ISSUE THREAD

**Issue by moxious** [neo4j-contrib/neo4j-spark-connector#180]
See screenshot:

<img width="1606" alt="Screen Shot 2020-09-10 at 12 33 44 PM" src="https://user-images.githubusercontent.com/5471710/92763916-f40b9b00-f361-11ea-9056-e10e8116fc69.png">

**Comment by moxious** [comment]
This appears to be related to the wrong assumption inside of struct() which is trying to read the schema of the return type ahead of time.  There are perhaps queries like these where we need to make the user provide ahead of time the columns that are coming back so that the connector doesn't have to infer them.

**Comment by moxious** [comment]
OK, so maybe the essence here is that without being able to inspect metadata from a call before you run it, you can't know what the resulting dataframe will have.   There should possibly be two behaviors here.

- Option 1: if the user specifies nothing and you can't know what's coming back, then you can always return one column called "value" with a map of key/values for individual records.
- Option 2: user can provide a list of columns that will come back, and connector can guarantee those in string format

Separately -- it's a little uncomfortable to pre-execute a query in order to fetch metadata.  Some queries may take a very long time to execute, and others may not be "pure read queries" ... i.e. if they have side effects, you don't want to execute them (even in part) twice.

**Comment by moxious** [comment]
Extra thought -- I think that the `CALL { foo }` syntax isn't even going to work on 3.5, and so it will fail every time.

**Comment by moxious** [comment]
Discussion:

* Add option to allow user to explicitly specify column order that will come back from a query
* If that option is present, don't use metadata detection -- use what the user said.
* If this option is MISSING, and database is 3.5, or metadata detection fails in any way, or user is using a procedure, then you can fail with the error "Can't do automatic metadata detection, you must specify "output.columns" (or whatever the option is)

**Comment by conker84** [comment]
closed via f96c4b2
