### ISSUE TITLE
Flag user and fail fast if the combined option set doesn't make sense

### ISSUE THREAD

**Issue by moxious** [neo4j-contrib/neo4j-spark-connector#181]
Here, I provide relationship metadata options but I'm reading a label

<img width="521" alt="Screen Shot 2020-09-10 at 2 42 45 PM" src="https://user-images.githubusercontent.com/5471710/92783590-e8c16b00-f373-11ea-88c8-53f517ba7f2d.png">

**Comment by conker84** [comment]
Closed via 27a7050b82057cb6071eee5ba8f89bad0e69b0aa, we opted to just warn the user
