### ISSUE TITLE
Swallowed Exception (probably deadlock) on writing relationships

### ISSUE THREAD

**Issue by moxious** [neo4j-contrib/neo4j-spark-connector#183]
See screenshot.   I am intentionally writing a big relationship set with 6 partitions.  I *expect* it to fail, probably with deadlock exceptions because this particular relationship `(:Event)-[:THEME]->(:Theme)` has 1 million events and only 5 thousand themes, so each theme has a lot of relationships.

The problem is that this does fail, you just can't tell how.   Recommend we check for high-concurrency writes that are going to cause problems, and make sure that the deadlock or other exceptions get surfaced to the users so they have a chance to discover what's wrong.  I think this is potentially a common problem.

<img width="1240" alt="Screen Shot 2020-09-11 at 10 46 06 AM" src="https://user-images.githubusercontent.com/5471710/92939696-1530c200-f41c-11ea-9284-cbdbca145fd9.png">

**Comment by moxious** [comment]
For reference, the python source of write_rel_batch is this:
```

def write_rel_batch(df, source_labels, source_keys, rel_type, target_labels, target_keys, batch_size=20000, mode='Overwrite', parallelism=1):
  return df.repartition(parallelism).write.format("org.neo4j.spark.DataSource") \
      .option("url", dbutils.widgets.get("url")) \
      .option("authentication.basic.username", dbutils.widgets.get("user")) \
      .option("authentication.basic.password", dbutils.widgets.get("password")) \
      .option("relationship", rel_type) \
      .option("relationship.save.strategy", "keys") \
      .option("relationship.source.labels", source_labels) \
      .option("relationship.source.save.mode", mode) \
      .option("relationship.target.labels", target_labels) \
      .option("relationship.target.save.mode", mode) \
      .option("relationship.source.node.keys", source_keys) \
      .option("relationship.target.node.keys", target_keys) \
      .save()
```

**Comment by utnaf** [comment]
@moxious A few things on this

- there is a `transaction.retries` option that I obviously forgot to add to the docs, you might want to try to improve that. Now is documented [here](http://5.9.211.195:8000/neo4j-spark-docs/1.0.0/writing.html#_options) btw
- we might want to add a `transaction.retries.delay` option to specify a delay between retries

**Comment by moxious** [comment]
those are both good points -- thanks for adding to the docs.  Maybe open a separate ticket to pick up the `transaction.retries.delay` issue.   Still -- failures will happen, and we need to make sure to surface why the underlying failure happened, otherwise people will be quite frustrated
