### ISSUE TITLE
error with mvn clean install assembly:single

### ISSUE THREAD

**Issue by raviranjan-innoplexus** [neo4j-contrib/neo4j-spark-connector#19]
Hi,
I am trying neo4j spark connector but am stuck at mvn clean install assembly:single step. It throws an error. 
Tests in error: 
  runMatrixQueryDFSchema(org.neo4j.spark.Neo4jDataFrameTest): Job aborted due to stage failure: Task 0 in stage 3.0 failed 1 times, most recent failure: Lost task 0.0 in stage 3.0 (TID 12, localhost): java.util.NoSuchElementException: None.get

Tests run: 7, Failures: 0, Errors: 1, Skipped: 1

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 33.448s
[INFO] Finished at: Wed Aug 24 14:14:10 IST 2016
[INFO] Final Memory: 65M/633M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.10:test (default-test) on project neo4j-spark-connector: There are test failures.
[ERROR] 
[ERROR] Please refer to /data/neo4j-spark-connector/target/surefire-reports for the individual test results.

**Comment by anuragknoldus** [comment]
Hi,
This issue has been resolved. Please update your branch with latest code.

**Comment by raviranjan-innoplexus** [comment]
Thanks a lot Anurag. I checked and it is working now.
