### ISSUE TITLE
Reading empty query sets fails due to schema inference

### ISSUE THREAD

**Issue by moxious** [neo4j-contrib/neo4j-spark-connector#200]
See screenshot.

Probably we're trying to sample the result and that's failing, because there are no results.

<img width="1051" alt="Screen Shot 2020-09-28 at 8 16 31 AM" src="https://user-images.githubusercontent.com/5471710/94431183-f1cb7e00-0162-11eb-9ee3-b46367848ebc.png">

**Comment by moxious** [comment]
* Problem is that there's no table to take the schema from because the query is empty
* use Explain plan to get the proper column names & types, and then return empty set.
* Warning - take into account void return types as in explain create index foo_bar for (f:Foo) ON (f.bar)

**Comment by utnaf** [comment]
> Warning - take into account void return types as in explain create index foo_bar for (f:Foo) ON (f.bar)

is this a real scenario? shouldn't the index creation be a write query?

**Comment by moxious** [comment]
@utnaf I don't mean specifically index creation as a read query (yes that should be a write) but there are many situations where a stored proc will be called and return nothing.  For example:

```
CALL myJsonPost('foo.com/bar', {x: 1})
```

This could be a pure read to the database (because it has some external side-effect) and it could also be a VOID procedure which returns nothing.

**Comment by moxious** [comment]
Actions:

* Davide to write up what the issue with the java driver is so I can ask the right people to follow up on the EXPLAIN outputs within java driver.
* What to do if the answer isn't computable at all?


Maybe:

```
.option("output.schema", "x:String,y:String,z:String")
```

If schema isn't computable, fail fast and say "For this query, you must specify output.schema"
