### ISSUE TITLE
Can't use stored procedures within Custom queries

### ISSUE THREAD

**Issue by moxious** [neo4j-contrib/neo4j-spark-connector#201]
See screenshot.

<img width="1050" alt="Screen Shot 2020-09-28 at 8 21 17 AM" src="https://user-images.githubusercontent.com/5471710/94431690-9d74ce00-0163-11eb-9667-be1fd6d367d3.png">

This is a 3.5 cluster, not 4.0.   I suspect it's related to metadata inspection but I don't know.

**Comment by moxious** [comment]
I also think this closed issue is related, but chose to open a new one rather than re-open this old one.

https://github.com/neo4j-contrib/neo4j-spark-connector/issues/180

The connector I'm using is the latest build as of this comment from the 4.0 branch, so I think I've got that fix in.

**Comment by utnaf** [comment]
@moxious I just realized we missed an important step in the docs: read query *must* always return something. So, if you write the query like:

`.option("query", "CALL apoc.meta.nodeTypeProperties() YIELD nodeType RETURN nodeType")`

it should work. Let me know, I add the missing documentation in the meantime

**Comment by moxious** [comment]
@utnaf verified that RETURN works on my side, and I saw the right mention in the documentation too, so I'm closing this as addressed.  Thanks.
