### ISSUE TITLE
Enable the "script" option for read access, not only write.

### ISSUE THREAD

**Issue by moxious** [neo4j-contrib/neo4j-spark-connector#209]
We have a "script" option, but it appears only accessible for writes, which require a dataframe.  I'd like them for reads too.  The key use case here is GDS -- where what the "script" would do is basically create a virtual graph and run an analysis, while the actual read query would return the analysis.   There's no writing that's going on with that, and if "script" is available write-only, then it means I'd have to invent a useless dataframe in order to use GDS.

<img width="914" alt="Screen Shot 2020-10-01 at 6 56 11 AM" src="https://user-images.githubusercontent.com/5471710/94800912-482efb80-03b3-11eb-9c88-80c67f2b58f5.png">

**Comment by conker84** [comment]
If we do this every partition will get the same dataset, is it fine with your use-case?

**Comment by moxious** [comment]
@conker84 no - not OK.  Or rather, needs to be in a single partition.  Imagine these use cases:

1. Use script to set up a GDS analysis
2. Read results by running/streaming GDS analysis back

In most cases where I'd want to use scripts, it's intended to be a sequential set of activities like a script, so it has to happen only once.   Can we force partition 1 a script?  It would be quite bad if you launched 4 expensive GDS analysis operations instead of 1.  Guaranteed OOM

**Comment by conker84** [comment]
O no, what I mean is that the script will be executed just once into the driver program but every partition will have the same value of `scriptResult`

**Comment by moxious** [comment]
yes this would be ok

**Comment by moxious** [comment]
Confirmed with the latest pre-release 2.0 that this works.   Sample confirmation:

```
%spark

spark.read.format("org.neo4j.spark.DataSource").option("url", "bolt://neo4j:7687")
    .option("authentication.type", "basic")
    .option("authentication.basic.username", "neo4j")
    .option("authentication.basic.password", "zeppelin")
    .option("script", "WITH range(0, 100) as params RETURN params")
    .option("query", "UNWIND $scriptResult as map UNWIND map.params as param RETURN param").load().show()
```
