### ISSUE TITLE
Write queries now require RETURN clause due to recent change

### ISSUE THREAD

**Issue by moxious** [neo4j-contrib/neo4j-spark-connector#210]
Can we avoid this / remove this restriction?  Due to a recent change in the way metadata from a result set gets harvested, if you don't have a RETURN statement in a write query, it fails with the error "Please provide a valid WRITE query".   Problem is, we don't get the results back from those batch cypher operations, so the RETURN clause isn't relevant.

Also, it broke a bunch of my sink statements when I was just doing MATCH / CREATE, etc.

**Comment by moxious** [comment]
Example: https://dbc-74dda7d2-ba72.cloud.databricks.com/#notebook/18/command/60

**Comment by conker84** [comment]
@moxious I tried with the last pre-release by creating the following tests case:
```scala
@Test
  def `custom write query should not require return`(): Unit = {
    val query =
      """
        |MERGE (t:Theme { name: event.themeName })
        |WITH t, event
        |MATCH (e:Event { id: event.eventName })
        |CREATE (e)-[:THEME { weight: event.weight }]->(t)""".stripMargin
    val triple = ("myTheme", "myEvent", 10)
    SparkConnectorScalaSuiteIT.session().run(
      s"""CREATE (:Event{id: '${triple._2}'})
         |""".stripMargin)
      .consume()
    val ds = Seq(triple)
      .toDF("themeName", "eventName", "weight")
    ds.write
      .format(classOf[DataSource].getName)
      .option("url", SparkConnectorScalaSuiteIT.server.getBoltUrl)
      .option("query", query)
      .save()
    val count = SparkConnectorScalaSuiteIT.session().run(
      s"""MATCH p = (:Event{id: '${triple._2}'})-[:THEME{weight: ${triple._3}}]->(:Theme{name: '${triple._1}'})
        |RETURN count(p) AS count
        |""".stripMargin)
      .single()
      .get("count")
      .asLong()
    assertEquals(1, count)
  }
```
and it worked can you please try with the `pre2` jar and confirm?

**Comment by moxious** [comment]
verified this isn't present in pre-release 2.    I must have been using old code sorry
