### ISSUE TITLE
Submit parameters to read queries

### ISSUE THREAD

**Issue by moxious** [neo4j-contrib/neo4j-spark-connector#214]
We need a method of piping parameters in for read queries.  Imagine a stored procedure called foo(), and needing to call it on the ID of every node of a certain label.   What a user is trying to accomplish is this:

`MATCH (n:Person) RETURN id(n) as id;`

And then bind all of those to read the results of:
`CALL foo($event.id)`

Not sure if we can do this yet but it'll be needed.

**Comment by moxious** [comment]
Presents with the need to read in parallel from stored procedure calls on a set of inputs, presumably because there are a lot of them.

Spark DataSource API is very limiting here - options can only be strings, so presumably if we wanted to pass params it would be as a JSON array or something like that.  But this might conflict with parallel reads

**Comment by moxious** [comment]
Partitioning of input parameters is an issue.  I have one use case where user wants to submit an array of up to a million different IDs, and wants to called a stored procedure on each of the IDs, but wants *that* to run in parallel.  Meaning that if we were to pass input parameters, they would have to be partitioned according to the separate reads.

**Comment by moxious** [comment]
Current thinking is that this is a terrible idea with current API.   Scala UDFs might be better.

**Comment by conker84** [comment]
what if with allow to do something like this?
```
ss.read.format(classOf[DataSource].getName)
      .option("url", SparkConnectorScalaSuiteIT.server.getBoltUrl)
      .option("parition.manual", true) // we need to find a better name :D
      .option("query", """
		MATCH (n:MyLabel)
		WITH id(n) AS id
		SKIP $skip
		LIMIT $limit
		CALL myproc(id) YIELD myNewId
		RETURN id, myNewId
      """.stripMargin)
      .option("partitions", 4)
      .option("query.count", "MATCH (n:MyLabel) RETURN count(n) AS count")
```
Allowing the user to put skip/limit properties where they want and then we can use them

**Comment by moxious** [comment]
Blocked by the need for more customer input & approach validation

**Comment by moxious** [comment]
March 12 update -- we probably won't implement this because Spark UDFs permit the use of the same computation - adding a column to a an existing dataframe.

We do need better documentation / examples on how to use Spark UDFs, but we have the existing example in @utnaf 's sample repository
