### ISSUE TITLE
"Scala - Basic Reading" example in the notebooks repo does not state how to get movies data

### ISSUE THREAD

**Issue by moxious** [neo4j-contrib/neo4j-spark-connector#228]
In the tutorial example, it loads a set of movies and does some simple query filtering off of that.  New users who clone the repo are guaranteed to fail at this example though because the repo doesn't identify how to get the data (movie database) into the sample database.   We should include a link so the basic read example doesn't break out of the box.

**Comment by utnaf** [comment]
Expanding the second block
<img width="796" alt="Screenshot 2020-10-16 at 14 07 43" src="https://user-images.githubusercontent.com/1318539/96256446-fb554280-0fb8-11eb-98ed-dc4d2b53979d.png">

reveal the cypher code
<img width="729" alt="Screenshot 2020-10-16 at 14 08 19" src="https://user-images.githubusercontent.com/1318539/96256490-1031d600-0fb9-11eb-8b48-7c009098d41f.png">


Agree it should be more visible, I though it would be easier to see... I will leave it expanded

**Comment by utnaf** [comment]
@moxious should be ok now
