### ISSUE TITLE
Using neo4j-spark-connector with Spark 3

### ISSUE THREAD

**Issue by sinamoeini** [neo4j-contrib/neo4j-spark-connector#230]
Hi Team,

I tried using this connector on Spark 3. Although I was not getting a connection error, every query I ran would result in an empty RDD. Then I found out the issue might be due to the fact that Spark 3 [is not supported yet](https://docs.databricks.com/data/data-sources/neo4j.html)? 

Is this the case and if so is there a road map for when it will become available? 

Thanks,
Sina

**Comment by conker84** [comment]
Hi @sinamoeini you can find the answer to your question here: #206 

I'm closing this.
