### ISSUE TITLE
Add 4.0 to spark packages

### ISSUE THREAD

**Issue by moxious** [neo4j-contrib/neo4j-spark-connector#235]
Ref this old ticket where it was done for the previous version: https://github.com/neo4j-contrib/neo4j-spark-connector/issues/1

**Comment by moxious** [comment]
published here: https://spark-packages.org/package/neo4j-contrib/neo4j-connector-apache-spark_2.11

and here: https://spark-packages.org/package/neo4j-contrib/neo4j-connector-apache-spark_2.12

**Comment by moxious** [comment]
solved for now; @conker84 investigating whether this can be done via maven central publishing

**Comment by conker84** [comment]
Done
