### ISSUE TITLE
Handle options consistency issues

### ISSUE THREAD

**Issue by utnaf** [neo4j-contrib/neo4j-spark-connector#239]
Throw error if none of `labels` `query` or `relationship` is set.

Log a warning for other kind of inconsistent options.

**Comment by utnaf** [comment]
@moxious, while I was working on this I though of this scenario:

```scala
df.read.format("neo4j")
  .option("labels", "Person")
  .option("relationship", "KNOWS")
  .option("query", "MATCH (n) RETURN id(n) AS id")
  .load()
```

What should we do in this case? Talked with @conker84 and we both think the connector should throw an Exception and stop the execution. What do you think?

**Comment by moxious** [comment]
I agree.  There are mutually exclusive options - don't try to be smart and do them in a certain order.  Tell the user that they gave us nonsense.  

Maybe we need to add to the docs too that these are sort of "mode" options, and that you *must* specify 1, and may *only* specify 1.
