### ISSUE TITLE
Release Actions

### ISSUE THREAD

**Issue by moxious** [neo4j-contrib/neo4j-spark-connector#244]
November 10th only

- Andrea:  make GitHub release
- Tag repo with version number
- Update release notes

- David: package for website

**Comment by moxious** [comment]
Andrea - Ensure package is live on spark packages

**Comment by moxious** [comment]
Carry forward tickets 4.0 -> 4.1 project and close 4.0 project

**Comment by moxious** [comment]
All release actions complete, except the spark packages bit.   Any update there @conker84 ?   Otherwise we can close this ticket and work spark packages separately

**Comment by conker84** [comment]
I'm closing this as we have #235
