### ISSUE TITLE
Unable get neo4j spark connector 4.x from Maven

### ISSUE THREAD

**Issue by samminen** [neo4j-contrib/neo4j-spark-connector#246]
Hello Team,
    I have installed Neo4j instance of version 4.0.8 community and I am using neo4j-spark-connector version 2.2.1-M5 (neo4j-spark-connector-2.2.1-M5.jar) because this is the version work with my spark version.

When I try to connect to Neo4J to query data, I am getting below error:

 org.neo4j.driver.v1.exceptions.ClientException: The server does not support any of the protocol versions supported by this driver. Ensure that you are using driver and server versions that are compatible with one another.

In Maven repo, I see the latest version of neo4j-connector as 2.4.5-M2 and I cannot find 4.0.0. 
https://mvnrepository.com/artifact/neo4j-contrib/neo4j-spark-connector

I tried adding maven dependency in my pom.xml as shown here https://github.com/neo4j-contrib/neo4j-spark-connector,  since it is not available in maven, it cannot download JAR.

Any help ?

**Comment by conker84** [comment]
Hi @samminen we plan to add the new `4.0` connector to Maven and Spark packages in the next few days, btw in the meanwhile you can use the pre-release by adding it to your local maven repository as explained here:

https://maven.apache.org/guides/mini/guide-3rd-party-jars-local.html

**Comment by conker84** [comment]
@samminen we did the official release, following a simple guide that allows you to import the new Spark Connector via maven:

https://github.com/neo4j-contrib/neo4j-spark-connector/blob/4.0/doc/docs/modules/ROOT/pages/quick-java-example.adoc

Cheers
Andrea

**Comment by conker84** [comment]
I'm closing this feel free to reopen in case you got any issue with importing the connector in your project
