### ISSUE TITLE
Builder API: Loading DataFrame containing more than just IDs

### ISSUE THREAD

**Issue by sjishan** [neo4j-contrib/neo4j-spark-connector#25]
Hi I would like to if it is possible to create DataFrame that will provide results just the way it does in Neo4j when I will do the query. 

For example (screenshot below) I would like to get 3 columns as return for this particular query 

`match (u2)-[e]-(u1) where e.timestamp > 1471651200 return u2,e,u1`

![image](https://cloud.githubusercontent.com/assets/5510397/18690493/35aab39e-7f43-11e6-839e-40e5d4612128.png)

However in spark it only is returning the IDs and the number of IDs is restricted to partition * batch size. So if parition size is 10 and batch size is 30 then we will only get 300 rows in return. But I think it will be great if it is possible to get all of them which matches the condition.

![image](https://cloud.githubusercontent.com/assets/5510397/18691166/0e809af0-7f47-11e6-8f15-1ecf8405b571.png)

**Comment by jexp** [comment]
Sure there is a loadDataFrame method that takes a schema:

```
scala> import org.neo4j.spark._
import org.neo4j.spark._

scala> val neo = Neo4j(sc)
neo: org.neo4j.spark.Neo4j = org.neo4j.spark.Neo4j@750cd36d

scala> val df = neo.cypher("match (n) return id(n) as id1, id(n) as id2").partitions(4).batch(100).loadDataFrame(("id1"->"int"),("id2"->"int"))
df: org.apache.spark.sql.DataFrame = [id1: bigint, id2: bigint]

scala> df.take(3)
res2: Array[org.apache.spark.sql.Row] = Array([0,0], [1,1], [2,2])

```

**Comment by jexp** [comment]
But it also work with just the query (it inspects the result metadata then)

```
val df = neo.cypher("match (n) return id(n) as id1, id(n) as id2").partitions(4).batch(100).loadDataFrame
df: org.apache.spark.sql.DataFrame = [id1: bigint, id2: bigint]
```

**Comment by sjishan** [comment]
Thanks. Solved.

**Comment by asarraf** [comment]
@jexp

scala> val df = neo.cypher("match (n:Emp) return id(n) as id, n.name as name, n.dept as dept").loadDataFrame(("id"->"long"),("name"->"string"),("dept"->"long"))
df: org.apache.spark.sql.DataFrame = [id: bigint, name: string ... 1 more field]

scala> df.count()
res15: Long = 28 // When I have only 7 nodes in my Graph. Any specific reason for this repetitions?

**Comment by jexp** [comment]
@asarraf What happens if you run the same query as Cypher in Neo4j?
