### ISSUE TITLE
Spark Connector - Saving Data Back to Neo4j

### ISSUE THREAD

**Issue by vishwasjione** [neo4j-contrib/neo4j-spark-connector#250]
Hi,
Can I save Spark Dataframe back to neo4j ?

df.printSchema()
root
 |-- City: string (nullable = true)
 |-- zip: integer (nullable = true)

 df.write
     .format("????????????????")
    .option("url", "bolt://localhost:7687")
    .option("query", "CREATE (n:City {Name: event.City})")
    .save()

I am not sure what value I should give to format option here.
I am using Spark neo4j connector 2.4.5-M1 and I am on Spark 2.4.x

Thank you so much
VG

**Comment by conker84** [comment]
Hi @vishwasjione and thanks for reaching us,
you should move to the Neo4j spark connector v `4.0`:

https://neo4j.com/developer/spark/

**Comment by vishwasjione** [comment]
Thanks @conker84  
Good Morning , Could you please provide maven repository details for this latest driver so that I can use it .

Thanks

**Comment by conker84** [comment]
@vishwasjione you can look here:
https://github.com/neo4j-contrib/neo4j-spark-connector/blob/4.0/doc/docs/modules/ROOT/pages/quick-java-example.adoc

**Comment by conker84** [comment]
I'm closing this since you seem able to import the library (see #252)
