### ISSUE TITLE
"Ignore" is not supported in this 4.0 release ?? 

### ISSUE THREAD

**Issue by vishwasjione** [neo4j-contrib/neo4j-spark-connector#252]
It is a part of the JAR but when we use it in the code while saving dataframe, it errors out.

Exception in thread "main" java.lang.IllegalArgumentException: Unsupported SaveMode.
You provided Ignore, supported are:
Overwrite,ErrorIfExists,Append

Thanks

**Comment by conker84** [comment]
No please read the documentation::
https://neo4j.com/developer/spark/writing/#bookmark-save-mode
