### ISSUE TITLE
AWS Glue error when I use connector 4.0 version

### ISSUE THREAD

**Issue by vishwasjione** [neo4j-contrib/neo4j-spark-connector#253]
Hi,

    someDF.write
      .format(classOf[org.neo4j.spark.DataSource].getName)
      .option("url", "bolt://XXXXXXXXXX")
      .option("authentication.type", "basic")
      .option("authentication.basic.username", "neo4j")
      .option("authentication.basic.password", "###")
      .option("batch.size", 5000)
      .mode(SaveMode.Overwrite)
      .option("node.keys", "number,word")
      .option("labels", ":MyNode")
      .save()

I get following error - 

java.lang.NoSuchMethodError : org.neo4j.driver.Config$ConfigBuilder.withUserAgent(Ljava/lang/String;)Lorg/neo4j/driver/Config$ConfigBuilder;
--
Kindly help.

Thanks

**Comment by conker84** [comment]
Hi @vishwasjione following a couple of questions:

* Can you share the full stack trace?
* What spark (and scala) version are you using?
* How did you install the plugin?

**Comment by vishwasjione** [comment]
Hi @conker84 
GM . .thanks for response

1.  Using Neo4j 4.0.4 & Scala 2.11.1 & Spark 2.4.4
2.  Downloaded mvn thing http://dl.bintray.com/spark-packages/maven/neo4j-contrib/neo4j-connector-apache-spark_2.11/ 

will provide more updates later in the day

Thanks
Vishwas

**Comment by conker84** [comment]
Closing for lack of feedback. Feel free to open in case of new info
