### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by adamrabie** [neo4j-contrib/neo4j-spark-connector#26]
@jexp 

I'm hoping we can get some more clear examples on how to load the graph with a cypher query. 

Assuming I want to run pagerank on a graph of something like...

`(:Label)-[:Type1|:Type2]-(n)`

Can you please show how to use loadGraph in a way that the pagerank will run against?

**Comment by jexp** [comment]
@adamrabie this should work:

```
Neo4j(sc).cypher("MATCH (n1:Label)-[:Type1|:Type2]-(n2) RETURN id(n1) as source, id(n2) as target").loadGraph()
```
