### ISSUE TITLE
 Unable to convert java.sql.Timestamp to Neo4j Value 

### ISSUE THREAD

**Issue by waelAbass** [neo4j-contrib/neo4j-spark-connector#269]
I am using spark 2.4.1 and  neo4j-spark-connector 2.4.5-M1  and I get the following exception :
 Task 162 in stage 32.0 failed 1 times, most recent failure: Lost task 162.0 in stage 32.0 (TID 1020, localhost, executor driver): org.neo4j.driver.exceptions.ClientException: **Unable to convert java.sql.Timestamp to Neo4j Value.**
	at org.neo4j.driver.Values.value(Values.java:134)
in the following line of code   **Neo4jDataFrame.createNodes(session.sparkContext(), data, tuple2, hashMap, 200, 1000, true);**
how to solve this problem ?

**Comment by waelAbass** [comment]
@Andrea Santurbano

**Comment by utnaf** [comment]
Hi @waelAbass! 
The old spark connector is no longer supported. Please try to use the [latest release of Neo4j Connector for Apache Spark](https://github.com/neo4j-contrib/neo4j-spark-connector/releases/tag/v4.0.0).

In the [README](https://github.com/neo4j-contrib/neo4j-spark-connector/blob/v4.0.0/README.md) you can find how to properly add it to your dependancy. 

Let me know if you have any issues. Thank you

**Comment by conker84** [comment]
I'm closing this since is related to the old connector, feel free to reopen it in case you need
