### ISSUE TITLE
is it possible to use neo4j-spark-connector to write a Spark data frame to Neo4j database?

### ISSUE THREAD

**Issue by simonegabbriellini** [neo4j-contrib/neo4j-spark-connector#27]
I am trying to write a Spark data frame to Neo4j database and stumbled upon neo4j-spark-connector... I understand the examples to retrieve data from Neo4j and make further processing into Spark, but is the opposite workflow contemplated by this connector?

**Comment by jexp** [comment]
Hi @simonegabbriellini yes, definitely. 

There are some examples in the older API to support that, I just have to find a bit of time to add it to the new API.

See [Neo4jDataFrame.mergeEdgeList](https://github.com/neo4j-contrib/neo4j-spark-connector/blob/master/src/main/scala/org/neo4j/spark/Neo4jDataFrame.scala#L17) for one example.

**Comment by simonegabbriellini** [comment]
thanks a lot! I have asked on [SO](http://stackoverflow.com/questions/40262546/how-to-write-spark-data-frame-to-neo4j-database/40266196#40266196) but the only reply I got stated the opposite... I'll put this link in the answer so to set the record straight.

**Comment by jexp** [comment]
Thanks a lot.

**Comment by jexp** [comment]
Were you successful with what you wanted to achieve?

Any other feedback what I can improve with the connector? Besides the API for writing and documentation?

**Comment by syarram** [comment]
Hi Jexp, Can you please let us know if we can write to Neo4j using Spark Data Frames or RDD's, or you are working on it?

**Comment by jexp** [comment]
@syarram did you look at the examples in the readme?
Did you try the mergeEdgeList ? https://github.com/neo4j-contrib/neo4j-spark-connector/blob/master/src/main/scala/org/neo4j/spark/Neo4jDataFrame.scala#L17 

The new API should look like this, I just worked on the code for saveGraph the other datastructures come next.

https://github.com/neo4j-contrib/neo4j-spark-connector/blob/master/src/main/scala/org/neo4j/spark/Neo4j.scala#L56

**Comment by ShahNewazKhan** [comment]
hi @jexp do you have any such example in python?

**Comment by GreGGus** [comment]
Looking for example in Scala/Spark :)

**Comment by azdafirmansyah** [comment]
you can use this :
`    val rows = sc.makeRDD(Seq(Row("Keanu Reavee", "Male", "The Matrix")))
    val schema = StructType(
      Seq(
        StructField("name", DataTypes.StringType),
        StructField("gender", DataTypes.StringType),
        StructField("title", DataTypes.StringType)))
    val dfx = new SQLContext(sc).createDataFrame(rows, schema)
    Neo4jDataFrame.mergeEdgeList(
      sc,
      dfx,
      ("Person",Seq("name","gender")),
      ("ACTED_IN",Seq.empty),
      ("Movie",Seq("title")))`

My code working use this

**Comment by lansaloltd** [comment]
@jexp I don't think the mergeEdgeList example can realistically persist a DataFrame/Dataset in Neo4j. Reasons are explained [here](https://lansalo.com/2020/01/09/how-not-to-persist-spark-dataset-dataframe-toneo4j-and-how-to/) in full but if you give it a try with a 1000 rows DataFrame (which should be still manageable locally) you should see that is not a doable solution.

**Comment by shao-shuai** [comment]
I tried to find documentation or tutorial on how to write data generated by Spark to neo4j with neo4j-spark-connector, but haven't found any, anyone can share? thanks!

**Comment by conker84** [comment]
I'm closing this because it's more than 1yr old feel free to reopen in case the issue is not solved
