### ISSUE TITLE
Document better how using procedures in query read can influence the exectuion

### ISSUE THREAD

**Issue by conker84** [neo4j-contrib/neo4j-spark-connector#274]
For a use case like this:

```scala
sparkSession.read.format("org.neo4j.spark.DataSource")
  .option("url", "bolt://localhost:7687")
  .option("authentication.type", "basic")
  .option("authentication.basic.username", "xxxxx")
  .option("authentication.basic.password", "xxxxx")
  .option("query", """
    |match (coach:Customer{id:'1'})
    |call my.custom.procedure('1') yield fieldA, fieldB, fieldC
    |value return fieldA, fieldB, fieldC")
  .load()
  .show()
```

if `my.custom.procedure` has mode `write` it can block the execution of the query.

The connector now return this message:

```bash
Exception in User Class: java.lang.IllegalArgumentException : Please provide a valid READ query
```

We can:
* Document better this behaviour;
* Add a better exception message like `Please provide a valid READ query. Nota bene, if you're using procedures in your query please check that they work in READ mode`

**Comment by fbiville** [comment]
Moved to https://github.com/neo4j/docs-spark/issues/44
