### ISSUE TITLE
ModuleNotFoundError: No module named 'pyspark.functions' error when running Spark Connector Zeppelin Notebook

### ISSUE THREAD

**Issue by ShipatNeo** [neo4j-contrib/neo4j-spark-connector#277]
When running through the Python - Cypher Destructuring Example from https://github.com/utnaf/neo4j-connector-apache-spark-notebooks, on the 3rd notebook entry, the following error is observed:

%pyspark

from pyspark.functions import col

df = spark.read.option("header",True).csv("worldcities.csv")
df.show(5)

# Do a short cleanup step: get rid of null country identifiers.
cleaned_data = df.where(col("iso2").isNotNull())
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-10-525947f3605d> in <module>
----> 1 from pyspark.functions import col
      2 
      3 df = spark.read.option("header",True).csv("worldcities.csv")
      4 df.show(5)
      5 

ModuleNotFoundError: No module named 'pyspark.functions'

**Comment by purushothaman-sridharan** [comment]
from pyspark.sql.functions import col

above works, I'm on Spark 3.0.1!

**Comment by conker84** [comment]
Closing this as not related to the Neo4j Connector
