### ISSUE TITLE
how to set nodeOperation  to "create" in mergeEdgeList method  

### ISSUE THREAD

**Issue by waelAbass** [neo4j-contrib/neo4j-spark-connector#279]
I am using neo4j-spark-connector version 2.4.5-M1 using spark 
the default nodeOperation   in  mergeEdgeList  method is "merge"
please , help to set nodeOperation  to  "create" using spark java  as I did not find any resource to help  me on the internet

**Comment by conker84** [comment]
Hi @waelAbass we don't support version `2.4.5-M1` anymore, please move to the new `4.0`, you can find the documentation of the new connector here:

https://neo4j.com/developer/spark/
