### ISSUE TITLE
When Databricks documentation on their site is complete, add link back from our docs

### ISSUE THREAD

**Issue by conker84** [neo4j-contrib/neo4j-spark-connector#280]
Add step-by-step guide for Databricks cloud

**Comment by utnaf** [comment]
@conker84 can this be considered fixed by #305?

**Comment by moxious** [comment]
We will be driving this documentation onto Databricks site -- together with a PR already merged this should be sufficient.

https://docs.google.com/document/d/1GtZnEkL7Ww64bJ6Ye_3nUnBitYaoJdHgW8G60NtgtdY/edit?usp=sharing
