### ISSUE TITLE
Test against Neo4j 4.3

### ISSUE THREAD

**Issue by conker84** [neo4j-contrib/neo4j-spark-connector#289]
It would be cool having a docker container in:
https://hub.docker.com/r/neo4j/neo4j-experimental

**Comment by conker84** [comment]
@moxious assigned to you so you can get in touch with the eng team and ask for the container

**Comment by moxious** [comment]
@moxious pinged Chris Gioran Feb 12 for experimental docker builds, TBD

**Comment by conker84** [comment]
Done
