### ISSUE TITLE
Take a look at merge relationship documentation -- how best to clarify?

### ISSUE THREAD

**Issue by moxious** [neo4j-contrib/neo4j-spark-connector#297]
Users appear confused about save mode on relationship merges.

Crux of the issue may be that relationship writes have effectively 3 save modes: the rel, the source, and the target.

Need examples, and expansion in the docs on these points.

**Comment by moxious** [comment]
@utnaf to talk to a key user about problem statement to help inform how best to explain these concepts.

**Comment by utnaf** [comment]
We might want to create a quickstart guide that includes the most common scenarios

- I want to read data out of Neo4j with a cypher query
- I want to write a bunch of nodes
- I want to create a bunch of unique relationships between nodes
- I want to write a dataframe with a Cypher query

Also provide examples in all the languages supported by Spark, something like:

<img width="914" alt="Screen Shot 2021-03-05 at 6 51 40 AM" src="https://user-images.githubusercontent.com/1318539/110123504-41247300-7dc1-11eb-8e46-dc90d20cb0e0.png">

Add a "Quick Tips" section with best practice and suggestions to avoid common mistakes.

fyi @conker84 @moxious

**Comment by stumoore** [comment]
Apologies for the wait, but we have done an extensive overhaul of the Spark docs, which now include Python code examples as well as the scala
 https://neo4j.com/docs/spark/current/writing/ which incudes nodes and relationships
 https://neo4j.com/docs/spark/current/reading
Pages on schema optimizations
