### ISSUE TITLE
neo4j 2.x compatibility?

### ISSUE THREAD

**Issue by prseshad** [neo4j-contrib/neo4j-spark-connector#30]
Hi Michael

Thanks @jexp for providing this.  We would love to use it but we are using neo4j 2.3 currently and it will be a while before we can migrate to 3.0 because we have to refactor some of our code.

I was thinking of forking your repo and making it work for 2.3.  Do you think it would be possible?  Any gotchas I should look out for?  Or is there something out there that already works for 2.3 (mazerunner seems like it might work)?  

Our use case is that we just want to be able to run computations on our neo4j data in parallel, we don't intend to run any "classical" graph computations per se such a mazerunner seems designed to do, but our own custom logic.

**Comment by jexp** [comment]
Currently this library uses the bolt-connector to talk to Neo4j, which is not supported in 2.x

For running your graph computations in Neo4j in parallel please check out: https://github.com/neo4j-contrib/neo4j-graph-algorithms which was recently released (although also only for 3.x)

But you could upgrade a copy of your database to 3.1 and run it there, just to see if it works well for you.
