### ISSUE TITLE
Troubleshooting bad ssl handshake errors with Databricks (solution found)

### ISSUE THREAD

**Issue by moxious** [neo4j-contrib/neo4j-spark-connector#300]
This applies only to Aura -- and is recommended as a potential troubleshooting item for the documentation.

Aura may be looking at a KBase article, but since Aura highly encourages clients to use TLS ciphers that include GCM, customers using Java 8 should make sure to use recent versions of Oracle JDK (8u261 or newer) or OpenJDK (8u272 or newer) due to performance issues with AES-GCM: https://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8201633
I believe this is why Databricks disabled GCM as an available algorithm, leading the recent customer issue where they couldn't connect to Aura.

It seems the issue was found and raised by Spark developers working with large encrypted Parquet files, hence why Databricks seems keenly interested in disabling GCM. See http://mail.openjdk.java.net/pipermail/security-dev/2018-November/018745.html and the author's presentation (spefically slide 24) here https://www.slideshare.net/databricks/efficient-spark-analytics-on-encrypted-data-with-gidon-gershinsky (edited)

**Comment by moxious** [comment]
Sample draft work-around, a shell script to be used with instantiating a databricks cluster

```
#!/bin/sh
PROPERTIES_FILE="/databricks/spark/dbconf/java/extra.security"
DISABLED_ALGOS="SSLv3, RC4, DES, MD5withRSA, DH keySize < 1024, EC keySize < 224, 3DES_EDE_CBC, anon, NULL"
echo "Configure Databricks java for Aura access"
if [[ -f "${PROPERTIES_FILE}" ]]; then
    echo "setting jdk.tls.disabledAlgorithms..."
    echo "jdk.tls.disabledAlgorithms=${DISABLED_ALGOS}" | tee "${PROPERTIES_FILE}"
else
    >&2 echo "ERROR failed to find ${PROPERTIES_FILE}"
fi
```

**Comment by moxious** [comment]
thanks to @voutilad who diagnosed and spotted this issue

**Comment by moxious** [comment]
For reference, here are the release notes and versions that the JDK-8201633 issue was resolved:
Oracle:
- Java 8u261: https://www.oracle.com/java/technologies/javase/8u261-bugfixes.html
- Java 11.0.2+31: https://www.oracle.com/java/technologies/javase/11all-relnotes.html

OpenJDK:
- jdk8u272: https://mail.openjdk.java.net/pipermail/jdk8u-dev/2020-October/012817.html
- jdk 11.0.4: https://mail.openjdk.java.net/pipermail/jdk-updates-dev/2019-July/001423.html

Zulu:
- 13.27: https://docs.azul.com/zulu/zulurelnotes-archive/ZuluReleaseNotes/OpenJDK_Fixes_Sept19.htm

**Comment by moxious** [comment]
not sure this is a "good" solution for Databricks at the moment. They clearly had a reason for disallowing GCM. From what I saw in the materials I found, it's a massive performance hit if Java ends up using it for things like Parquet. We're talking multiple orders of magnitude difference in encryption/decryption rates.

TBD:  which cipher suites are a good compromise between security, default functionality, and performance.

**Comment by voutilad** [comment]
Databricks has migrated to using Zulu's Java distribution as of at least their 7.3LTS release. (5.5LTS uses OpenJDK builds.) I've opened a ticket with Azul to see if I can get confirmation on which Zulu versions have the fix for JDK-8201633 incorporated.

Even on the most recent Databricks runtime release, they're using a Java 8 version of Zulu, so it's not clear if JDK-8201633 has been ported yet or not. (Or if it ever will.)

**Comment by voutilad** [comment]
According to a support engineer at Azul Systems:

> JDK-8201633 is fixed in Zulu 11 and Zulu 12 since the October 2019 update (Zulu 11.31 and 12.2), and in Zulu 8 since the July 2020 Update (Zulu 8.48).

This means _potentially_ Databricks 7.3LTS and any newer runtimes might not be impacted if you re-enable support for GCM.

**Comment by voutilad** [comment]
For any future discoverers of this issue, you can check if your Databricks environment can support  connecting securely to Neo4j Aura using the following Scala. Put it in a workbook using a Scala runtime and check the output for at least one of the ciphers having `supported: true`:

```scala
import scala.collection.mutable.ListBuffer
import javax.net.ssl.SSLSocketFactory

var auraCiphers = Set(
    // see https://aura.support.neo4j.com/hc/en-us/articles/360062636473-What-are-the-TLS-cipher-suite-supported-by-Aura-
    // tls v1.3
    "TLS_CHACHA20_POLY1305_SHA256",
    "TLS_AES_128_GCM_SHA256",
    "TLS_AES_256_GCM_SHA384",
    // tls v1.2
    "TLS_DHE_RSA_WITH_AES_128_GCM_SHA256",
    "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
    "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
    "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256",
    "TLS_DHE_RSA_WITH_AES_256_GCM_SHA384")
var factory = SSLSocketFactory.getDefault().asInstanceOf[SSLSocketFactory]
var supportedCiphers = factory.getSupportedCipherSuites()
var defaultCiphers = factory.getDefaultCipherSuites()

var matchingCiphers = new ListBuffer[String]()

for (cipher <- auraCiphers) {
  if (supportedCiphers.contains(cipher)) {
    matchingCiphers += cipher
  }
  println("cipher: " + cipher + ", supported: " + supportedCiphers.contains(cipher) + ", default: " + defaultCiphers.contains(cipher))
}
```

**Comment by utnaf** [comment]
Should we reference this issue in the FAQs section of the Spark Connector? https://neo4j.com/developer/spark/faq/

**Comment by conker84** [comment]
> For any future discoverers of this issue, you can check if your Databricks environment can support connecting securely to Neo4j Aura using the following Scala. Put it in a workbook using a Scala runtime and check the output for at least one of the ciphers having `supported: true`:
> 
> ```scala
> import scala.collection.mutable.ListBuffer
> import javax.net.ssl.SSLSocketFactory
> 
> var auraCiphers = Set(
>     // see https://aura.support.neo4j.com/hc/en-us/articles/360062636473-What-are-the-TLS-cipher-suite-supported-by-Aura-
>     // tls v1.3
>     "TLS_CHACHA20_POLY1305_SHA256",
>     "TLS_AES_128_GCM_SHA256",
>     "TLS_AES_256_GCM_SHA384",
>     // tls v1.2
>     "TLS_DHE_RSA_WITH_AES_128_GCM_SHA256",
>     "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
>     "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
>     "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256",
>     "TLS_DHE_RSA_WITH_AES_256_GCM_SHA384")
> var factory = SSLSocketFactory.getDefault().asInstanceOf[SSLSocketFactory]
> var supportedCiphers = factory.getSupportedCipherSuites()
> var defaultCiphers = factory.getDefaultCipherSuites()
> 
> var matchingCiphers = new ListBuffer[String]()
> 
> for (cipher <- auraCiphers) {
>   if (supportedCiphers.contains(cipher)) {
>     matchingCiphers += cipher
>   }
>   println("cipher: " + cipher + ", supported: " + supportedCiphers.contains(cipher) + ", default: " + defaultCiphers.contains(cipher))
> }
> ```

@utnaf please create a simple Databricks cloud notebook and link it into the documentation so anyone can clone and test the env with just a simple click.

**Comment by moxious** [comment]
Leaving this ticket with the solution, but closing it because we've moved these docs into our main documentation
