### ISSUE TITLE
is it possible to update any empty values like ""  to NULL values in NEO4J while using case statements?

### ISSUE THREAD

**Issue by Dineshkumarmurugan07** [neo4j-contrib/neo4j-spark-connector#310]
I am attaching a query, in this query we need to convert the empty strings as **NULL** values to **concat the strings to form comma-separated strings.**

```
match (d:dpComponent)
call apoc.do.case([
      d.componentId="",'SET d.componentID = null return d',
      d.componentName="",'SET d.componentName = null return d',
     d.componentKey="",'SET d.componentKey = null return d'],
'',{d:d}) 
YIELD value
RETURN 
    value.d.componentID as ID,
    value.d.componentName as Name, 
    value.d.componentKey as Key 
order by ID
```

**Comment by moxious** [comment]
Hi @Dineshkumarmurugan07 can you please identify how this connects to your usage of the spark connector?   If you have a general question about the use of APOC and Cypher, we recommend https://community.neo4j.com/

Our team may not be the best suited to answer questions about how the APOC function work.
