### ISSUE TITLE
Error when writing to neo4j

### ISSUE THREAD

**Issue by samasalam** [neo4j-contrib/neo4j-spark-connector#328]
I'm trying to save the PageRank data back to Neo4j, as the steps in [https://neo4j.com/blog/neo4j-3-0-apache-spark-connector/](url) but an error occured.

My code is as follow:

```
import org.neo4j.spark._ 
import org.apache.spark.graphx._
import org.apache.spark.graphx.lib._
val neo = Neo4j(sc)
val g = Neo4jGraph.loadGraph(sc, label1="node", relTypes=Seq("connect"),  label2="node")
val g2 = PageRank.run(g, numIter = 9)
val v = g2.vertices.take(9)
Neo4jGraph.saveGraph(sc, g2,"rank")
```
**The error:** org.neo4j.driver.exceptions.ClientException: Writing in read access mode not allowed. Attempted write to internal graph 0 (neo4j)

**Note:** everything is run well until the last line of code.

**Comment by samasalam** [comment]
Please anyone can help with the above issue.

**Comment by conker84** [comment]
Hi @samasalam you're using the old version of the spark which is not supported anymore please move to the new Connector:
https://neo4j.com/developer/spark/

**Comment by samasalam** [comment]
I tried this but it doesn't work

`$SPARK_HOME/bin/spark-shell  --conf spark.neo4j.password=sama --packages neo4j-contrib:neo4j-connector-apache-spark_2.12:4.0.1_for_spark_3`

I also download the jar file and tried this but it doesn't work too:

`$SPARK_HOME/bin/spark-shell --conf spark.neo4j.password=sama --jars neo4j-connector-apache-spark_2.12-4.0.1_for_spark_3.jar`

For this line of code:

`val neo = Neo4j(sc)`
error: not found: value Neo4j

**Comment by utnaf** [comment]
@samasalam the whole syntax changed in the new version, please check the documentation https://neo4j.com/developer/spark/

**Comment by samasalam** [comment]
I check it and it is the same as I wrote.  As below, I brought it from the site: 

`$SPARK_HOME/bin/spark-shell --packages neo4j-contrib:neo4j-connector-apache-spark_2.12:4.0.1_for_spark_3`

How should I use the packages and the jar files? where should I put them?  

The only one that work is the following:

`$SPARK_HOME/bin/spark-shell  --packages neo4j-contrib:neo4j-spark-connector:2.4.5-M2`

But the `Neo4jGraph.saveGraph` is not working. The error is : **Writing in read access mode not allowed.**

Thanks for your help.
