### ISSUE TITLE
Error while reading from neo4j into spark

### ISSUE THREAD

**Issue by samasalam** [neo4j-contrib/neo4j-spark-connector#329]
I follow the steps in (https://neo4j.com/developer/spark/quickstart/) and use the following package: 

`$SPARK_HOME/bin/spark-shell --packages neo4j-contrib:neo4j-connector-apache-spark_2.12:4.0.1_for_spark_3
`
Now, in spark shell, when I try to execute this (mentioned in the same site):

```scala
import org.apache.spark.sql.{SaveMode, SparkSession}

val spark = SparkSession.builder().getOrCreate()

val df = spark.read.format("org.neo4j.spark.DataSource")
  .option("url", "bolt://localhost:7687")
  .option("authentication.basic.username", "neo4j")
  .option("authentication.basic.password", "neo4j")
  .option("labels", "Person")
  .load()
```

The following error occur: 
**java.lang.NoClassDefFoundError: org/apache/spark/sql/sources/v2/ReadSupport**

What shall I do to fix the problem?

**Comment by utnaf** [comment]
What's your Spark version?

**Comment by samasalam** [comment]
> What's your Spark version?

spark-3.1.1-bin-hadoop2.7

But I don't know scala version

**Comment by utnaf** [comment]
> > What's your Spark version?
> 
> spark-3.1.1-bin-hadoop2.7
> 
> But I don't know scala version

If you downloaded Spark from here https://spark.apache.org/downloads.html you should have Scala 2.12 (if you want to be sure just run `util.Properties.versionString` from the spark shell), this means that the JAR you are using is correct. 

I tried the same bit of code with the same jar and Spark and everything works for me. Can I ask you to paste the output of this command

`$SPARK_HOME/bin/spark-shell --packages neo4j-contrib:neo4j-connector-apache-spark_2.12:4.0.1_for_spark_3`

**Comment by samasalam** [comment]
> > > What's your Spark version?
> > 
> > 
> > spark-3.1.1-bin-hadoop2.7
> > But I don't know scala version
> 
> If you downloaded Spark from here https://spark.apache.org/downloads.html you should have Scala 2.12 (if you want to be sure just run `util.Properties.versionString` from the spark shell), this means that the JAR you are using is correct.
> 
> I tried the same bit of code with the same jar and Spark and everything works for me. Can I ask you to paste the output of this command
> 
> `$SPARK_HOME/bin/spark-shell --packages neo4j-contrib:neo4j-connector-apache-spark_2.12:4.0.1_for_spark_3`

:: loading settings :: url = jar:file:/C:/Spark/spark-3.1.1-bin-hadoop2.7/jars/ivy-2.4.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
Ivy Default Cache set to: C:\Users\Sama\.ivy2\cache
The jars for the packages stored in: C:\Users\Sama\.ivy2\jars
neo4j-contrib#neo4j-connector-apache-spark_2.12 added as a dependency
:: resolving dependencies :: org.apache.spark#spark-submit-parent-1784c6b8-d2a4-463f-b960-22271e6d52d5;1.0
        confs: [default]
        found neo4j-contrib#neo4j-connector-apache-spark_2.12;4.0.1_for_spark_3 in spark-packages
:: resolution report :: resolve 135ms :: artifacts dl 0ms
        :: modules in use:
        neo4j-contrib#neo4j-connector-apache-spark_2.12;4.0.1_for_spark_3 from spark-packages in [default]
        ---------------------------------------------------------------------
        |                  |            modules            ||   artifacts   |
        |       conf       | number| search|dwnlded|evicted|| number|dwnlded|
        ---------------------------------------------------------------------
        |      default     |   1   |   0   |   0   |   0   ||   1   |   0   |
        ---------------------------------------------------------------------
:: retrieving :: org.apache.spark#spark-submit-parent-1784c6b8-d2a4-463f-b960-22271e6d52d5
        confs: [default]
        0 artifacts copied, 1 already retrieved (0kB/16ms)
21/04/22 20:41:50 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
Spark context Web UI available at http://DESKTOP-KRTACL2:4040
Spark context available as 'sc' (master = local[*], app id = local-1619113315935).
Spark session available as 'spark'.
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /___/ .__/\_,_/_/ /_/\_\   version 3.1.1
      /_/

Using Scala version 2.12.10 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_281)
Type in expressions to have them evaluated.
Type :help for more information.

scala> 21/04/22 20:42:07 WARN ProcfsMetricsGetter: Exception when trying to compute pagesize, as a result reporting of ProcessTree metrics is stopped

**Comment by samasalam** [comment]
Thanks for your help. The problem is solved. 

Many Thanks :)
