### ISSUE TITLE
Can't import org.neo4j.spark._

### ISSUE THREAD

**Issue by plantton** [neo4j-contrib/neo4j-spark-connector#34]
Sorry, but I think the example in the README file shall be changed. I find the maven repositories doesn't contain the newest version. https://mvnrepository.com/artifact/org.neo4j.spark

So when I try to follow the example in README, it indicates "neo4j is not a member of org".

**Comment by jexp** [comment]
It is in the spark-packages repository, see the configuration snippets for sbt and maven in the readme.
