### ISSUE TITLE
 java.lang.NoClassDefFoundError: org/apache/spark/sql/sources/v2/ReadSupport - error

### ISSUE THREAD

**Issue by karunaish** [neo4j-contrib/neo4j-spark-connector#342]
I have created a new databricks cluster with the following libraries installed.
Cluster version - 7.6 (includes Apache Spark 3.0.1, Scala 2.12)

spark_cdm_connector_0_19_1.jar
neo4j_connector_apache_spark_2_12_4_0_1_for_spark_3.jar
com.microsoft.azure:spark-cdm-connector:0.19.1 - maven file
neo4j-contrib:neo4j-connector-apache-spark_2.12:4.0.1_for_spark_3 - maven file

But while loaing CDM data from datalake to databricks I'm facing the subjected error
java.lang.NoClassDefFoundError: org/apache/spark/sql/sources/v2/ReadSupport

Should I need to change the configuration of databricks cluster or update the configuration file?
Thanks

**Comment by conker84** [comment]
@karunaish can you share the screens about how you installed the package?

**Comment by karunaish** [comment]
Hi 

I have downloaded the Jar files and uploaded in my databricks cluster library.

https://user-images.githubusercontent.com/82949543/117663966-20014980-b199-11eb-9581-e3b7ad872782.png

**Comment by conker84** [comment]
You have two neo4j jars please delete both and add one via maven

**Comment by karunaish** [comment]
You mean I have to delete both JAR and keep maven fies alone

**Comment by karunaish** [comment]
Does spark-cdm-connector-assembly-0.19.1.jar support spark 3.0 version?

https://user-images.githubusercontent.com/82949543/117666231-8dae7500-b19b-11eb-9684-ef1b7241e1fa.png

Can you see this image take from https://github.com/Azure/spark-cdm-connector/blob/master/documentation/overview.md

So in that case though "neo4j-connector-apache-spark_2.12-4.0.1_for_spark_3.jar" connector supports spark version 3 + , "spark-cdm-connector-assembly-0.19.1.jar" did not support spark 3.0 version right?  if I'm not wrong

https://user-images.githubusercontent.com/82949543/117666531-da924b80-b19b-11eb-8ed0-9de6644e0bea.png

**Comment by conker84** [comment]
we're not the owners of that plugin, so I don't know

**Comment by karunaish** [comment]
Ok Thank you for your replies
