### ISSUE TITLE
Loading 22 Mil + records into neo4j database via databricks environment

### ISSUE THREAD

**Issue by karunaish** [neo4j-contrib/neo4j-spark-connector#345]
I am using neo4j spark connector and via databricks environment - I have loaded 22 Mil records into neo4j database and While establishing relationships for this 22mil records with the query

```cypher
CALL apoc.periodic.iterate('Match (jh:JournalHeader) return jh', 'with jh MATCH (jli:JournalLineItem) where jli.glheader_id = jh.glheader_id MERGE (jh)-[:HAS_PARENT]->(jli)', {batchSize:1000, parallel:false}) yield batch return null;")\
```

Though the required relationships got established in neo4j database. The spark job is hanging and no updates are being written.

Is there a way to make the query more efficient so once the relationships got established it will finish the job. Because in this case though the relationships got established still the query is searching for all the other records which is not necessary in this case.

**Comment by conker84** [comment]
@karunaish as I said in the APOC issue we also need the code of the spark job and the structure of the source dataframe

**Comment by karunaish** [comment]
Hi

Structure of the source Dataframe:

```
uid:string
glline_id:string
glheader_id:string
amount:float
amountCreditDebitIndicator:string
amountCurrency:string
approvedBy:string
approvedDateTime:date
businessUnitCode:string
customerID:string
jeLineDescription:string
fiscalYear:integer
glAccountNumber:string
journalEntryType:string
journalId:string
journalIdLineNumber:integer
lastModifiedBy:string
lastModifiedDate:date
manualFlag:string
reportingAmount:float
reversalIndicator:string
reversalJournalId:string
segment01:string
segment02:string
segment03:string
segment04:string
segment05:string
sourceId:string
taxCode:string
name:string
```

Step 1 ) Have created index and Constraints initially and loaded the data into neo4j desktop with the below code:

```scala
Journalheaderdf.write.format("org.neo4j.spark.DataSource")\
                     .option("url", "bolt://xxx.com:7687")\
                     .option("authentication.type", "basic")\
                     .option("authentication.basic.username", "xxx")\
                     .option("authentication.basic.password", "xxx")\
                     .option("database", "mydb")\
                     .option("labels",":JournalHeader")\
                     .option("script","""CREATE INDEX ON :JournalHeader(glheader_id);
                                         CREATE CONSTRAINT ON (jh:JournalHeader) ASSERT jh.uid IS UNIQUE;""")\
                     .save()
```

Step 2) : Loaded Journal Line Item into neo4j database similiar to step 1

Step 3 ) Establishing relationships between both using the following code

```scala
JournalLineItemdf.write.format("org.neo4j.spark.DataSource")\
            .mode("Overwrite")\
            .option("url",  "bolt://xxx.com:7687")\
            .option("authentication.basic.username", "xxx")\
            .option("authentication.basic.password", "xxx")\
            .option("database", "mydb")\
            .option("query","CALL apoc.periodic.iterate('Match (jh:JournalHeader) return jh', 'with jh MATCH (jli:JournalLineItem) where jli.glheader_id = jh.glheader_id  MERGE (jh)-[:HAS_PARENT]->(jli)', {batchSize:1000, parallel:false}) yield batch return null;")\
            .save()
```

While running above query I'm facing the subjected issue.

**Comment by conker84** [comment]
This is not working because for each row you are scanning all the `(jh:JournalHeader)` into the database while, if I understood correctly it's enough to get the current one described by the `JournalLineItemdf` row:
```
JournalLineItemdf.write.format("org.neo4j.spark.DataSource")\
            .mode("Overwrite")\
            .option("url",  "bolt://xxx.com:7687")\
            .option("authentication.basic.username", "xxx")\
            .option("authentication.basic.password", "xxx")\
            .option("database", "mydb")\
            .option("batch.size","1000")\
            .option("query","MATCH (jh:JournalHeader{uuid: event.uuid}) MATCH (jli:JournalLineItem{glheader_id: jh.glheader_id}) MERGE (jh)-[:HAS_PARENT]->(jli)")\
            .save()
```

If the `uuid` in the `JournalLineItemdf` is the uuid of `JournalHeader`

**Comment by karunaish** [comment]
Hi 

Thanks for the query . This query is getting completed from databricks end. But no updates in Neo4j Database. Please check the below screenshots.

https://user-images.githubusercontent.com/82949543/117962849-96c45100-b317-11eb-8d14-73cd57ccd1a4.png

No updates in neo4j end :  Below Screenshot:

https://user-images.githubusercontent.com/82949543/117962904-aba0e480-b317-11eb-95d5-6653df1ce8be.png 

Also  FYI - currently for checking this i used 100 thousand records but the actual data is 22 million.

**Comment by conker84** [comment]
This is something that you need to figure out in your data model, the only thing that I can do is to provide you a guideline, you need to check how you can get `MATCH (jh:JournalHeader{uuid: event.<your_row_column>})` returning a node

**Comment by conker84** [comment]
Btw did you define an index for `JournalLineItem(glheader_id)`? I saw that you defined it only for `JournalHeader(glheader_id)`

**Comment by karunaish** [comment]
Yes I have defined Index for both JournalHeader and JournalLineItem.

JournalLineItemdf.write.format("org.neo4j.spark.DataSource")\
                     .option("url", "bolt://xxx.com:7687")\
                     .option("authentication.type", "basic")\
                     .option("authentication.basic.username", "xxx")\
                     .option("authentication.basic.password", "xxx")\
                     .option("database", "mydb")\
                     .option("labels",":JournalLineItem")\
                     .option("script","""CREATE INDEX ON :JournalLineItem(glheader_id);
                                         CREATE CONSTRAINT ON (jli:JournalLineItem) ASSERT jli.uid IS UNIQUE;""")\
                     .save()
