### ISSUE TITLE
repartition(1) - Makes loading very slow

### ISSUE THREAD

**Issue by karunaish** [neo4j-contrib/neo4j-spark-connector#348]
Hi 

When I load 20 Million records from spark  - Databricks into neo4j when I mention repartition (1) While writing into neo4j - It takes a lot of time for loading all the records. If I didnt mention repartition(1) it is failing with database not upto the requested version error. How to overcome this?

**Comment by conker84** [comment]
Hi @karunaish you should add more infos otherwise we're not able to assist you:
* the code of your spark job
* the Databricks runtime specs
* the Neo4j specs (cluster/single?)
* what do you mean by `very slow`? can you give us a quantity of time? 
Thank you

**Comment by conker84** [comment]
we also need:
* the structure of your dataframe
* did you define the constraints/indexes?

**Comment by karunaish** [comment]
1) the code of spark job

`JournalLineItemdf.repartition(1).write.format("org.neo4j.spark.DataSource")\`
		 `.mode("overwrite")\`
		 `.option("url", "bolt://xxx:7687")\`
		 `.option("authentication.type", "basic")\`
		 `.option("authentication.basic.username", "xxx")\`
		 `.option("authentication.basic.password", "xxx")\`
		 `.option("database", "mydb")\`
		 `.option("labels","JournalLineItem")\`
		 `.option("node.keys","uid")\`
		 `.option("script","""CREATE INDEX ON :JournalLineItem(glheader_id)`
                             `CREATE CONSTRAINT ON (jli:JournalLineItem) ASSERT jli.uid IS UNIQUE;""")\`
         `.save()`

2) DBR specifications:

`6.4 (includes Apache Spark 2.4.5, Scala 2.11)`

Libraries:

- spark_cdm_connector_assembly_0_19_0.jar
- neo4j-contrib:neo4j-connector-apache-spark_2.11:4.0.1

3) Neo4j - Single

4) Time:

22 Mill Records - 8 + hours

**Comment by conker84** [comment]
@karunaish 

> we also need:
> 
> * the structure of your dataframe
> * did you define the constraints/indexes?

@karunaish please we also need this

**Comment by karunaish** [comment]
1) structure of dataframe

`uid:string`
`glline_id:string`
`glheader_id:string`
`amount:float`
`amountCreditDebitIndicator:string`
`amountCurrency:string`
`approvedBy:string`
`approvedDateTime:date`
`businessUnitCode:string`
`customerID:string`
`jeLineDescription:string`
`fiscalYear:integer`
`glAccountNumber:string`
`journalEntryType:string`
`journalId:string`
`journalIdLineNumber:integer`
`lastModifiedBy:string`
`lastModifiedDate:date`
`manualFlag:string`
`reportingAmount:float`
`reversalIndicator:string`
`reversalJournalId:string`
`segment01:string`
`segment02:string`
`segment03:string`
`segment04:string`
`segment05:string`
`sourceId:string`
`taxCode:string`
`name:string`

2) Yes

`.option("script","""CREATE INDEX ON :JournalLineItem(glheader_id)`
`CREATE CONSTRAINT ON (jli:JournalLineItem) ASSERT jli.uid IS UNIQUE;""")\`

**Comment by conker84** [comment]
Please read this guide:
https://neo4j.com/developer/spark/faq/#_how_can_i_speed_up_writes_to_neo4j
Bascally you need to tune the option `batch.size` and adjust the parameter partition:

```
JournalLineItemdf.repartition(<your_value>).write.format("org.neo4j.spark.DataSource")\
.mode("overwrite")\
.option("url", "bolt://xxx:7687")\
.option("authentication.type", "basic")\
.option("authentication.basic.username", "xxx")\
.option("authentication.basic.password", "xxx")\
.option("batch.size", "<your_value>")\
.option("database", "mydb")\
.option("labels","JournalLineItem")\
.option("node.keys","uid")\
.option("script","""CREATE INDEX ON :JournalLineItem(glheader_id)
CREATE CONSTRAINT ON (jli:JournalLineItem) ASSERT jli.uid IS UNIQUE;""")\
.save()
```

You should "repartition" to a sustainable number according to your Neo4j instance configuration please try something between 1 and 10

Your batch size should be defined according to your Neo4j instance configuration please try something between 5000 and 20000

**Comment by karunaish** [comment]
@conker84 Thank you .Will try the mentioned parameters

**Comment by karunaish** [comment]
Hi @conker84 

If I gave repartition as 10 or any other number except 1 - I'm getting the below error:

Caused by: [CIRCULAR REFERENCE: org.neo4j.driver.exceptions.TransientException: Database 'new1' not up to the requested version: 523. Latest database version is 517]

Total record  count 23,000,000

Time taken -  1hours 22mins 34s 116ms and it got failed after loading (15,360,000) records .

the code of spark job - Same as above
the Databricks runtime specs - Same as above
the Neo4j specs (cluster/single?) - Same as above
the structure of your dataframe - Same as above
did you define the constraints/indexes? - Yes

**Comment by conker84** [comment]
what is the batch size?

**Comment by karunaish** [comment]
Hi Batch size is  - 20000

**Comment by conker84** [comment]
I forwarded this to the Neo4j java driver team, in the meanwhile please use partition(1) with the batch size

**Comment by karunaish** [comment]
Sure Thanks

**Comment by conker84** [comment]
@karunaish If I share a jar with you are you willing to test it?

**Comment by karunaish** [comment]
@conker84 - yes do share with me. I can test it from my end.

**Comment by conker84** [comment]
[neo4j-connector-apache-spark_2.11-4.0.2_for_spark_2.4.jar.zip](https://github.com/neo4j-contrib/neo4j-spark-connector/files/6516432/neo4j-connector-apache-spark_2.11-4.0.2_for_spark_2.4.jar.zip)

@karunaish thank you

**Comment by conker84** [comment]
@karunaish any feedback on this?

**Comment by karunaish** [comment]
Hi @conker84 I have added the respective JAR file into the cluster libraries and tried running the above query for 22 Million records with the same previously mentioned configurations and query with repartition(10) and batch Size - 20000. But it got failed after running for 1.47 hours it loaded (16,801,798) records and failed with the below error.

Database 'abc' not up to the requested version: 599. Latest database version is 592.

Please refer below screenshot.

https://user-images.githubusercontent.com/82949543/119161248-0097d580-ba51-11eb-92c4-2991d40879f9.png

Thanks.

**Comment by conker84** [comment]
@karunaish Can you try with a fresh Databricks cluster instance?

**Comment by conker84** [comment]
@karunaish ping

**Comment by karunaish** [comment]
@conker84 - We will create a fresh cluster and check on it and will update you.

**Comment by conker84** [comment]
@karunaish any news?

**Comment by karunaish** [comment]
Hi @conker84 When I tried with fresh cluster instance with DBR runtime version - 6.4 Extended Support (includes Apache Spark 2.4.5, Scala 2.11, and if I use repartition 10 - It is giving same error.

But however if I mention repartition(1) - with batch size - 30000 for 22 MIL records compared to the previous version of JAR with the new one loads are happening much faster.

**Comment by conker84** [comment]
@karunaish can you share the dataset and the notebook? Or give us access to them.
We're not able to reproduce your problem

**Comment by karunaish** [comment]
hi @conker84 - I will check on this and will update you.

**Comment by conker84** [comment]
@karunaish ping

**Comment by lakshmannikhil** [comment]
Hi @conker84 I am a colleague of Karuna, I am gonna continue working on this, will provide you with the requested information soon. Please let me know a convenient time to discuss this. One thing is even though original issue was raised with the repartition even if we don't repartition we keep running into the same error. I have looked at stackoverflow as well where people are having same errors
https://stackoverflow.com/questions/65908235/running-spark-2-4-4-with-neo4j-connector-getting-transientexception-for-db-versi

**Comment by moxious** [comment]
is there a next step on this ticket?

**Comment by lakshmannikhil** [comment]
Hi

Please close i was monitoring the VM metrics and found some 100% spikes there which might have caused things to not work.
