### ISSUE TITLE
Change org of package to org.neo4j for maven central publishing

### ISSUE THREAD

**Issue by moxious** [neo4j-contrib/neo4j-spark-connector#354]
We need to update the pom to publish to groupId `org.neo4j` so that JARs can be published under neo4j's key on maven central.

Note that this ticket must also make changes to the documentation, because when we change the maven coordinates it impacts installation advice we have in the manual right now.

TBD: whether we issue a patch release just for the coordinate change.

This change will enable publishing via maven central in the TeamCity build.

**Comment by moxious** [comment]
@conker84 re-opening.  Note that the ticket needs to concern documentation and quickstart coordinates such as here https://neo4j.com/developer/spark/quickstart/

**Comment by conker84** [comment]
@moxious closing via bb38be4

**Comment by moxious** [comment]
Related https://github.com/neo4j-contrib/neo4j-spark-connector/issues/334

**Comment by axololtl1997** [comment]
Hello, 
When will neo4j-spark-connector be moved to maven2 repo?
Also, will versions compatible with older versions of spark (2.2.x) be uploaded on the maven2 repo?
Thanks again

**Comment by moxious** [comment]
@axololtl1997 update, we are working on this during this week.   Example URLs are right here: https://search.maven.org/search?q=g:org.neo4j%20AND%20a:neo4j-connector-apache-spark_2.11 

We're not quite finished publishing all of the artifacts and verifying that it works in the install processes we need to support, but we're actively working on this right now.

**Comment by moxious** [comment]
The 2.2.x versions of the connector are deprecated, not supported, and will not be moved to maven central

**Comment by moxious** [comment]
@axololtl1997 publishing complete as of now.
