### ISSUE TITLE
Null query result error - java.lang.UnsupportedOperationException: empty collection

### ISSUE THREAD

**Issue by annievic** [neo4j-contrib/neo4j-spark-connector#36]
I am using neo4j-spark-connector version 2.0.0-M2 and getting the above error when my query returns no results. The code is like:

`query = 'MATCH (a:PEOPLE)-[:INVOLVED_IN]->(b.EVENT)`
`WHERE a.person_id IN [123, 456, 789] `
`RETURN a.person_id AS id, count(distinct b.event_id) AS count`

`val result = neo.cypher(query).batch(25).loadDataFrame`

But when none of the ids in the WHERE clause are in the graph (which is possible for my use case) I get the error `java.lang.UnsupportedOperationException: empty collection`. I would expect an empty dataframe with columns id and count.

Stack trace (sensitive data has been redacted):
![neo4j_empty_collection_error-1](https://user-images.githubusercontent.com/9266252/27132943-7b49c3a8-5108-11e7-849a-9e3c08cb03b2.png)

At the moment I've got round the error by changing my `MATCH` to `OPTIONAL MATCH` but it feels a bit hacky.

**Comment by jexp** [comment]
I found the issue, the problem is, that it cannot infer the schema from empty results b/c it needs the first row to look at the data types. If you use `loadDataFrame( "id" -> "long", "count" -> "long" )` it should work also with empty results.

**Comment by jexp** [comment]
Please test that and let me know, I added a more detailed error message now.

**Comment by conker84** [comment]
I'm closing this because it's more than 1yr old feel free to reopen in case the issue is not solved
