### ISSUE TITLE
Change constraint naming convention

### ISSUE THREAD

**Issue by conker84** [neo4j-contrib/neo4j-spark-connector#361]
If we have one dataframe with two columns [id:nullable,name:nullable] and two spark jobs like:

Job 1:
```scala
ds.write
      .format(classOf[DataSource].getName)
      .option("labels", ":City")
      .option("node.keys", "id")
      .option("schema.optimization.type", "NODE_CONSTRAINTS")
      .save()
```

Job 2:
```scala
ds.write
      .format(classOf[DataSource].getName)
      .option("labels", ":City")
      .option("node.keys", "name")
      .option("schema.optimization.type", "NODE_CONSTRAINTS")
      .save()
```

Under the hood we try to create two constraints:

Job 1:
```
"CREATE CONSTRAINT `spark_NODE_CONSTRAINTS_City`
ON (n:City) ASSERT (n.id) IS UNIQUE
```

Job 2:
```
"CREATE CONSTRAINT `spark_NODE_CONSTRAINTS_City`
ON (n:City) ASSERT (n.name) IS UNIQUE
```

The second constant will not be created because of the same name, we need to add the property into the constraint naming convention.

**Comment by utnaf** [comment]
Just for clarity, the new names will be `spark_NODE_CONSTRAINTS_City_name` and `spark_NODE_CONSTRAINTS_City_id`.

Correct?

**Comment by conker84** [comment]
Yes but also. `spark_NODE_CONSTRAINTS_Person_name-surname` for multiple keys
