### ISSUE TITLE
Apache Spark Databricks is not finishing the job and not termintiating even after the relationships are created properly.

### ISSUE THREAD

**Issue by lakshmannikhil** [neo4j-contrib/neo4j-spark-connector#366]
Hi
We are creating relationship between existing nodes in the database using the below query from databricks.

```scala
JournalLineItemdf.repartition(1).write.format("org.neo4j.spark.DataSource")
            .mode("Overwrite")
            .option("url",  "bolt://XXXXXXX.azure.com:7687")
            .option("authentication.basic.username", "XXXX")
            .option("authentication.basic.password", "XXXX")
            .option("database", "db")
            .option("batch.size","30000")
            .option("query","""CALL apoc.periodic.iterate(
'MATCH(jh:JournalHeader) return jh', 'with jh MATCH (jli:JournalLineItem) WHERE jli.glheader_id=jh.uid MERGE(jh)-[:HAS_PARENT]->(jli)',
{batchSize:10000, parallel: true, iterateList:true}) yield batch return null;""")
            .save()
```

This query creates the required relationships, However it is not finishing the job as you can see from the below screenshot 

![image](https://user-images.githubusercontent.com/30304701/120785987-55584780-c54b-11eb-9ed3-3a4bc2dc768b.png)
If you look at the stderr from the 3rd task executing in the screenshot it shows the below query
![image](https://user-images.githubusercontent.com/30304701/120786297-ac5e1c80-c54b-11eb-8931-b37950284912.png)
but it just doesn't get completed from databricks perspective

## Expected Behavior (Mandatory)

Query should updated the relationship and finish the job

## Actual Behavior (Mandatory)

Query updates the relationships but the job keeps running

### Versions

- Spark: DBR 6.4 Extended Support | Spark 2.4.5 | Scala 2.11
- Scala:2.11
- Neo4j: 4.2.2
- Neo4j Connector:neo4j_connector_apache_spark_2_11_4_0_2 (This was shared by @conker84 for an earlier issue reported)

## Additional information

* The code of the Spark job already provided
* did you define the constraints/indexes? Yes
* if you're you using any Spark Cloud provider please specify it (ie: Databricks)

**Comment by moxious** [comment]
@lakshmannikhil it appears that in this code, you aren't really trying to write a data frame, but you're executing a generic cypher query by using the spark connector.   The reason I am saying this is because the `event` variable is not referenced in your Cypher query.

Writing dataframes with Cypher queries using this connector expects that you're going to use that `event` variable.  If you want to execute a general Cypher query that is not in any way tied to the contents of a dataframe, then the spark connector is not the best way to do that.

When you use the connector in your environment, it comes with it all of the driver classes for the Neo4j official java driver.  As a result, a better option for you here would be use regular java or scala code as a Neo4j Client (you can read about that here: https://neo4j.com/docs/java-manual/current/client-applications/).  The classes you need are already available because you have the spark connector.

I'd like to ask more about your workflow though, and what you're trying to do here.  We want to improve the documentation for the spark connector, so it'd be helpful to know what led you to this usage pattern, so we can do a better job of indicating the best way to handle those situations.

**Comment by lakshmannikhil** [comment]
@moxious Hi will try a general java or scala load,As far as your question is concerned, We were using the Dataframe to write nodes so we just reused the same format for the relationship query and expected that it should be able to execute without any issues.

We will see if a generic Scala or Java load works and reach out in case of any questions. Thanks for your quick response

**Comment by moxious** [comment]
@lakshmannikhil the same format does work _if you refer the event variable in the query_.  But the entire purpose of the connector is to bind data from a dataframe into a Cypher query in the end.  So to run a query without an event variable works around the purpose of what the connector is trying to do.  

There's nothing wrong with wanting to run generic cypher queries separate from a dataframe.  We want to get to better documentation to describe how this is done, but the particular pattern that you are doing here isn't the best approach, and so debugging why there might be issues with it is perhaps not the best use of time.  In particular, when you use apoc.periodic.iterate, you are creating sub-queries and sub-jobs inside of cypher, so this pattern creates quite a complex structure much of which can't even be observed by the spark-connector.  This is why it often pays to back up and assess the approach carefully.

**Comment by lakshmannikhil** [comment]
Understood that we are working on the alternate approach that you have suggested, I am closing this.

Thank you

**Comment by lakshmannikhil** [comment]
@moxious Can you show an example of how i can change the default database while running from java or scala

**We tried as shown below**

import org.neo4j.driver.{AuthTokens,GraphDatabase}
import org.neo4j.driver.Transaction

val driver = GraphDatabase.driver("bolt://***********:7687/", AuthTokens.basic("****", "******"))

val session = driver.session
val result=session.run("use testdbpart;")
val tx=session.beginTransaction
val script ="""CALL apoc.periodic.iterate(
'MATCH(jh:JournalHeader) return jh', 'with jh MATCH (jli:JournalLineItem) WHERE jli.glheader_id=jh.uid MERGE(jh)-[:HAS_PARENT]->(jli)',
{batchSize:10000, parallel: true, iterateList:true}) yield batch return null"""
val result1=tx.run(script)
tx.commit()
tx.close()


**but it fails giving the below error message**
org.neo4j.driver.exceptions.ClientException: Query cannot conclude with USE GRAPH (must be RETURN or an update clause) (line 1, column 1 (offset: 0))

**Comment by moxious** [comment]
@lakshmannikhil this is just a regular cypher error.  Here:

```
val result=session.run("use testdbpart;")
```

is not a valid cypher query.  What you should instead do is use the session API to run your later query against that database.  Check the session API in the java driver docs, and don't use the "USE" syntax
