### ISSUE TITLE
Sort Partitions by internal ID

### ISSUE THREAD

**Issue by conker84** [neo4j-contrib/neo4j-spark-connector#370]
For the partitioning, we use the skip/limit mechanism, and as described into the [docs](https://neo4j.com/docs/cypher-manual/current/clauses/skip/)

```
Please note that no guarantees are made on the order of the result unless the query specifies the ORDER BY clause
```

we need to allow to the use to define an order by cause.

Unfortunately, unlike pushdown filters, we cannot catch `orderBy` ops of a dataframe and we need to allow something like this:

```
ss.read.format(classOf[DataSource].getName)
      .option("url", SparkConnectorScalaSuiteIT.server.getBoltUrl)
      .option("labels", ":Person:Customer")
      .option("partitions", "5")
      .option("partitions.sort.column", "id")
      .option("partitions.sort.direction", "desc")
      .load()
```

**Comment by moxious** [comment]
Do not use extra parameters in this case but for generated cypher queries always ORDER BY id(n) ASC
