### ISSUE TITLE
Relationships creating with option "query"

### ISSUE THREAD

**Issue by olegbogutskyy-ayasdi** [neo4j-contrib/neo4j-spark-connector#373]
Hi, 
I want to create nodes and relations based on dataframe. 
I divided long complex cypher query to nodes only and relations only. 
So nodes part can be run with batch option and processed in parallel, and it works just fine.
On other hand I need relations part be processed not in parallel to avoid LockClient exception. But LockClient exception raises . Can't understand why, does transactions run in parallel? if yes then how can I set up it to run transactions one by one?

Here is relations part examlpe:

```
cypher_query = """
     MATCH (p:Person {id: event.id}),
                   (a:Account {id: event.account_id}),
                   (b:Bank {id: event.bank_id}),
                   (addr:Address {id: event.address_id})
     MERGE (p)-[:HOLDER]->(a)
     MERGE (b)-[:BANK]->(a)
     MERGE (e)-[:RESIDENCE]->(addr)
"""
```

```scala
df.write.format("org.neo4j.spark.DataSource") \
      .option("url", neo4j_uri) \
      .option("authentication.type", "basic") \
      .option("authentication.basic.username", "user") \
      .option("authentication.basic.password", "password") \
      .mode('Overwrite') \
      .option("query", cypher_query) \
      .save()
```

Thanks in advance

**Comment by utnaf** [comment]
Hi! Can you tell me please which version of Spark and connector are you using?

**Comment by olegbogutskyy-ayasdi** [comment]
> Hi! Can you tell me please which version of Spark and connector are you using?

Hi, spark version 3.0.1 and neo4j-connector-apache-spark_2.12_3.0-4.0.0.jar

**Comment by utnaf** [comment]
Is the dataframe partitioned? What's the output of `df.rdd.getNumPartitions`?

If it's greater than 1 you might want to repartition it to 1.

If I got this correctly, this [FAQ](https://neo4j.com/developer/spark/faq/#_my_writes_are_failing_due_to_deadlock_exceptions) explains the issue better.

**Comment by olegbogutskyy-ayasdi** [comment]
> Is the dataframe partitioned? What's the output of `df.rdd.getNumPartitions`?


oh my gosh, it's 12!!! Thanks for that! Now it makes sense
