### ISSUE TITLE
neo4j connector not getting downloaded from maven

### ISSUE THREAD

**Issue by praveenkumarb1207** [neo4j-contrib/neo4j-spark-connector#375]
## Guidelines

Please note that GitHub issues are only meant for bug reports/feature requests. If you have questions on how to use the Neo4j Connector for Apache Spark,
please ask on [the Neo4j Discussion Forum](https://community.neo4j.com/c/integrations/18) instead of creating an issue here.

## Expected Behavior (Mandatory)

As the package is in maven , it should be downloaded and should be able to use it inside the spark-shell

## Actual Behavior (Mandatory)

Getting the following error when starting the spark-shell 

```
:: problems summary ::
:::: WARNINGS
                ::::::::::::::::::::::::::::::::::::::::::::::

                ::          UNRESOLVED DEPENDENCIES         ::

                ::::::::::::::::::::::::::::::::::::::::::::::

                :: org.neo4j#neo4j-connector-apache-spark_2.11;4.0.2_for_spark_2.4: java.text.ParseException: inconsistent module descriptor file found in 'https://repo1.maven.org/maven2/org/neo4j/neo4j-connector-apache-spark_2.11/4.0.2_for_spark_2.4/neo4j-connector-apache-spark_2.11-4.0.2_for_spark_2.4.pom': bad module name: expected='neo4j-connector-apache-spark_2.11' found='neo4j-connector-apache-spark_2.12';

                ::::::::::::::::::::::::::::::::::::::::::::::


:::: ERRORS
                central: bad module name found in https://repo1.maven.org/maven2/org/neo4j/neo4j-connector-apache-spark_2.11/4.0.2_for_spark_2.4/neo4j-connector-apache-spark_2.11-4.0.2_for_spark_2.4.pom: expected='neo4j-connector-apache-spark_2.11 found='neo4j-connector-apache-spark_2.12'
```

## How to Reproduce the Problem
Start the spark-shell with the following command 

````
spark-shell  --packages "org.neo4j:neo4j-connector-apache-spark_2.11:4.0.2_for_spark_2.4"
````
For package , I have referred the following link 

https://search.maven.org/artifact/org.neo4j/neo4j-connector-apache-spark_2.11/4.0.2_for_spark_2.4/jar

### Versions

- Spark: 2.4.0 (standalone spark)
- Scala:2.11.12
- Neo4j:3.5.26
- Neo4j Connector:4.0.2_for_spark_2.4

**Comment by utnaf** [comment]
Hi @praveenkumarb1207, we are looking into the issue. In the meantime please consider using the JAR directly as mentioned [here](https://neo4j.com/developer/spark/quickstart/#_where_to_get_the_jars).

**Comment by utnaf** [comment]
Just wanted to tell you that if you use Scala 2.12 and Spark 2.4 it should be working. The issue appears to be only on Scala 2.11 and Spark 2.4.

**Comment by praveenkumarb1207** [comment]
Hi @utnaf  , as suggested we are currently using jars .  Please let us know  if this issue gets fixed

**Comment by utnaf** [comment]
Sure, I'll ping you in this thread

**Comment by joeljgeorge** [comment]
Did this end up getting fixed?

**Comment by utnaf** [comment]
Hey all, not yet I'm sorry. We need to wait the next release to fix it. You can download the JAR directly from the [release page](https://github.com/neo4j-contrib/neo4j-spark-connector/releases) or from the [Neo4j Connector page](https://neo4j.com/product/connectors/apache-spark-connector/).
