### ISSUE TITLE
Unable to write relationships using saveMode.Append and source/target saveMode.Match

### ISSUE THREAD

**Issue by mroiter-larus** [neo4j-contrib/neo4j-spark-connector#384]
## Expected Behavior (Mandatory)

A customer reports that, as per the documentation, it should be possible writing relationships to neo4j without overwriting nodes, with save modes `Append` and `Match` as given below. 

```
.mode(SaveMode.Append)
.option("relationship", ":rel_name")
.option("relationship.properties", "rel_id, rel_timestamp, rel_name, rel_type, rel_file_id")
.option("relationship.save.strategy", "keys")
.option("relationship.source.save.mode", "Match")
.option("relationship.source.labels", "name, claimtag")
.option("relationship.source.node.keys", "src_uid:uid, src_type:type, claimtag")
.option("relationship.target.save.mode", "Match")
.option("relationship.target.labels", "name, claimtag")
.option("relationship.target.node.keys", "dst_uid:uid, dst_type:type, claimtag")
```

## Expected Behavior (Mandatory)

It should create the relationships.

## Actual Behavior (Mandatory)

They get the following error:

```
This works only with `relationship.source.save.mode` `Overwrite`
java.lang.IllegalArgumentException: This works only with `relationship.source.save.mode` `Overwrite` 
```

### Versions

- Spark: 2.4.5/open source
- Scala: 2.12.12
- Neo4j:
- Neo4j Connector: neo4j-connector-apache-spark_2.12-4.0.2_for_spark_2.4

**Comment by conker84** [comment]
It should be fixed in newer version feel free to reopen if you have new info.
