### ISSUE TITLE
Cypher query - Read parallel

### ISSUE THREAD

**Issue by baskar1981** [neo4j-contrib/neo4j-spark-connector#388]
Hi,
I am using the below script to download 1 million data from Neo4j.
    Neo4j neo4j = new Neo4j(sparkSession.sparkContext());
    Dataset<Row> neo4jrecords=null;
    neo4jrecords = neo4j.cypher(query, params).partitions(4)
        .batch(25000)
        .loadDataFrame(fields);

When I pass the partition as 1, it downloads all the unique records. If i pass the partition value as more than 1, it downloads the duplicate records (Total *number of partitions). 
Could you please help me how to implement the parallel call like the below apoc exporty query using this connector?.

call apoc.export.csv.query("match(a:User) where a.active=true return a.username", "/tmp/users.csv",{parallel: true, batchSize: 1000});

**Comment by utnaf** [comment]
Hi @baskar1981, you are using an unsupported version of the connector. Please use the latest you can find here https://github.com/neo4j-contrib/neo4j-spark-connector/releases/tag/4.0.2

Docs available here https://neo4j.com/developer/spark/

**Comment by baskar1981** [comment]
Thanks. I have made the changes and tried to execute the below code. But I am getting an error.

```
   Dataset<Row> ds = sparkSession.read().format("org.neo4j.spark.DataSource")
        .option("url", **URL***)
        .option("authentication.basic.username", "test")
        .option("authentication.basic.password", "test")
        .option("partitions", 6)
        .option("query", query)
        .load();
```

```
org.neo4j.driver.exceptions.ClientException: Invalid input '{': expected whitespace, comment, namespace of a procedure or a procedure name (line 1, column 6 (offset: 5))
"CALL { MATCH(a:User) where a.active=true RETURN a.email_string }"
```

If I remove the partition from the above code, I was able to download the records from the neo4j.

Could you please help me on how to implement async download from the neo4j?

**Comment by utnaf** [comment]
is this your query?

`CALL { MATCH(a:User) where a.active=true RETURN a.email_string }`

I suggest you to just use `MATCH(a:User) where a.active=true RETURN a.email_string`

You probably don't need partitions while reading, remove the partition option and you can repartition afterwards.

**Comment by baskar1981** [comment]
I am just passing the below query.
MATCH(a:User) where a.active=true RETURN a.email_string. I am not sure why this match was wrapped inside Call method.

How can we implement the batch with the parallel download similar to the below apoc query?
call apoc.export.csv.query("MATCH(a:User) where a.active=true return aa.email_string","/tmp/results2.csv",**{{batchSize:10000, parallel:true}});**

**Comment by conker84** [comment]
@baskar1981 `apoc.export.csv.query` does not provide that behaviour at all. If you provide those optional parameters they don't affect the procedure. If you want parallelize via apoc you need to combine `apoc.periodic.iterate` and `apoc.export.csv.query`.

In spark you can parallelize a query with a job like this:

```
ss.read.format(classOf[DataSource].getName)
      .option("url", SparkConnectorScalaSuiteIT.server.getBoltUrl)
      .option("query",
        """
          |MATCH (p:Person)-[r:BOUGHT]->(pr:Product{name: 'Product 2'})
          |RETURN p.name AS person, pr.name AS product, r.quantity AS quantity""".stripMargin)
      .option("partitions", "5")
      .option("query.count",
        """
          |MATCH (p:Person)-[r:BOUGHT]->(pr:Product{name: 'Product 2'})
          |RETURN count(p) AS count""".stripMargin)
      .load()
```

is important to configure the `query.count` option in order to allow the connector to understand the amount of data that it will have to extract; than that count will be divided for the number of partitions.

**Comment by conker84** [comment]
Hi I'm closing this for lack of feedback, feel free to reopen if you have anything new to share

**Comment by baskar1981** [comment]
Hi,
I have implemented the changes using the below library. It was working for more than 5 days. Then I have started to see the below error. I am using neo4j version  Neo4j 3.5.12.
Error: 2021-11-23 13:19:56.018 ERROR 4261 --- [  restartedMain] org.neo4j.spark.service.SchemaService    : Query not compiled because of the following exception:

org.neo4j.driver.exceptions.TransientException: Database not up to the requested version: 675969205. Latest database version is 675969141

<dependency>
    <groupId>org.neo4j</groupId>
    <artifactId>neo4j-connector-apache-spark_2.12</artifactId>
    <version>4.0.2_for_spark_3</version>
</dependency>

**Comment by baskar1981** [comment]
Hi,
I have implemented the changes using the below library. It was working for more than 5 days. Then I have started to see the below error. I am using neo4j version  Neo4j 3.5.12.
Error: 2021-11-23 13:19:56.018 ERROR 4261 --- [  restartedMain] org.neo4j.spark.service.SchemaService    : Query not compiled because of the following exception:

org.neo4j.driver.exceptions.TransientException: Database not up to the requested version: 675969205. Latest database version is 675969141

<dependency>
    <groupId>org.neo4j</groupId>
    <artifactId>neo4j-connector-apache-spark_2.12</artifactId>
    <version>4.0.2_for_spark_3</version>
</dependency>

**Comment by conker84** [comment]
Can you try with the last released version? It’s 4.1.0

**Comment by baskar1981** [comment]
I think I had some issue on the latest version. Hence I have switched to the old version. Anyway I will update the new connector and get back to you with a result.

**Comment by baskar1981** [comment]
Hi,
I have used the 4.1.0 connector. The performance of my job increased from 1:30 hrs to 4 to 6 hours to complete the neo4j download and insert the result into the azure sql. I didn't change any code change for using the new connector. I am not sure why the performance was impacted when using the new connector.

**Comment by conker84** [comment]
That's odd the 4.1.0 release focused on Streaming Support. Can you please add the code of the Spark job and the indexes/constraints defined in your database?

**Comment by conker84** [comment]
We're closing this for lack of feedback, feel free to reopen in case you have more info to share
