### ISSUE TITLE
Shutdown bintray repo in docs

### ISSUE THREAD

**Issue by lorenz-nlp** [neo4j-contrib/neo4j-spark-connector#396]
The documentation provides a maven repository to add in order to retrieve the neo4j-spark-connector packages. However, this repository does not longer exist (dl.bintray.com). Therefore, the documentation should be updated and the correct repository should be given:

```
<repositories>
    <repository>
        <id>SparkPackagesRepo</id>
        <url>https://repos.spark-packages.org</url>
    </repository>
</repositories>
```

### Steps to reproduce

1. Clean the local maven repository
2. Perform mvn clean install on a project with dependency to neo4j-spark-connector

**Comment by conker84** [comment]
closed via #427
