### ISSUE TITLE
mvn compilation failed

### ISSUE THREAD

**Issue by Mageswaran1989** [neo4j-contrib/neo4j-spark-connector#4]
Hi,

While trying to build in my machine, I am getting following error:

mdhandapani@VID-Android:~/neo4j-spark-connector$ mvn clean install assembly:single -DskipTests 
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.neo4j.spark:neo4j-spark-connector_2.11:jar:1.0-SNAPSHOT
[WARNING] 'artifactId' contains an expression but should be a constant. @ org.neo4j.spark:neo4j-spark-connector_${scala.version.suffix}:1.0-SNAPSHOT, /home/mdhandapani/neo4j-spark-connector/pom.xml, line 8, column 17
[WARNING] The expression ${artifactId} is deprecated. Please use ${project.artifactId} instead.
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building neo4j-spark-connector 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading: http://repo.maven.apache.org/maven2/org/apache/lucene/lucene-solr-grandparent/5.5.0/lucene-solr-grandparent-5.5.0.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1:02.536s
[INFO] Finished at: Wed Jul 13 16:24:49 KOST 2016
[INFO] Final Memory: 18M/327M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project neo4j-spark-connector_2.11: Could not resolve dependencies for project org.neo4j.spark:neo4j-spark-connector_2.11:jar:1.0-SNAPSHOT: Failed to collect dependencies for [org.neo4j.driver:neo4j-java-driver:jar:1.0.2 (compile), org.apache.spark:spark-core_2.11:jar:1.6.0 (provided), org.apache.spark:spark-graphx_2.11:jar:1.6.0 (provided), org.apache.spark:spark-sql_2.11:jar:1.6.0 (provided), graphframes:graphframes:jar:0.1.0-spark1.6 (provided), junit:junit:jar:4.12 (test), org.neo4j.test:neo4j-harness:jar:3.0.2 (test)]: Failed to read artifact descriptor for org.apache.lucene:lucene-core:jar:5.5.0: Could not transfer artifact org.apache.lucene:lucene-solr-grandparent:pom:5.5.0 from/to central (http://repo.maven.apache.org/maven2): Read timed out -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by Mageswaran1989** [comment]
I am following below stackoverflow question to setup maven artifact for the connector. While doing so I got stuck with this build error.
http://stackoverflow.com/questions/14013644/hosting-a-maven-repository-on-github

**Comment by jexp** [comment]
The connector is on the github repo of spark-packages, no need to build your own.

https://spark-packages.org/package/neo4j-contrib/neo4j-spark-connector
-> http://dl.bintray.com/spark-packages/maven/neo4j-contrib/neo4j-spark-connector/1.0.0-RC1/

and https://m2.neo4j.org/content/repositories/releases/org/neo4j/spark/

**Comment by jexp** [comment]
Just built it locally and it works, fine, looks like a network issue on your side:

```
[INFO] --- maven-install-plugin:2.4:install (default-install) @ neo4j-spark-connector_2.11 ---
[INFO] Installing /Users/mh/d/java/neo/neo4j-spark-connector/target/neo4j-spark-connector_2.11-full-1.0-SNAPSHOT.jar to /Users/mh/.m2/repository/org/neo4j/spark/neo4j-spark-connector_2.11/1.0-SNAPSHOT/neo4j-spark-connector_2.11-1.0-SNAPSHOT.jar
[INFO] Installing /Users/mh/d/java/neo/neo4j-spark-connector/pom.xml to /Users/mh/.m2/repository/org/neo4j/spark/neo4j-spark-connector_2.11/1.0-SNAPSHOT/neo4j-spark-connector_2.11-1.0-SNAPSHOT.pom
[INFO] Installing /Users/mh/d/java/neo/neo4j-spark-connector/target/neo4j-spark-connector_2.11-1.0-SNAPSHOT-sources.jar to /Users/mh/.m2/repository/org/neo4j/spark/neo4j-spark-connector_2.11/1.0-SNAPSHOT/neo4j-spark-connector_2.11-1.0-SNAPSHOT-sources.jar
[INFO] Installing /Users/mh/d/java/neo/neo4j-spark-connector/target/neo4j-spark-connector_2.11-1.0-SNAPSHOT-javadoc.jar to /Users/mh/.m2/repository/org/neo4j/spark/neo4j-spark-connector_2.11/1.0-SNAPSHOT/neo4j-spark-connector_2.11-1.0-SNAPSHOT-javadoc.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 49.322 s
[INFO] Finished at: 2016-07-13T13:34:58+02:00
[INFO] Final Memory: 80M/995M
[INFO] ------------------------------------------------------------------------
```
