### ISSUE TITLE
Neo4jRowRDD/Neo4jDataFrame cannot handle complex data structure (Error: not serializable result)

### ISSUE THREAD

**Issue by sjishan** [neo4j-contrib/neo4j-spark-connector#40]
I run a query which returns result in a data structure as follows:

```
[
{"identity":539850,"labels":["WHITE"],"properties":{"provider":"abc","id":"123","timestamp":1500336625}},
{"identity":3705864,"labels":["WHITE"],"properties":{"provider":"abc","id":"456","timestamp":1500336625}},
{"identity":573686,"labels":["WHITE"],"properties":{"provider":"def","id":"678","timestamp":1496618498}}
]
```

Basically a list of maps and each key in the map can have different data type. The problem is Neo4jRowRDD cannot handle such complex data structure. Now this is also the case if I am making a query like _"match (n) return n"_ as it returns key-value pairs. I would like to know if there is any way this issue can be handled? For instance take the whole thing as string and then maybe convert the whole thing when in rdd?

**Comment by sjishan** [comment]
Here is the python code and result of my use case. 

Code:
```

#Input: A list of IDs
#Output: A dictionary of the subgraphs for each of the ID in the list

user_list = ['123', '456', '678']

def get_subgraphs(user_list):


  output_dict = {}
  with driver.session() as session:
    with session.begin_transaction() as tx:
      for user in user_list:
        for record in tx.run("MATCH (n) WHERE n.id = {d} CALL apoc.path.subgraphNodes(n, {}) YIELD node WITH n , collect(node) as nodes return nodes", d = user):
          output_dict[user] = record["nodes"]
  return output_dict   

```


Result:


>{
> '123': 
> [<Node id=384431 labels=set([u'WHITE']) properties={u'timestamp': 1500414423, u'id': '234', u'provider': u'abc'}>,
>   <Node id=354995 labels=set([u'WHITE']) properties={u'timestamp': 1500414423, u'id': '345', u'provider': u'abc'}>],
> 
>  '456': 
> [<Node id=451250 labels=set([u'WHITE']) properties={u'timestamp': 1500329866, u'id': '564', u'provider': u'abc'}>,
>   <Node id=485854 labels=set([u'WHITE']) properties={u'timestamp': 1500412487, u'id': '556', u'provider': u'abc'}>,
>   <Node id=2925207 labels=set([u'WHITE']) properties={u'timestamp': 1500412487, u'id': '778', u'provider': u'abc'}>],
> 
>  '678': 
> [<Node id=539850 labels=set([u'WHITE']) properties={u'timestamp': 1500336625, u'id': '567'', u'provider': u'abc'}>,
>   <Node id=3705864 labels=set([u'WHITE']) properties={u'timestamp': 1500336625, u'id': '887', u'provider': u'abc'}>,
>   <Node id=573686 labels=set([u'WHITE']) properties={u'timestamp': 1496618498, u'id': '333', u'provider': u'abc'}>]
> }


Issue:
1. I am trying to use dataframe instead of list as input.
2. Output as rdd/dataframe.

**Comment by sjishan** [comment]
Solution:

This was the original query code:
`MATCH (n) WHERE n.id = 'some id' CALL apoc.path.subgraphNodes(n, {}) YIELD node WITH n , collect(node) as nodes return nodes`

Solution:
```
val query = "MATCH (n) WHERE n.id = 'some id' CALL apoc.path.subgraphNodes(n, {}) YIELD node WITH n , node.id  as returnid, node.timestamp as timestamp, n.id as queryid return returnid, queryid, timestamp"

val result = neo.cypher(query).batch(25).loadDataFrame
```

**Comment by conker84** [comment]
I'm closing this because it's more than 1yr old feel free to reopen in case the issue is not solved
