### ISSUE TITLE
Neo4j Session object leaked for Cypher Query

### ISSUE THREAD

**Issue by RoseFlunder** [neo4j-contrib/neo4j-spark-connector#42]
Hello,

I am using the neo4j-spark-connector with a local in memory spark instance without hadoop.
When retrieving data with a cyper query, I get the error "Neo4j Session object leaked...".

My environment:
OS: Windows 10 x64
Java: Oracle Java 1.8.0_141
Spark version: 2.2.0 (scala 2.11) and using the Java API
Neo4J version: 3.2.3
Neo4J Spark connector version: 2.0.0-M2

EDIT: Maybe its already fixed, but there is no new version on maven central yet?
Seems like there are some commits after the 2.0.0-M2 release which address this problem?

Code snippet:
```
SparkConf sparkConf = new SparkConf().setAppName("SOME APP NAME").setMaster("local[4]")
				.set("spark.neo4j.bolt.user", user).set("spark.neo4j.bolt.password", password)
				.set("spark.neo4j.bolt.url", boltUrl);
SparkSession spark = SparkSession.builder().config(sparkConf).getOrCreate();
Dataset<Row> dataset = new Neo4j(spark.sparkContext())
				.cypher("MATCH p=(a)-[r:Bestellposition]->(b) RETURN a.id as BESTELLUNG, b.Artikelnummer as ARTIKELNR", new HashMap<>())
				.loadDataFrame();
```

Here is the log:
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
17/08/15 13:30:31 INFO SparkContext: Running Spark version 2.2.0
17/08/15 13:30:31 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
17/08/15 13:30:31 ERROR Shell: Failed to locate the winutils binary in the hadoop binary path
17/08/15 13:30:31 INFO SparkContext: Submitted application: SOME APP NAME
17/08/15 13:30:31 INFO SecurityManager: Changing view acls to: Stephan
17/08/15 13:30:31 INFO SecurityManager: Changing modify acls to: Stephan
17/08/15 13:30:31 INFO SecurityManager: Changing view acls groups to: 
17/08/15 13:30:31 INFO SecurityManager: Changing modify acls groups to: 
17/08/15 13:30:31 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(Stephan); groups with view permissions: Set(); users  with modify permissions: Set(Stephan); groups with modify permissions: Set()
17/08/15 13:30:32 INFO Utils: Successfully started service 'sparkDriver' on port 53844.
17/08/15 13:30:32 INFO SparkEnv: Registering MapOutputTracker
17/08/15 13:30:32 INFO SparkEnv: Registering BlockManagerMaster
17/08/15 13:30:32 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
17/08/15 13:30:32 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
17/08/15 13:30:32 INFO DiskBlockManager: Created local directory at C:\Users\Stephan\AppData\Local\Temp\blockmgr-60bdf0ed-00bc-4ce7-905c-baae18d476e1
17/08/15 13:30:32 INFO MemoryStore: MemoryStore started with capacity 2000.4 MB
17/08/15 13:30:32 INFO SparkEnv: Registering OutputCommitCoordinator
17/08/15 13:30:32 INFO Utils: Successfully started service 'SparkUI' on port 4040.
17/08/15 13:30:32 INFO SparkUI: Bound SparkUI to 0.0.0.0, and started at http://192.168.178.30:4040
17/08/15 13:30:32 INFO Executor: Starting executor ID driver on host localhost
17/08/15 13:30:32 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 53865.
17/08/15 13:30:32 INFO NettyBlockTransferService: Server created on 192.168.178.30:53865
17/08/15 13:30:32 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
17/08/15 13:30:32 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 192.168.178.30, 53865, None)
17/08/15 13:30:32 INFO BlockManagerMasterEndpoint: Registering block manager 192.168.178.30:53865 with 2000.4 MB RAM, BlockManagerId(driver, 192.168.178.30, 53865, None)
17/08/15 13:30:32 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 192.168.178.30, 53865, None)
17/08/15 13:30:32 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 192.168.178.30, 53865, None)
17/08/15 13:30:32 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir ('file:/C:/Development/Datenbanken_Praktikum_Master/spark/spark-warehouse/').
17/08/15 13:30:32 INFO SharedState: Warehouse path is 'file:/C:/Development/Datenbanken_Praktikum_Master/spark/spark-warehouse/'.
17/08/15 13:30:32 INFO StateStoreCoordinatorRef: Registered StateStoreCoordinator endpoint
17/08/15 13:30:33 INFO SparkContext: Starting job: first at Neo4j.scala:280
17/08/15 13:30:33 INFO DAGScheduler: Got job 0 (first at Neo4j.scala:280) with 1 output partitions
17/08/15 13:30:33 INFO DAGScheduler: Final stage: ResultStage 0 (first at Neo4j.scala:280)
17/08/15 13:30:33 INFO DAGScheduler: Parents of final stage: List()
17/08/15 13:30:33 INFO DAGScheduler: Missing parents: List()
17/08/15 13:30:33 INFO DAGScheduler: Submitting ResultStage 0 (Neo4jRDD partitions Partitions(1,9223372036854775807,9223372036854775807,None) MATCH p=(a)-[r:Bestellposition]->(b) RETURN a.id as BESTELLUNG, b.Artikelnummer as ARTIKELNR using Map()), which has no missing parents
17/08/15 13:30:33 INFO MemoryStore: Block broadcast_0 stored as values in memory (estimated size 1816.0 B, free 2000.4 MB)
17/08/15 13:30:33 INFO MemoryStore: Block broadcast_0_piece0 stored as bytes in memory (estimated size 1298.0 B, free 2000.4 MB)
17/08/15 13:30:33 INFO BlockManagerInfo: Added broadcast_0_piece0 in memory on 192.168.178.30:53865 (size: 1298.0 B, free: 2000.4 MB)
17/08/15 13:30:33 INFO SparkContext: Created broadcast 0 from broadcast at DAGScheduler.scala:1006
17/08/15 13:30:33 INFO DAGScheduler: Submitting 1 missing tasks from ResultStage 0 (Neo4jRDD partitions Partitions(1,9223372036854775807,9223372036854775807,None) MATCH p=(a)-[r:Bestellposition]->(b) RETURN a.id as BESTELLUNG, b.Artikelnummer as ARTIKELNR using Map()) (first 15 tasks are for partitions Vector(0))
17/08/15 13:30:33 INFO TaskSchedulerImpl: Adding task set 0.0 with 1 tasks
17/08/15 13:30:33 INFO TaskSetManager: Starting task 0.0 in stage 0.0 (TID 0, localhost, executor driver, partition 0, PROCESS_LOCAL, 4863 bytes)
17/08/15 13:30:33 INFO Executor: Running task 0.0 in stage 0.0 (TID 0)
17/08/15 13:30:33 INFO Executor: Finished task 0.0 in stage 0.0 (TID 0). 1840 bytes result sent to driver
17/08/15 13:30:33 INFO TaskSetManager: Finished task 0.0 in stage 0.0 (TID 0) in 472 ms on localhost (executor driver) (1/1)
17/08/15 13:30:33 INFO TaskSchedulerImpl: Removed TaskSet 0.0, whose tasks have all completed, from pool 
17/08/15 13:30:33 INFO DAGScheduler: ResultStage 0 (first at Neo4j.scala:280) finished in 0,483 s
17/08/15 13:30:33 INFO DAGScheduler: Job 0 finished: first at Neo4j.scala:280, took 0,613730 s
**17/08/15 13:30:33 ERROR session: Neo4j Session object leaked, please ensure that your application calls the `close` method on Sessions before disposing of the objects.**
17/08/15 13:30:33 INFO BlockManagerInfo: Removed broadcast_0_piece0 on 192.168.178.30:53865 in memory (size: 1298.0 B, free: 2000.4 MB)
17/08/15 13:30:34 INFO SparkContext: Invoking stop() from shutdown hook
17/08/15 13:30:34 INFO SparkUI: Stopped Spark web UI at http://192.168.178.30:4040
17/08/15 13:30:34 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
17/08/15 13:30:34 INFO MemoryStore: MemoryStore cleared
17/08/15 13:30:34 INFO BlockManager: BlockManager stopped
17/08/15 13:30:34 INFO BlockManagerMaster: BlockManagerMaster stopped
17/08/15 13:30:34 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
17/08/15 13:30:34 INFO SparkContext: Successfully stopped SparkContext

**Comment by conker84** [comment]
I'm closing this because it's more than 1yr old feel free to reopen in case the issue is not solved
