### ISSUE TITLE
Multiple Relationships can build with in the same data frame ? Like Relationship array, source array keys, source node array props..is that possible ?

### ISSUE THREAD

**Issue by surendrameda** [neo4j-contrib/neo4j-spark-connector#422]
## Guidelines

Please note that GitHub issues are only meant for bug reports/feature requests. If you have questions on how to use the Neo4j Connector for Apache Spark,
please ask on [the Neo4j Discussion Forum](https://community.neo4j.com/c/integrations/18) instead of creating an issue here.

## Feature description (Mandatory)
A clear and concise description of what you want to happen. Add any considered drawbacks.

## Considered alternatives
A clear and concise description of any alternative solutions or features you've considered. Maybe there is something in the project that could be reused?

## How this feature can improve the project?
If you can, explain how users will be able to use this and possibly write out a version the docs.
Maybe a screenshot or design?

**Comment by conker84** [comment]
Please don't use the title for describing the problem, I had a hard time looking for where the description of the issue was.

The answer to your question is yes, you have to use a custom cypher query like described in the documentation:
https://neo4j.com/docs/spark/current/writing/#write-query

**Comment by lvijnck** [comment]
Dropping this here, incase someone hits the same issue. Image trying to add a Dataframe representing nodes with various labels, i.e., the label is present in the `label` column of the dataframe. The following query will ingest this correctly:

```
MERGE (n {id: event.id, name: event.name}) 
WITH event, n
CALL apoc.create.addLabels(n, [event.label])
YIELD node
RETURN node
```

(make sure the apoc plugin is enabled).
