### ISSUE TITLE
how can i select another db but not the default neo4j database in Enterprise Edition

### ISSUE THREAD

**Issue by Nevernamed** [neo4j-contrib/neo4j-spark-connector#446]
- Spark:3.1.1
- Scala:1.2
- Neo4j:4.1
- Neo4j Connector:4.5

df = spark.readStream \
    .format("org.neo4j.spark.DataSource") \
    .option("url", "neo4j://IP:7687") \
    .option("labels", "Person") \
    .load()

it's error when i add
 .option("database", "studentdb") \

**Comment by conker84** [comment]
Which error?
Can you share the full name of the neo4j connector?

**Comment by Nevernamed** [comment]
> Which error? Can you share the full name of the neo4j connector?

neo4j-connector-apach-spark_2.12-4.1.5_for_spark_3.jar

`df = spark.read.format("org.neo4j.spark.DataSource")
    .option("url","")
    .option("auth~username","")
    .option("auth~password","")
    .option("database","studentdb")
    .option("labels","studengs")
    .load()

df.show()
`
it's empty
is it not support other neo4j database, only default neo4j?

**Comment by Nevernamed** [comment]
> Which error? Can you share the full name of the neo4j connector?

neo4j-connector-apach-spark_2.12-4.1.5_for_spark_3.jar

`df = spark.read.format("org.neo4j.spark.DataSource")
    .option("url","")
    .option("auth~username","")
    .option("auth~password","")
    .option("database","studentdb")
    .option("labels","studengs")
    .load()

df.show()
`
it's empty
is it not support other neo4j database, only default neo4j?

**Comment by conker84** [comment]
Sorry but if you don’t attach the stacktrace I cannot understand what is
the problem.

Il giorno ven 16 set 2022 alle 18:45 Kerwin Chou ***@***.***>
ha scritto:

**Comment by conker84** [comment]
Closing for lack of feedback. Feel free to open in case of new info
