### ISSUE TITLE
Deleting nodes and/or relationships via the connector

### ISSUE THREAD

**Issue by N13T** [neo4j-contrib/neo4j-spark-connector#447]
Hi team, can someone share if there's any best practice on how to do large deletes of nodes/relationships via the connector?

Currently we got this to work but its very slow, we manage to delete only around 7k nodes in a minute. 
```
cypher_query = """
               MATCH (n:Person {perID: event.per_id})
               DETACH DELETE n
               """
(df.select("per_id").write.format("org.neo4j.spark.DataSource")\
     .option("database", neo4j_database)
     .option("query", cypher_query)
     .option("batch.size", "5000")
     .option("transaction.retries", 3)
     .option("transaction.retry.timeout", 1000)
     .mode("Append")
     .save())
```

**Comment by conker84** [comment]
@N13T Did you defined constraints on `Person.perID`?

**Comment by conker84** [comment]
Closing for lack of feedback. Feel free to reopen in case you have more info
