### ISSUE TITLE
Issue : Specifying the id field mappings between a relationship data frame and a node data frame

### ISSUE THREAD

**Issue by ThatDaveStevens** [neo4j-contrib/neo4j-spark-connector#451]
## Expected Behaviour (Mandatory)
Loading a data frame from a parquet file of Node data, and push that data frame to Neo4J – it works fine, with the column names being preserved (including colons) as property names on the Nodes.
 
But we run into an issue when we attempt to load relationship data, where we need to specify the mapping between the columns in the relationship data frame and the associated columns in the node data.

## Actual Behaviour (Mandatory)
Problem appears to be parsing the value of these options;
 
 ~~~
"relationship.source.node.keys", "who:name",
"relationship.target.node.keys", "where:addressId",
 ~~~
 
Which both use a colon as a delimiter between relationship column name an

### Steps (Mandatory)

1.
1.
1.

## Specifications

Currently used versions

### Versions
- Spark                     3.3.0
- Scala                      (n/a - we use Java 17)
- Neo4J Server     4.4.8

Library Dependency Versions (per Maven pom)
- spark-core_2.13                                               3.3.0
- spark-sql_2.13                                                   3.3.0
- neo4j                                                                    4.4.9
- neo4j-connector-apache-spark_2.13       4.1.5_for_spark_3
- scala-library                                                        2.13.9

**Comment by conker84** [comment]
@EnglishSid could you please try with version `5.2.0` it should be fixed.
Feel free to reopen it in case you have new info to share
