### ISSUE TITLE
Update Spark v5 documentation for Neo4j v5

### ISSUE THREAD

**Issue by davidoliverSP2** [neo4j-contrib/neo4j-spark-connector#459]
Please could the Spark v5 docs be updated to mirror changes and features in Neo4j v5.

For example, 
* Causal Clustering has been replaced by autonomous clusters - the [Using with Neo4j Causal Cluster](https://neo4j.com/docs/spark/current/neo4j-cluster/) section, and all other places where "Causal Clustering" appears need to be updated to remove reference of Causal Clusters.
* The [Compatibility section](https://neo4j.com/docs/spark/current/overview/#_compatibility) should be updated to reference support for Neo4j v5.

**Comment by fbiville** [comment]
Thanks @davidoliverSP2, I've already included a reference to Neo4j 5 in #460.
I'll see what I can with the causal cluster section. Shall it just mention "cluster" then?

**Comment by davidoliverSP2** [comment]
Thanks @fbiville - yes, possibly, but the correct reference is now "autonomous cluster", and it may depend on the context in which it's used. Please could you reach out to @AlexicaWright, and she'll be able to help!

**Comment by fbiville** [comment]
Since docs have been massively hauled, I think we're good here.
