### ISSUE TITLE
 After “neo.saveGraph()” execution, node duplication is found

### ISSUE THREAD

**Issue by allen-bigdata** [neo4j-contrib/neo4j-spark-connector#46]
//
    val vertexRDD:RDD[(VertexId,String)] = sc.parallelize(vertexArray)
    val edgeRDD:RDD[Edge[Int]] = sc.parallelize(edgeArray)

    // 
     val graph: Graph[String, Int] = Graph(vertexRDD, edgeRDD)

    graph.vertices.foreach(println)
    graph.edges.foreach(println)

    val neo = Neo4j(sc)
    println(graph.vertices.first())

    var tuples: List[NameProp] = List()
    tuples = tuples.+:(new NameProp(("guanxi","name")))
    val pattern: Pattern = Pattern(new NameProp(("test","id")),tuples,new NameProp(("test","id")))
   // neo.saveGraph(graph, "rank",pattern, merge = true)

result：
![image](https://user-images.githubusercontent.com/7122385/31933044-90bba65e-b8da-11e7-93a3-548db8a7f4bd.png)

**Comment by ysule** [comment]
hi @thbqlf ,
You can solve the issue of duplicate nodes by creating unique IDs for each of them,
One way would be to generate md5 hash values for a combination of columns.

**Comment by ysule** [comment]
On another note could you tell me where does the graph get stored. By this I mean which Database.

    val (vertices, edges): (DataFrame, DataFrame) =
      getGraphData(data, pairs, conf)
    /*Stuck at the writing Stage*/
    val graphFramePair: GraphFrame = GraphFrame(vertices, edges)
    val frameToGraphx = graphFramePair.toGraphX
    neoEntry.saveGraph(frameToGraphx, "Test")

I am trying to save the graph with the above code. I have followed the tutorial for the saveGraph() api. 
In the above code is the string *"Test"* the target database directory?
I would appreciate the help

**Comment by conker84** [comment]
I'm closing this because it's more than 1yr old feel free to reopen in case the issue is not solved
