### ISSUE TITLE
Write large dataset from Hive to neo4j via neo4j-spark connect api Neo4jDataFrame.mergeEdgeList in cluster is super slow. 

### ISSUE THREAD

**Issue by RayTsui** [neo4j-contrib/neo4j-spark-connector#49]
When I ran the following code:
Neo4jDataFrame.mergeEdgeList(sc, df, ("ACCOUNT",Seq("acct_no")), ("SHARE_EMAIL", Seq(“share_no”)),(“EMAIL", Seq(“email”))), in which df has 190000+ records, the cluster spark log presents 
228.151: [CMS-concurrent-reset: 0.006/0.006 secs] [Times: user=0.01 sys=0.00, real=0.00 secs]
[Stage 4:>                                                         (0 + 4) / 19]
 
That is almost there and it does not move to next step. Is there any improvements of api mergeEdgeList improvement or suggestions of how to achieve that?

**Comment by wzqaustin** [comment]
We encountered the same problem when loading 360w+ records to neo4j。After check the server  thread stack，several 'neo4j.Session-xxx' threads always using almost 100% CPU。

not find the solution yet.

**Comment by KristinaPlazonic** [comment]
the queries ran much faster for me if I created indices in advance in Neo4j directly, and superslow if I didn't. I don't know how to create index from Spark though. I did it in Neo4j browser.

**Comment by RayTsui** [comment]
that is right, the index or constraint are created beforehand in neo4j server manually and then using spark to import data. Currently, as much as I know, you can try to use the neo4j native java api to achieve that.

**Comment by GreGGus** [comment]
@KristinaPlazonic @RayTsui 

Did you succed with large dataset ? I have like 200k+ node and I have to deal with this error : 

Caused by: org.neo4j.driver.v1.exceptions.TransientException: LockClient[565] can't wait on resource RWLock[NODE(45464), hash=1502017791] since => LockClient[565] <-[:HELD_BY]- RWLock[NODE(2976), hash=1046700343] <-[:WAITING_FOR]- LockClient[564] <-[:HELD_BY]- RWLock[NODE(45464), hash=1502017791]


Thanks for help.

**Comment by RayTsui** [comment]
Yeah, I succeeded. neo4j has this limitation that you can not write the same part of nodes by parallel, otherwise it will incur this exceptions. However, according to the official docs, when you have this exception, you just try to execute your same code block that causes this exception. 

At same time, you can use some mechanism to ask your code to detect this exception and then re-execute this block of code until you succeed to write data.

Hope this can help.

**Comment by jexp** [comment]
Thanks a lot for helping each other!
And sorry for not following up earlier, I plan to update some of the driver usage, so I hope those retries will happen automatically in the future.

Does any of you by chance know the plans at databricks about graphframes?

**Comment by RayTsui** [comment]
Since last time short talk with databricks guys, they mainly pay much more attention on business platform, and relatively less effort on community development. However, I am sure the graphframe will integrate into one of the components in the future, though it's as third-party package. The reason is that DataFrame optimization like catalyst and tunsgen is still on progress.

**Comment by GreGGus** [comment]
@RayTsui Thanks a lot.

I'm on standalone Spark & neo4j docker for dev.

I just had to use partition(1) with index created before and it's working.

When I'll distribute this, I'll try your execption mechanism even if I have no idea how restart fail row.

Anyway, I'll keep you in touch :)
