### ISSUE TITLE
very slow writing of data

### ISSUE THREAD

**Issue by polyglot-v** [neo4j-contrib/neo4j-spark-connector#491]
I have used the following code to write a spark data frame with 35,452,611 distinct rows on 08/04/2022 and it took 1.61 minutes.

```python
(df_person.write
  .format("org.neo4j.spark.DataSource")
  .mode('Append')
  .option("url", "bolt://xxx.xx.xx.xx:xxxx")
  .option("authentication.basic.username", "xxxxx")
  .option("authentication.basic.password", "xxxxxxxxxx")
  .option("database", "graph")
  .option("labels", ":Person")
  .save())
```

I had to recreate the spark cluster and also the neo4j installation.  
I am running the exact above code, now with 179,704,788 distinct rows and it's taking 37.51 minutes.

I am using:
(I) neo4j 4.4.9
(ii) Databricks Runtime Version: 11.3 LTS (includes Apache Spark 3.3.0, Scala 2.12)
(ii) neo4j-connector-apache-spark_2.12-5.0.1_for_spark_3.jar

**Comment by fbiville** [comment]
Did you use the same environment for the initial import of 35 million rows and the second one of 179 million rows?

**Comment by conker84** [comment]
@polyglot-v also did you define the constraint on Person?

**Comment by conker84** [comment]
Closing for lack of feedback. Feel free to reopen in case you have more info
