### ISSUE TITLE
saving GraphFrames or GraphX[VD,ED] to Neo4j

### ISSUE THREAD

**Issue by ysule** [neo4j-contrib/neo4j-spark-connector#50]
hi Jexp,
I have created a set of Vertex and Edge DataFrames in my Spark code. I want to save these in my Neo4j database, but the example of savegraph() method is not very clear. Could you tell me how to pass GraphFrames to the function and which database does it store to since there is no mention of the database name.

**Comment by ysule** [comment]
I have achieved the GraphFrame creation but I still lack knowledge as to where is this Graph being Stored.
Kindly provide some clarity on the same

**Comment by jexp** [comment]
It stores it in the database that is indicated by your bolt connection.

I haven't gotten around to implement saving of graph frames :(

Currently saving of DataFrames and GraphX graphs are supported.

You can also have a look at the code of `Neo4jGraph.saveGraph` or `Neo4jDataFrame.mergeEdgeList`

**Comment by ysule** [comment]
hi jexp, Following is the code snippet in my writeToNeo4j function. I am converting my *GraphFrames* to *GraphX* Graph. The code runs to the point of creating the *GraphX Graph*, but no graph is being populated in Neo4j. My bolt URL, username and Password are checked and they are not the issue.
    
    val neoEntry: Neo4j = Neo4j(sparkcontext)
    val (vertices, edges): (DataFrame, DataFrame) =
    getGraphData(data, pairs, conf)

    /*Stuck at the writing Stage*/

    val graphFramePair: GraphFrame = GraphFrame(vertices, edges)  
    val frameToGraphx = graphFramePair.toGraphX
    neoEntry.saveGraph(frameToGraphx, "Test")

Could you sugget something?

**Comment by mitakshgupta** [comment]
@ysule - Were you able to solve this? Also, are you aware if it is possible to save graphframes to neo4j?

**Comment by ysule** [comment]
@mitakshgupta Sorry  I reverted to create CSV files of the data and then loading them via the commandline data load utility of Neo4j. I am planning to test the connector once again, If i can achieve the same via code, i'll push the code to my git

**Comment by mitakshgupta** [comment]
Thanks @ysule 
Please do let me know.
