### ISSUE TITLE
saveGraph API

### ISSUE THREAD

**Issue by ysule** [neo4j-contrib/neo4j-spark-connector#52]
hi jexp,
Could you tell me what exactly  "PATTERN" used for in Neo4j saveGraph method.
is it an absolute requirement to call the function with this Parameter.
I am getting a java NullPointerException when I try to save a graph without this parameter in the method.

**Comment by KristinaPlazonic** [comment]
Hi, 
I also would really appreciate some examples of how to use saveGraph API. I have a Spark dataframe with the following columns: pmid, title, journal, pub_date and would like to save this dataframe as nodes in Neo. 

I construct a spark graph of type org.apache.spark.graphx.Graph[MyNode,Long] where MyNode is: 
case class MyNode(val pmid:Long, val title:String, val pub_date:String, val journal:String)
with that many nodes and 0 edges. I now don't know how to save this graph in Neo. 

I tried 
Neo4jGraph.saveGraph(sc, graph, merge = false, nodeProp = "pmid")
but of course I get an error like: 
Caused by: org.neo4j.driver.v1.exceptions.ClientException: Unable to convert MyNode to Neo4j Value.

Any help would be appreciated! Thanks!

**Comment by KristinaPlazonic** [comment]
So, it seems that you can only set a single property of a node at a time using saveGraph API? 

this worked for me - but was extremely slow (doing on 18K records)

```
case class MyNode(val pmid:Long, val title:String, val pub_date:String, val journal:String)

val nodes = nodesdf.selectExpr("cast(pmid AS LONG) AS pmid", "title", "pub_date", "journal")
val nodes2 = nodes.as[MyNode]  // this is now a Dataset[MyNode]
val edges = Seq.empty[(Long, Long, Long)].toDF("srcId", "dstId", "attr")


val nodesrdd = nodes2.map( x => (x.pmid, x)).rdd                     // nodes need to be RDD[(VertexID, MyNode)]
val edgesrdd = edges.as[org.apache.spark.graphx.Edge[Long]].rdd         


// it seems that saveGraph only works with a single node property at a time. so will repeat this process for specially constructed graphs. 
val nodesrdd = nodes2.map( x => (x.pmid, x.pmid)).rdd                     // nodes need to be RDD[(VertexID, Long)]
val graph = Graph[Long,Long](nodesrdd, edgesrdd)
Neo4jGraph.saveGraph(sc, graph, merge = true, nodeProp = "pmid", mainLabelIdProp = Some("PubMed", "pmid"))

// for the following nodes we only set the properties
val nodesrdd = nodes2.map( x => (x.pmid, x.title)).rdd                     // nodes need to be RDD[(VertexID, String)]
val graph = Graph[String,Long](nodesrdd, edgesrdd)
Neo4jGraph.saveGraph(sc, graph, merge = false, nodeProp = "title", mainLabelIdProp = Some("PubMed", "pmid"))

val nodesrdd = nodes2.map( x => (x.pmid, x.journal)).rdd                     
val graph = Graph[String,Long](nodesrdd, edgesrdd)
Neo4jGraph.saveGraph(sc, graph, merge = false, nodeProp = "journal", mainLabelIdProp = Some("PubMed", "pmid"))

val nodesrdd = nodes2.map( x => (x.pmid, x.pub_date)).rdd                  
val graph = Graph[String,Long](nodesrdd, edgesrdd)
Neo4jGraph.saveGraph(sc, graph, merge = false, nodeProp = "pub_date", mainLabelIdProp = Some("PubMed", "pmid"))
```

**Comment by KristinaPlazonic** [comment]
I should add here that of course saving additional node properties ran much faster when I created an index with "CREATE INDEX ON :PubMed(pmid)" in Neo4j. 

Is there already an option to run such a command from Spark?

**Comment by GreGGus** [comment]
@KristinaPlazonic  looking same command to create index.
And did you managed to avoid index lock exception during request ?

**Comment by analyticalpicasso** [comment]
Hi,

Is this functionality still not available? What is the optimal way to insert milti property graph?

**Comment by jexp** [comment]
Yes right now, it only allows for a single property, as it was mostly meant to be used with the results of algorithms that compute a result.

But that should be possible to change.

**Comment by JakobWyatt-VGW** [comment]
Is there any way to efficiently write the entire GraphX graph into Neo4j?
My workflow is that the entire graph database is erased and a new one constructed in Spark, which is then written to Neo4j.
Is this possible?

**Comment by jexp** [comment]
@JakobWyatt-VGW in principle yes, how big is your graph? 
I recommend to save about 1M nodes/rels per partition as creating the driver object within a spark job is quite expensive.
You should have the necessary constraints in place. And if possible partition your graphx graph into independent clusters each of which can be written in parallel without conflicting on concurrent writes.
/cc @conker84

**Comment by JakobWyatt-VGW** [comment]
Hi @jexp, thanks for the reply.
My graph has about 200 nodes and 80 000 000 relationships.
It's not clear on the documentation whether or not its possible to update multiple **relationship** properties at once using the graphX save method.
For now, I've been using the mergeEdgeList method - is this recommended, or does the graphX save method have that functionality?

Also, I may have found a bug within the mergeEdgeList method - I'll hopefully be able to submit a pull request / issue report tomorrow, and get some advice on the best way of fixing it (not sure if my current patch is the most idiomatic way of doing things.)
