### ISSUE TITLE
Transaction Retries using pyspark

### ISSUE THREAD

**Issue by daamgard** [neo4j-contrib/neo4j-spark-connector#530]
## Expected Behavior (Mandatory)

When setting the parameter "transaction.retries" in a write statement we expect that the driver will retry at least n times before triggering an exception. e.g.:

    df.write
    .format('org.neo4j.spark.DataSource')
    .option('url',url)
    [....]
    .option('transaction.retries', 8) #Number of retries
    .option('transaction.timeout', 8) #Timeout for each try
    .save()

## Actual Behavior (Mandatory)
However when I execute such statement I get the following error : 

    [....] 
    Caused by : org.apache.spark.SparkException : Job aborted due to stage failure : 
    Task 0 in stage 124.0 failed 4 times : org.neo4j.driver.exceptions.TransientException: 
    ForsetiClient(transactionId=14111, clientId=1472) can't acquire ExclusiveLock
    [....]

Shouldn't the exception be triggered if the task failed 8 times ?

## How to Reproduce the Problem
You will need a pretty large DataFrame (at least 50k relationships). Unfortunately I cannot share that with you. 

### Simple Dataset (where it's possible)

```
// Insert the output of the `df.show()` call
+---+-----+
| id|NodeSource|RelationPropertyA|RelationPropertyB|TargetNode|
+---+------------------+---------------------------+--------------------------+------------------+
|  1|  A|1.0|2.5|B|
|  2|  A|2.5|2.1|C|
|  3|  C|1.2|2.1|D|
[...]

```

### Steps (Mandatory)

1. Load a Dataframe from csv file
2. Build relationships
3. Write Nodes
4. Write relationships

## Specifications (Mandatory)

Currently used versions

### Versions

- Spark: 3.3.0
- Scala: /
- Neo4j: 5.8.0
- Neo4j Connector: 2.12-5.0.2_for_spark_4.jar

## Additional information

* did you define the constraints/indexes? 
Constraints are on NodeSource and TargetNode, they are unique by 'name'

**Comment by conker84** [comment]
Hi @daamgard there is a misunderstanding. 
There are two retry mechanisms:

1. The first one is inside the Neo4j Spark connector and is managed via `transaction.retries` and `transaction.timeout`
2. The second one is managed by Spark itself and it's configurable via `spark.task.maxFailures` (the default is 4, remember it)

This means that the Neo4j Spark connector will retry for n-times before delegating to the Spark retry mechanism. 

If you look into the logs you should see n-times the message `Matched Neo4j transient exception next retry is` which comes from the Neo4j Spark connector and then `Task 0 in stage 124.0 failed 4 times` (the 4-times comes from `spark.task.maxFailures`, remember?)

Feel free to reopen in case have more info.
