### ISSUE TITLE
Problem with datetime properties with null values

### ISSUE THREAD

**Issue by thiago-braga-gep** [neo4j-contrib/neo4j-spark-connector#531]
## Expected Behavior (Mandatory)

Create a dataframe based on the cypher query

## Actual Behavior (Mandatory)

Works fine on Databricks Runtime 9.1 LTS

Breaks on Databricks Runtime 12.2 LTS - Error Message->IOException: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Java 8 date/time type `java.time.ZonedDateTime` not supported by default: add Module "com.fasterxml.jackson.datatype:jackson-datatype-jsr310" to enable handling
Caused by: InvalidDefinitionException: Java 8 date/time type `java.time.ZonedDateTime` not supported by default: add Module "com.fasterxml.jackson.datatype:jackson-datatype-jsr310" to enable handling

## How to Reproduce the Problem

Use any cypher query that returns more than one datetime, like: datetime(o.submittedDate) as submittedDateABC, o.isOnboardingSubmitted as isOnboardingSubmitted, datetime(o.triggeredDate) as triggeredDateABC, datetime(o.sentBackDate) as sentBackDateABC, o.finalActionTakenUsername as finalActionTakenUsername, datetime(o.onboardingFinalActionTakenDate) as onboardingFinalActionTakenDate, o.statusid as statusId

## Specifications (Mandatory)

Currently used versions

### Versions

- Spark: 3.3.2
- Scala: 2.12.15
- Neo4j: 4.4.15
- Neo4j Connector: 5.0.1

## Additional information

 Spark Cloud provider: Databricks 12.2LTS (https://docs.databricks.com/release-notes/runtime/12.2.html)

**Comment by conker84** [comment]
@thiago-braga-gep we tried to reproduce the problem but we weren't able.
You said I'm quoting:

> Use any Cypher query that returns more than one datetime

So we used several queries in order to test it, one of them look like this. 
```scala
  def test531(): Unit = {
    ss.read.format(classOf[DataSource].getName)
      .option("url", SparkConnectorScalaSuiteIT.server.getBoltUrl)
      .option("query", "RETURN datetime('2022-06-14T10:02:28.192Z') AS old, datetime() AS now")
      .load()
      .show(false)
  }
```
And it provides the correct result:
```bash
+-----------------------+-----------------------+
|old                    |now                    |
+-----------------------+-----------------------+
|2022-06-14 12:02:28.192|2023-07-14 10:23:24.384|
+-----------------------+-----------------------+
 ```
So I guess that is something in your data.
Please provide a very minimal dataset (Cypher queries) that allows us to create a database that reproduces the problem.
Moreover, we need to understand the Databricks runtime configuration.
