### ISSUE TITLE
Run query on all nodes

### ISSUE THREAD

**Issue by AviAvni** [neo4j-contrib/neo4j-spark-connector#54]
can we get api that the session https://github.com/neo4j-contrib/neo4j-spark-connector/blob/master/src/main/scala/org/neo4j/spark/Neo4j.scala#L395
is in read mode so the queries that run can be splitted to run on all cluster nodes?

**Comment by NivTikolski** [comment]
hi Michael @jexp ,
you think someone can do it on the next version?

Thanks,
Niv.

**Comment by jexp** [comment]
The code is already in there, and released
https://github.com/neo4j-contrib/neo4j-spark-connector/releases/tag/2.2.1-M5

so you should be already able to use it.

**Comment by NivTikolski** [comment]
thanks! i will wait for the new version that support neo4j 3.4.5 and upgrade to it. thanks michael!
