### ISSUE TITLE
5.2.0 missing from maven?

### ISSUE THREAD

**Issue by Habitats** [neo4j-contrib/neo4j-spark-connector#553]
Hey,

I see 5.1.0 was released on maven the same day of the [github release](https://mvnrepository.com/artifact/org.neo4j/neo4j-connector-apache-spark) ([30th of Aug](https://github.com/neo4j-contrib/neo4j-spark-connector/releases)). Same of older releases. However, 5.2.0 is nowhere to be seen.

Apologies if I misunderstood how releases work!

**Comment by fbiville** [comment]
Thanks for the report, we're looking into it right now.

**Comment by fbiville** [comment]
The release has been fixed, the new version is now available: https://central.sonatype.com/artifact/org.neo4j/neo4j-connector-apache-spark_2.13.
Thanks again!
