### ISSUE TITLE
Neo4j connector is currently unusable to write data from Databricks with Unity Catalog enabled

### ISSUE THREAD

**Issue by riccardodelega** [neo4j-contrib/neo4j-spark-connector#556]
When trying to write from a Databricks cluster with Unity Catalog enabled to Neo4j, you get the following errors:

* Overwrite mode: `AnalysisException: [UC_COMMAND_NOT_SUPPORTED.WITHOUT_RECOMMENDATION] The command(s): OverwriteByExpression are not supported in Unity Catalog. ;`
* Append mode: `AnalysisException: [UC_COMMAND_NOT_SUPPORTED.WITHOUT_RECOMMENDATION] The command(s): AppendData are not supported in Unity Catalog. ;`

This happens with all of the methods described in the [documentation](https://neo4j.com/docs/spark/current/writing/).

**Comment by conker84** [comment]
@riccardodelega can you provide the full stack trace? It seems like the error is related to the Unity catalog itself rather than the spark connector.
As asked in the issue template we need a set of steps in order to reproduce the problem otherwise we cannot help

**Comment by conker84** [comment]
Closing for lack of feedback. Please feel free to reopen in case you have new info.
