### ISSUE TITLE
more documentation?

### ISSUE THREAD

**Issue by greghines** [neo4j-contrib/neo4j-spark-connector#57]
Spark graph frames and graph x do not seem to offer the ability to have node types. When you query a neo4j database (the only examples I see on the site are for ones with just one node type - Person),the resulting graph frame.vertex only has a list of the vertex ids (and value equal to null). I've tried playing around with stuff but some more documentation would be really appreciated - how are we supposed to keep node type (e..g movie vs. person) in Spark.

**Comment by F0bi** [comment]
I agree with this consideration.

**Comment by conker84** [comment]
I'm closing this because it's more than 1yr old feel free to reopen in case the issue is not solved
