### ISSUE TITLE
Single table without relations writes into Neo4j

### ISSUE THREAD

**Issue by roksolana-d** [neo4j-contrib/neo4j-spark-connector#58]
I have been trying to write data from Spark data frames into Neo4j tables. However, I have only found a possibility to do that using the _mergeEdgeList_ method, which performs quite slow on data frames with more than 100,000 rows. And this method creates 2 tables with relations. Is there a possibility to persist a single data frame as a table without any relations and add them in the future  (for example, directly in Neo4j)? Maybe, something like that will be in the next release?

**Comment by conker84** [comment]
I'm closing this because it's more than 1yr old feel free to reopen in case the issue is not solved
