### ISSUE TITLE
Create graph with mergeEdgeList : big dataset

### ISSUE THREAD

**Issue by GreGGus** [neo4j-contrib/neo4j-spark-connector#59]
-spark2.2
-neo4j 3.3
-Actually using spark on standAlone to dev. We'll be distribute later.

I'm using function  'mergeEdgeList'  to create graph into neo4j.

Everywthing is good, but I'm testing with more bigger dataset ( 200k ) and it's fail.

This is StackTrace : 

`Caused by: org.neo4j.driver.v1.exceptions.TransientException: LockClient[565] can't wait on resource RWLock[NODE(45464), hash=1502017791] since => LockClient[565] <-[:HELD_BY]- RWLock[NODE(2976), hash=1046700343] <-[:WAITING_FOR]- LockClient[564] <-[:HELD_BY]- RWLock[NODE(45464), hash=1502017791]
`

i'm using partitions number as  : 

`    val partitions = Math.max(1, (dataFrame.count() / 10000).asInstanceOf[Int]) // TODO : Index + check la repartition`

What happening ? Everything is running on Azure Ubuntu 16 with 32Go RAM.

Thanks.

**Comment by conker84** [comment]
I'm closing this because it's more than 1yr old feel free to reopen in case the issue is not solved

**Comment by hancong0601** [comment]
hi @GreGGus ,Does it work nice on distribute situation? I am using function 'mergeEdgeList' to insert dataframe into neo4j when spark running on standAlone, the result is process of insert is slowly. do you have some suggestion or spark running on distribute will get the speed insert what we want?
Thanks
