### ISSUE TITLE
Neo4j.rels return null (should return same LoadRowRdd as Neo4j.cypher)

### ISSUE THREAD

**Issue by Litchilitchy** [neo4j-contrib/neo4j-spark-connector#60]
The core issue is following
```
scala> val rowRDD = neo.rels("MATCH (n:uid) RETURN id(n) as name limit 10").loadRowRdd
rowRDD: org.apache.spark.rdd.RDD[org.apache.spark.sql.Row] = null
```
where `Neo4j.rels` returns `null`

--------------------detail-------------(╯‵□′)╯︵┻━┻
I am writing following pieces of codes
   ```
val neo = Neo4j(sc)
neo.cypher(queryString).loadRowRdd //line1
neo.rels(queryString).loadRowRdd //line2
```
I have read the source code and it seems that `Neo4j.cypher` set `.nodes` attribute and `Neo4j.rels` set `.rels` attribute and after running above code the 2 variables `neo.cypher.query` and `neo.rels.query` should both be `queryString`. 

The pieces of the source code is 
 ```
def loadNodeRdds : RDD[Row] = {
    if (pattern != null) {
      loadNodeRdds(pattern.source,nodes.params,partitions)
        .union(loadNodeRdds(pattern.target,nodes.params,partitions)).distinct()
    } else if (!nodes.isEmpty) {
       new Neo4jRDD(sc, nodes.query, nodes.params, partitions)
    } else if (!rels.isEmpty) {
       new Neo4jRDD(sc, rels.query, rels.params, partitions)
    } else {
       throw new RuntimeException("No relationship query provided either as pattern or with cypher() or nodes()")
    }
  }
```
Then since in line1, `neo.nodes` is not empty, which means it calls `new Neo4jRDD(sc, nodes.query, nodes.params, partitions)`
in line2, `neo.rels` is not empty, which means it calls `new Neo4jRDD(sc, rels.query, rels.params, partitions)`

However, `nodes.params` and `rels.params` are both empty and `nodes.query` and `rels.query` are the same, but line1 can run successfully and line2 have error

This error can not be retrieved in Jupyter, and in spark-shell, I found the problem, here is the log
```
scala> val rowRDD = neo.cypher("MATCH (n:uid) RETURN id(n) as name limit 10").loadRowRdd
rowRDD: org.apache.spark.rdd.RDD[org.apache.spark.sql.Row] = Neo4jRDD partitions Partitions(...)
scala> val rowRDD = neo.rels("MATCH (n:uid) RETURN id(n) as name limit 10").loadRowRdd
rowRDD: org.apache.spark.rdd.RDD[org.apache.spark.sql.Row] = null
```
when calling the `Neo4j.rels` function it returns `null`, that is strange, why? I am using version `2.0.0-M2`
, the same issue occurs when using the newest version `2.1.0-M4`

**Comment by tzungtzu** [comment]
same problem！

**Comment by wuxuec** [comment]
same issue as i met, still wondering

**Comment by Suguha** [comment]
Good question! If solved, tell me plz:)

**Comment by conker84** [comment]
I'm closing this because it's more than 1yr old feel free to reopen in case the issue is not solved
