### ISSUE TITLE
Is it possible to know on which record preparation of dataframe from neo4j data failed

### ISSUE THREAD

**Issue by Mahesha999** [neo4j-contrib/neo4j-spark-connector#62]
I was doing following:

 - fetching dataframe from neo4j using neo4j-spark-connector
 - fetching dataframe from hbase using apache hbase spark connector
 - printing both dataframe to console by `df.show()`
 - joining both data frames using spark sql using unique id column present in both dataframes:

        Dataset<Row> mergedData = ss.sql("SELECT * from hbasetable, neo4jtable WHERE hbasetable.nodeId = neo4jtable.id");
 - printing joined dataframe to console by `mergedData.show()`

This was working perfectly fine. However, now, I changed the cypher query using which I was fetching neo4j data. Earlier my cypher used to like this:

    Match (n:Type1 {caption:'type1caption"'})-[:contains]->(m:Type2) return m.attr1, m.attr2, m.attr3, m.attr4, m.attr5, m.attr6, m.attr7, m.attr8, m.id as id, m.attr9, m.attr10, m.attr11

Now its like this:

    Match (m:Type1) return m.attr1, m.attr2, m.attr3, m.attr4, m.attr5, m.attr6, m.attr7, m.attr8, m.id as id, m.attr9, m.attr10, m.attr11

But now the joining fails. It gives me following exception:

    Long is not a valid external type for schema of string

It seems that the contents of both new neo4j dataframe and hbase dataframe are getting correctly fetched as both `neo4jdf.show()` and `hbasedf.show()` shows data on console. I was wondering, if earlier join was working fine and if data is getting correctly fetched, then what can fail the join.

Main concern is that I am unable to interpret the stack trace printed on the console. It looks something like this:

    18/06/04 17:47:48 ERROR Executor: Exception in task 0.0 in stage 4.0 (TID 4)
    java.lang.RuntimeException: Error while encoding: java.lang.RuntimeException: java.lang.Long is not a valid external type for schema of string
    if (assertnotnull(input[0, org.apache.spark.sql.Row, true], top level row object).isNullAt) null else validateexternaltype(getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true], top level row object), 0, m.attr1), NullType) AS m.attr1#0
    +- if (assertnotnull(input[0, org.apache.spark.sql.Row, true], top level row object).isNullAt) null else validateexternaltype(getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true], top level row object), 0, m.attr1), NullType)
       :- assertnotnull(input[0, org.apache.spark.sql.Row, true], top level row object).isNullAt
       :  :- assertnotnull(input[0, org.apache.spark.sql.Row, true], top level row object)
       :  :  +- input[0, org.apache.spark.sql.Row, true]
       :  +- 0
       :- null
       +- validateexternaltype(getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true], top level row object), 0, m.attr1), NullType)
          +- getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true], top level row object), 0, m.attr1)
             +- assertnotnull(input[0, org.apache.spark.sql.Row, true], top level row object)
                +- input[0, org.apache.spark.sql.Row, true]

         :
         :
       lot of stack trace omitted
         :
         :
    if (assertnotnull(input[0, org.apache.spark.sql.Row, true], top level row object).isNullAt) null else staticinvoke(class org.apache.spark.unsafe.types.UTF8String, StringType, fromString, validateexternaltype(getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true], top level row object), 11, m.attr11), StringType), true) AS m.attr11#11
    +- if (assertnotnull(input[0, org.apache.spark.sql.Row, true], top level row object).isNullAt) null else staticinvoke(class org.apache.spark.unsafe.types.UTF8String, StringType, fromString, validateexternaltype(getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true], top level row object), 11, m.attr11), StringType), true)
       :- assertnotnull(input[0, org.apache.spark.sql.Row, true], top level row object).isNullAt
       :  :- assertnotnull(input[0, org.apache.spark.sql.Row, true], top level row object)
       :  :  +- input[0, org.apache.spark.sql.Row, true]
       :  +- 11
       :- null
       +- staticinvoke(class org.apache.spark.unsafe.types.UTF8String, StringType, fromString, validateexternaltype(getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true], top level row object), 11, m.attr11), StringType), true)
          +- validateexternaltype(getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true], top level row object), 11, m.attr11), StringType)
             +- getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true], top level row object), 11, m.attr11)
                +- assertnotnull(input[0, org.apache.spark.sql.Row, true], top level row object)
                   +- input[0, org.apache.spark.sql.Row, true]
    
    	at org.apache.spark.sql.catalyst.encoders.ExpressionEncoder.toRow(ExpressionEncoder.scala:279)
    	at org.apache.spark.sql.SparkSession$$anonfun$5.apply(SparkSession.scala:537)
    	at org.apache.spark.sql.SparkSession$$anonfun$5.apply(SparkSession.scala:537)
    	at scala.collection.Iterator$$anon$11.next(Iterator.scala:370)
    	at scala.collection.Iterator$$anon$11.next(Iterator.scala:370)
    	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.processNext(Unknown Source)
    	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
    	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$8$$anon$1.hasNext(WholeStageCodegenExec.scala:370)
    	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:369)
    	at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:147)
    	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:79)
    	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:47)
    	at org.apache.spark.scheduler.Task.run(Task.scala:85)
    	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:274)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    	at java.lang.Thread.run(Thread.java:745)
    Caused by: java.lang.RuntimeException: java.lang.Long is not a valid external type for schema of string
    	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection.apply(Unknown Source)
    	at org.apache.spark.sql.catalyst.encoders.ExpressionEncoder.toRow(ExpressionEncoder.scala:276)
    	... 16 more

The full stack trace can be found in [gist here](https://gist.github.com/Mahesha999/c284458d51141884fbff6f9415570d11)

I feel that this must be something related to inconsistency in neo4j data. If I can know the id of the neo4j node at which the exception is occurring I can check it. But I am absolutely not able to interpret this stacktrace. **Is it possible to force spark to show on which record the exception occurred while preparing dataframe?**

**Update**

I removed everything related to join and hbase and added `neo4jdf.show(24000,false);`, and its giving the same error as above. There are 23748 records. When I print small number of records (say `neo4jdf.show(1000)`) it prints them without error. But, when I allow printing 24000 records, it fails. It means something is wrong with some node. But how can I pin point it?

**Comment by conker84** [comment]
I'm closing this because it's more than 1yr old feel free to reopen in case the issue is not solved
