### ISSUE TITLE
Error on build

### ISSUE THREAD

**Issue by HADDADENICAR** [neo4j-contrib/neo4j-spark-connector#65]
when i tip `mvn clean package`, i get this error : 

     Failed to execute goal net.alchim31.maven:scala-maven-plugin:3.2.0:compile (scala-compile) on project  neo4j-spark-connector: Execution scala-compile of goal net.alchim31.maven:scala-maven- plugin:3.2.0:compile failed: For artifact {null:null:null:jar}: The groupId cannot be empty. -> [Help 1]

**Comment by jexp** [comment]
I never had that.

Do you really need to build yourself or could you pull it from releases / spark-packaages?

**Comment by HADDADENICAR** [comment]
i was  just following the read me.
My os is win10
