### ISSUE TITLE
result: org.neo4j.driver.internal.InternalNode Serialization stack

### ISSUE THREAD

**Issue by francliu** [neo4j-contrib/neo4j-spark-connector#66]
Exception in thread "main" org.apache.spark.SparkException: Job aborted due to stage failure: Task 0.0 in stage 0.0 (TID 0) had a not serializable result: org.neo4j.driver.internal.InternalNode
Serialization stack:
	- object not serializable (class: org.neo4j.driver.internal.InternalNode, value: node<6>)
	- writeObject data (class: java.util.HashMap)
	- object (class java.util.LinkedHashMap, {n=node<6>})
	- element of array (index: 0)
	- array (class [Ljava.util.Map;, size 1)

**Comment by jexp** [comment]
Please share the code you ran.

It's better not to return nodes from neo4j to pass them to another task, but just literal primitive values

**Comment by francliu** [comment]
private final static Logger log = LoggerFactory.getLogger(neo4j.class);
    public static final String QUERY = "MATCH (n:Person) RETURN n.born,n.name";//"MATCH (m:Movie {title:{title}}) RETURN m.released as released, m.tagline as tagline";
    public static final Map<String, Object> PARAMS = Collections.<String, Object>singletonMap("name", "张三");
    public static void main( String[] args )
    {
    	
    	/*if (args.length < 1) {
            System.err.println("Usage: JavaWordCount <file>");
            System.exit(1);
        }*/

        SparkConf sparkConf = new SparkConf().setAppName("neo4j-spark");
        JavaSparkContext ctx = new JavaSparkContext(sparkConf);
        

        log.info("start...");
        Neo4JavaSparkContext neoSpark = Neo4JavaSparkContext.neo4jContext(ctx);
        log.info("neoSpark created success...");
        
        JavaRDD<Row> lines = neoSpark.queryRow(QUERY, null);
        log.info("neo4j tranfer spark success...");

        //flatMap与map的区别是，对每个输入，flatMap会生成一个或多个的输出，而map只是生成单一的输出
        //用空格分割各个单词,输入一行,输出多个对象,所以用flatMap
        log.info("neo4j map spark start...");
        JavaRDD<String> res = lines.map(new Function<Row, String>() {
			private static final long serialVersionUID = -8485357784693311513L;

			@Override
			public String call(Row doc) throws Exception {	
				StringBuilder res = new StringBuilder();
				for(int i = 0;i < doc.size();i++){
					res.append("第"+i+"个:");
					String s = doc.get(i) == null ? "" :doc.get(i).toString();
					res.append(s);
				}
				log.info(res.toString());
				return res.toString();
			}
		});

        log.info("neo4j map spark success...");
        
        List<String> words = res.collect();
        log.info("spark excuctte success...");
        for(String r : words){
        	log.info(r);
        }
        ctx.stop();
      }

**Comment by francliu** [comment]
now It's works

**Comment by conker84** [comment]
I'm closing this because it's more than 1yr old feel free to reopen in case the issue is not solved
