### ISSUE TITLE
ServiceUnavailableException: Connection terminated while receiving data

### ISSUE THREAD

**Issue by pranaysahith** [neo4j-contrib/neo4j-spark-connector#67]
Hi,

I am getting below error while connecting to neo4j:

> org.neo4j.driver.v1.exceptions.ServiceUnavailableException: Connection terminated while receiving data

I have set url, username, password of neo4j in sparkConf as below, is it the right way to do?

```
val sparkConf = new SparkConf().setAppName("Test01").setMaster("local[4]")
				.set("spark.neo4j.bolt.user", user).set("spark.neo4j.bolt.password", password)
				.set("spark.neo4j.bolt.url", boltUrl);

```
Thanks

**Comment by conker84** [comment]
I'm closing this because it's more than 1yr old feel free to reopen in case the issue is not solved
