### ISSUE TITLE
package org.neo4j.graphdb.factory does not exist

### ISSUE THREAD

**Issue by HADDADENICAR** [neo4j-contrib/neo4j-spark-connector#68]
while running the `mvn test` i get this error:

       [ERROR] /C:/Users/Ahmed/Desktop/neo4j-spark-connector-master/src/test/java/org/neo4j/spark/Neo4jRDDTest.java:[9,33] package org.neo4j.graphdb.factory does not exist

**Comment by conker84** [comment]
I'm closing this because it's more than 1yr old feel free to reopen in case the issue is not solved
