### ISSUE TITLE
Writing to / deleting from DB issue

### ISSUE THREAD

**Issue by ishaanmadan19** [neo4j-contrib/neo4j-spark-connector#69]
I am having issues writing to my database using the connector. 

If I were to write actual cypher queries in Neo4j, for example create two simple nodes with: 
_CREATE (n:person)_

and then in my script write: 

  _val neo = Neo4j(sc)
  val rdd = neo.cypher("MATCH (n:person) RETURN id(n) as id ").loadRowRdd
  println(rdd.count)_

 I successfully get a printed value of 2. 

However, if I were to add the following to my script: 

_neo.cypher("CREATE (n:PERSON)")_

Nothing shows up in the db, but no errors are thrown. The same logic applies for deleting nodes. Does anyone have any suggestions about how to write creational Cypher queries directly from my Scala script?

**Comment by ishaanmadan19** [comment]
@jexp

**Comment by Alucardmini** [comment]
same problem @jexp

**Comment by conker84** [comment]
I'm closing this because it's more than 1yr old feel free to reopen in case the issue is not solved
