### ISSUE TITLE
Neo4jGraphFrame query failed to execute

### ISSUE THREAD

**Issue by arjundeshwal-innoplexus** [neo4j-contrib/neo4j-spark-connector#7]
In the function apply of Neo4jGraphFrame , edgeProp is taking r.${edge._2} as string.

      #val edgeProp = if (edge._2 == null) "" else ", r.${edge._2} as prop"

Instead it shoud be 

      val edgeProp = if (edge._2 == null) "" else s", r.${edge._2} as prop"

**Comment by jexp** [comment]
Fixed, thanks!
