### ISSUE TITLE
Multiple calls to neo4j connector not supported in a forEachPartition?

### ISSUE THREAD

**Issue by swayam18** [neo4j-contrib/neo4j-spark-connector#73]
I have a list of ids and I am trying to update their corresponding nodes on neo4j:

```scala
val sparkSession = SparSession.builder(...)
val data = sparkSession.read(...).repartition(150)
data.foreachPartition(rows => {
    val neo = Neo4j(sparkSession.sparkContext)
    val ids = rows.map(row => row.getString(0)).toArray // Array of ids to update

    val updatedData = neo.cypher(s"""
        | UNWIND {pks} as pk
        | MATCH (i:Media {pk: pk})
        | SET i:NotSynced
        | RETURN i.pk as pk
      """.stripMargin).param("pks", pks).loadDataFrame

    updatedData.show()
  })
```

It works fine for the first 4 partitions (I have 4 cores), and then it just hangs. The weird thing is that if I reduce the number of partitions (by removing the repartition call and running it on a much smaller data) the above code works with zero issues.

Any idea what I may be doing wrong?

**Comment by jexp** [comment]
Hmm good question which version do you use?
I recently changed neo4j.cypher to only run with read transactions.

**Comment by conker84** [comment]
I'm closing this because it's more than 1yr old feel free to reopen in case the issue is not solved
