### ISSUE TITLE
Neo4jDataFrame.mergeEdgeList can not write to neo4j with a:TypeA-[r:Rel]->b:TypeA data structure

### ISSUE THREAD

**Issue by zqz981** [neo4j-contrib/neo4j-spark-connector#76]
When I am trying to build a new relationship which links two objects with the same type, it fails to write to neo4j, unless you assign two objects with different column names.
For example,  I have a data frame which has three columns: Acct1, order_cnt, Acc2.  Acct1 and Acct2 are the same type Object which has one property "acct_no" for each element in the list.
when you write this dataframe into neo4j, you have to rename Acct1, Acct2 with different property names, otherwise, it fails to build the right connection graph.
`Neo4jDataFrame.mergeEdgeList(sc, df, ("Acct", Seq("from_acct_no")), ("ORDER_REL", Seq("order_cnt")), ("Acct", Seq("to_acct_no")))`

**Comment by MrTomerLevi** [comment]
this will be solved in https://github.com/neo4j-contrib/neo4j-spark-connector/pull/77

**Comment by zqz981** [comment]
Thank you  MrTomerLevi

**Comment by conker84** [comment]
I'm closing this because it's more than 1yr old feel free to reopen in case the issue is not solved
