### ISSUE TITLE
Does this support spark streaming?

### ISSUE THREAD

**Issue by swayam18** [neo4j-contrib/neo4j-spark-connector#78]
Bolt protocol has support for streaming data, so I am wondering, can we use this library to stream data from neo4j and use spark streaming to process it?

**Comment by jexp** [comment]
Good question, i try to use lazy iterators in all places so in theory it should not fetch data eagerly.

Do you have an example for a spark streaming call? How would it work with RDDs or dataFrames?

**Comment by kant111** [comment]
@jexp Since streaming is a micro-batch in spark it will be great if the connector can provide a way to incrementally construct the graph as Spark process every batch.
