### ISSUE TITLE
support neo4j 3.4.5?

### ISSUE THREAD

**Issue by NivTikolski** [neo4j-contrib/neo4j-spark-connector#80]
hi,
i just now tried to change my data processing query to work with the new datetime field of neo4j 3.4.5.
i got an error and then saw that the driver support only neo4j < 3.3.6 ?

you working on it? when it will be ready?

thanks,
niv.

**Comment by jexp** [comment]
Good point, I update the bolt-driver and also upgrade to spark 2.4

**Comment by NivTikolski** [comment]
@jexp  
hi michael, 
you know when it will be ready? 

Thanks,
Niv.

**Comment by jexp** [comment]
Hey I still have a few failing tests, but it would be great if you could test this jar:

https://www.dropbox.com/s/ovsg95a2cftai67/neo4j-spark-connector-full-2.4.0-M6.jar?dl=0

**Comment by jexp** [comment]
Fixed the last test, pushed the update, also to spark-packages.
Hope this works for you.

**Comment by NivTikolski** [comment]
thanks.
i will check it and will update you!

**Comment by NivTikolski** [comment]
@jexp 
it works! 

thanks,
Niv.
