### ISSUE TITLE
Cannot create nodes and relationships using Cypher queries using neo.cypher(...)

### ISSUE THREAD

**Issue by imaginesus** [neo4j-contrib/neo4j-spark-connector#82]
neo.cypher("match (n:Person), (m:Person) where id(n) = 491 and id(m)=634 create (n)-[r:KNOWS]->(m)") executes but no change in graph database. Please help.

**Comment by jexp** [comment]
Those are meant for reading data from neo4j, not writing that's why they are executed in read-transactions.

**Comment by Alucardmini** [comment]
hello when I use this code ``
val insert = "CREATE (c:Person {name:king}) return c"
neo.cypher(insert)
It's useless to create a Person node, What should I do if I want create a node use spark?

**Comment by Alucardmini** [comment]
@jexp

**Comment by Alucardmini** [comment]
hello when I use this code ``
val insert = "CREATE (c:Person {name:king}) return c"
neo.cypher(insert)
It's useless to create a Person node, What should I do if I want create a node use spark?  @jexp
