### ISSUE TITLE
Info: Proposal to bring Cypher into the Spark project

### ISSUE THREAD

**Issue by jexp** [neo4j-contrib/neo4j-spark-connector#83]
Xiangrui Meng of Databricks recently posted a [request for SPIP feedback](http://apache-spark-user-list.1001560.n3.nabble.com/SPIP-DataFrame-based-Property-Graphs-Cypher-Queries-and-Algorithms-td34358.html) on the Apache Spark project users list. The [SPIP (Spark Project Improvement Proposal)](https://docs.google.com/document/d/1ljqVsAh2wxTZS8XqwDQgRT6i_mania3ffYSYpEgLx9k/edit) proposes to bring Cypher queries into the core Spark project as part of Spark 3.0.

We would appreciate it if you could express your interest on the [SPIP mailing list thread](http://apache-spark-user-list.1001560.n3.nabble.com/SPIP-DataFrame-based-Property-Graphs-Cypher-Queries-and-Algorithms-td34358.html). Your comment would help the Spark community to better understand the need for working with property graphs and Cypher in Spark.

Thanks, the Cypher for Apache Spark engineering team

**Comment by jexp** [comment]
Because you used the neo4j-spark-connector this ^^^^ might be interesting to you too^.

@swayam18, @adamrabie, @analyticalpicasso, @annievic, @AviAvni, @codejoy, @F0bi, @fntneves, @francliu, @gchokeen, @GreGGus, @greghines, @HADDADENICAR, @ishaanmadan19, @Mahesha999, @Mazzjs, @PandaGongfu, @pranaysahith, @roksolana-d, @RoseFlunder, @sandys, @simonegabbriellini, @sjishan, @SummerLitchy, @thbqlf, @yashs360, @ysule, @zengxijin, @zqz981, @MrTomerLevi 

Cheers, Michael

**Comment by HADDADENICAR** [comment]
Yes we need Cypher on Spark , But there's already a project that  brings Cypher for Spark , it's [Cypher for Apache Spark](https://github.com/opencypher/cypher-for-apache-spark).
Maybe they need to integrate this project on spark instead of re-inventing a new one , But only after the team of  CAPS adds  graph algorithms to the project.
Any way , i have posted my use case in which i needed the Cypher on Spark during my final year project. ;)

**Comment by s1ck** [comment]
Hey @HADDADENICAR . Nice to see you again and thanks for your comments, both here and on the mailing list! The SPIP was written by us (the Cypher for Apache Spark engineers) in collaboration with Databricks engineers and actually proposes to bring a subset of Cypher for Apache Spark into the Spark project.
