### ISSUE TITLE
Does this support PySpark?

### ISSUE THREAD

**Issue by GuanYingChen** [neo4j-contrib/neo4j-spark-connector#86]
How can I connect Neo4j with PySpark?
Is there any example to demonstrate the use of **neo4j-spark-connector** with **PySpark**?
(I really want to integrate Neo4j with Pyspark graphframes...)

Thanks a lot!

**Comment by conker84** [comment]
I'm closing this because it's more than 1yr old feel free to reopen in case the issue is not solved
