### ISSUE TITLE
How to return an RDD[(Long, Long, String)] 

### ISSUE THREAD

**Issue by xixi-baba** [neo4j-contrib/neo4j-spark-connector#89]
I was trying to integrate this neo4j-spark-connector with another program module(named A for convenience), the entry of A is an RDD[(Long, Long, String)] , I tried to execute an query with three return values like this
`val graphQuery = "MATCH (s:DataNode)-[r:TO]->(e:DataNode) RETURN ID(s) as start, ID(e) as end, r.weight as weight "`
`val rdd = neo.cypher(graphQuery).loadRdd[(Long, Long, String)]`
But it seems the function loadRdd can only receive one cypher result as an RDD, I also tried to use load RowRDD, but it is not compatible with the module A
Is there any way to create an RDD[(Long，Long， String)]  to solve this question?

Thanks in advance！！

**Comment by sahand1995** [comment]
same problem
