### ISSUE TITLE
Exception in thread "main" java.lang.NullPointerException 	at org.neo4j.spark.Neo4j.saveGraph

### ISSUE THREAD

**Issue by Yongquan-He** [neo4j-contrib/neo4j-spark-connector#91]
val sc =new SparkContext(conf)

    val neo=Neo4j(sc)
    val graphQuery = """MATCH (n)-[r]->(m) RETURN id(n) as source,id(m) as target,type(r) as value SKIP {_skip} LIMIT {_limit}"""

    val graph: Graph[Long, String] = neo.rels(graphQuery).partitions(10).batch(200).loadGraph
    val g = PageRank.run(graph, 5)
    neo.saveGraph(g,"rank")

**in the spark:8080, neo4j real run,but the savegraph report error,how do I solve it?**

**Comment by jexp** [comment]
1. **you need to share the full stacktrace**
2. does your connection to neo4j work?
3. are there null values in your data?

**Comment by andreclaudino** [comment]
I have the same error here, stacktrace is very poor

> [error] (run-main-0) java.lang.NullPointerException
[error] java.lang.NullPointerException
[error] 	at org.neo4j.spark.Neo4j.saveGraph(Neo4j.scala:303)
[error] 	at com.github.andreclaudino.recommender.jobs.PrepareForNeo4J$.saveNeo4J(PrepareForNeo4J.scala:129)
[error] 	at com.github.andreclaudino.recommender.jobs.PrepareForNeo4J$$anonfun$1.apply$mcJI$sp(PrepareForNeo4J.scala:98)
[error] 	at com.github.andreclaudino.recommender.jobs.PrepareForNeo4J$$anonfun$1.apply(PrepareForNeo4J.scala:91)
[error] 	at com.github.andreclaudino.recommender.jobs.PrepareForNeo4J$$anonfun$1.apply(PrepareForNeo4J.scala:91)
[error] 	at scala.collection.immutable.Range.foreach(Range.scala:160)
[error] 	at com.github.andreclaudino.recommender.jobs.PrepareForNeo4J$.delayedEndpoint$com$github$andreclaudino$recommender$jobs$PrepareForNeo4J$1(PrepareForNeo4J.scala:90)
[error] 	at com.github.andreclaudino.recommender.jobs.PrepareForNeo4J$delayedInit$body.apply(PrepareForNeo4J.scala:11)
[error] 	at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
[error] 	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
[error] 	at scala.App$$anonfun$main$1.apply(App.scala:76)
[error] 	at scala.App$$anonfun$main$1.apply(App.scala:76)
[error] 	at scala.collection.immutable.List.foreach(List.scala:392)
[error] 	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
[error] 	at scala.App$class.main(App.scala:76)
[error] 	at com.github.andreclaudino.recommender.jobs.PrepareForNeo4J$.main(PrepareForNeo4J.scala:11)
[error] 	at com.github.andreclaudino.recommender.jobs.PrepareForNeo4J.main(PrepareForNeo4J.scala)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.lang.reflect.Method.invoke(Method.java:498)
[error] stack trace is suppressed; run 'last Compile / bgRunMain' for the full output

In my case, there are no null values in dataframe.

**Comment by conker84** [comment]
I'm closing this because we got no feedback feel free to reopen in case the issue is not solved
