### ISSUE TITLE
Does neo4j-spark-connector distribute writes to different neo4j nodes?

### ISSUE THREAD

**Issue by kant111** [neo4j-contrib/neo4j-spark-connector#93]
It looks to me that there is no clustering available on the open source version of neo4j so does that mean writes from all spark executors must talk to one neo4j node? If not, Does neo4j-spark-connector distribute writes to different neo4j nodes?

**Comment by sandeepwww** [comment]
The documentation says, WRITES are allowed only on the LEADER node.

**Comment by conker84** [comment]
I'm closing this because it's more than 1yr old feel free to reopen in case the issue is not solved
