### ISSUE TITLE
Its showing error Neo4j not found

### ISSUE THREAD

**Issue by warkechetan** [neo4j-contrib/neo4j-spark-connector#95]
Whenever i write this statement val neo=Neo4j(sc) in scala it gives me error "Neo4j not found , i have imported every package given "

**Comment by jexp** [comment]
Did you provide the spark-package when you call spark-shell or spark-submit?

**Comment by warkechetan** [comment]
> Did you provide the spark-package when you call spark-shell or spark-submit?

Yes i have provided every package . Problem is there is no Neo4j.class file in my jar. Every other class is present but not Neo4j class. I have added dependency given on github

**Comment by azdafirmansyah** [comment]
Try this :

> resolvers += "Spark Packages Repo" at "http://dl.bintray.com/spark-packages/maven"
libraryDependencies += "neo4j-contrib" % "neo4j-spark-connector" % "2.4.0-M6"
libraryDependencies += "org.neo4j.driver" % "neo4j-java-driver" % "1.7.5"

I hope this can solve your problem
