### ISSUE TITLE
Task not serializable exception when using mergeEdgeList

### ISSUE THREAD

**Issue by wgf515** [neo4j-contrib/neo4j-spark-connector#96]
at org.apache.spark.sql.Dataset.withNewExecutionId(Dataset.scala:2823)
	at org.apache.spark.sql.Dataset.foreachPartition(Dataset.scala:2343)
	at org.neo4j.spark.Neo4jDataFrame$.mergeEdgeList

Here is the error log.

**Comment by wgf515** [comment]
".asJava" returns java.util.Map, it doesn't extends Serializable , but java.util.HashMap does.

**Comment by wgf515** [comment]
@jexp  I don't know why I got this problem. Could you help me to resolve it?

**Comment by conker84** [comment]
I'm closi

**Comment by conker84** [comment]
@wgf515 did you solved the problem?

**Comment by moxious** [comment]
Hi - I’m writing with good news.  Over the last few months, we’ve been investing a lot of effort in bringing the neo4j spark connector up to newer versions of spark, supporting the Datasource API, and enabling multi-language support for things like Python and R.

Today we’re putting out a pre-release of this new version of the spark connector.

You can download a build here:
https://github.com/neo4j-contrib/neo4j-spark-connector/releases/tag/4.0.0-pre1

And see the documentation here:
http://5.9.211.195:8000/neo4j-spark-docs/1.0.0/

We’re in the process of updating our guidance & documentation on spark.  We’re sorry, but we are unable fix issues & carry forward support of the earlier version of the connector, based on a different API - which went up to and included version 2.4.5-M2.  

Moving forward, we will be focusing our efforts on the new approach above.

As a result, we’re closing the remaining issues attached to the old version, but we would very much appreciate feedback & issues raised against the new 4.0 series of the connector, which you’ll find on the 4.0 branch of the repo.  The connector is going to stay open source, and our current issue list & github planning is in the open and will stay that way.  

We hope you find it a big improvement over the previous version,  and would welcome collaboration around this!
