### ISSUE TITLE
load a GraphFrame for a path with length 2 or more 

### ISSUE THREAD

**Issue by ZainLearn** [neo4j-contrib/neo4j-spark-connector#98]
Hi, 

I am trying to query neo4j from a path with length 2 or more. Here is what I use to load GraphFrame for a path of length one like this (Team) - [SomeRelation] -> (target):
` val nodesQuery = "match (n:Team) RETURN n.name as id UNION ALL MATCH (n:Game) RETURN n.name as id"`

`val relsQuery = "match (p:Team)-[r]-(c:Game) return p.name as src, c.name as dst, type(r) as value"`

`val graphFrame = Neo4j(sc).nodes(nodesQuery,Map.empty).rels(relsQuery,Map.empty).loadGraphFrame`

What would be the code please if I want to create GraphFrame for this pattern from neo4j:
(Team) - [SomeRelation] -> (Game) - [SomeOtherRelation] -> (Country) 
 
Thank you!

**Comment by conker84** [comment]
I'm closing this because it's almost 1 year old feel free to reopen in case the issue is not solved
